window.RECIPES_DB = [
  { name: "Jjigae Kimchi", ingredients: ["kimchi", "daging babi", "tahu", "bawang bombay", "daun bawang", "bawang putih", "bubuk cabai", "gochujang", "kecap asin"] },
  { name: "Bibimbap", ingredients: ["nasi", "daging sapi", "bayam", "tauge", "wortel", "zucchini", "telur", "gochujang", "rumput laut nori"] },
  { name: "Bulgogi", ingredients: ["daging sapi", "kecap asin", "bawang bombay", "pir", "gula", "minyak wijen", "bawang putih", "daun bawang", "merica"] },
  { name: "Japchae", ingredients: ["mie ubi jalar", "daging sapi", "bayam", "wortel", "bawang bombay", "jamur", "telur", "kecap asin", "minyak wijen"] },
  { name: "Tteokbokki", ingredients: ["kue beras", "odeng", "bawang bombay", "daun bawang", "gochujang", "gula", "kecap asin", "bawang putih", "telur rebus"] },
  { name: "Sundubu Jjigae", ingredients: ["tahu lembut", "daging babi", "telur", "zucchini", "bawang bombay", "daun bawang", "bawang putih", "bubuk cabai", "kecap asin"] },
  { name: "Samgyeopsal", ingredients: ["perut babi", "selada", "bawang putih", "ssamjang", "daun bawang", "garam", "merica"] },
  { name: "Nasi goreng kimchi", ingredients: ["kimchi", "nasi", "telur", "daging babi", "daun bawang", "kecap asin", "minyak wijen"] },
  { name: "Galbijjim", ingredients: ["iga sapi", "bawang bombay", "wortel", "kentang", "kecap asin", "gula", "pir", "bawang putih", "minyak wijen"] },
  { name: "Jajangmyeon", ingredients: ["mie", "daging babi", "bawang bombay", "zucchini", "kentang", "chunjang", "timun", "telur"] },
  { name: "Sushi", ingredients: ["nasi", "cuka", "gula", "garam", "rumput laut nori", "salmon", "tuna", "udang", "alpukat", "timun"] },
  { name: "Ramen", ingredients: ["mie", "daging babi", "telur", "daun bawang", "menma", "rumput laut nori", "kecap asin", "miso", "bawang putih"] },
  { name: "Katsudon", ingredients: ["nasi", "tonkatsu", "telur", "bawang bombay", "kecap asin", "gula", "mirin"] },
  { name: "Okonomiyaki", ingredients: ["tepung terigu", "telur", "kol", "daging babi", "udang", "daun bawang", "mayones", "saus okonomiyaki"] },
  { name: "Mapo tofu", ingredients: ["tahu", "daging babi cincang", "daun bawang", "bawang putih", "jahe", "kecap asin", "doubanjiang", "merica Sichuan"] },
  { name: "Bebek Peking", ingredients: ["bebek", "timun", "daun bawang", "tianmianjiang", "crepe tipis"] },
  { name: "Daging babi asam manis", ingredients: ["daging babi", "nanas", "paprika", "bawang bombay", "cuka", "gula", "saus tomat", "kecap asin"] },
  { name: "Pad Thai", ingredients: ["mie beras", "udang", "telur", "tahu", "tauge", "kacang tanah", "asam jawa", "saus ikan", "jeruk nipis"] },
  { name: "Tom Yum Kung", ingredients: ["udang", "serai", "jeruk nipis", "lengkuas", "jamur", "cabai", "saus ikan", "ketumbar"] },
  { name: "Pho", ingredients: ["mie beras", "daging sapi", "bawang bombay", "jahe", "kayu manis", "cengkeh", "saus ikan", "tauge", "jeruk nipis", "kemangi"] },
  { name: "Nasi ayam Hainan", ingredients: ["ayam", "nasi", "jahe", "bawang putih", "timun", "kecap asin", "saus cabai"] },
  { name: "Lumpia segar", ingredients: ["kulit lumpia", "udang", "daging babi", "selada", "mie beras", "mint", "ketumbar"] },
  { name: "Kari hijau", ingredients: ["ayam", "pasta kari hijau", "santan", "terong", "kemangi", "saus ikan", "gula"] },
  { name: "Nasi Goreng", ingredients: ["nasi", "ayam", "telur", "kecap asin", "udang", "daun bawang", "cabai"] },
  { name: "Satay", ingredients: ["ayam", "kacang tanah", "kecap asin", "serai", "bawang putih", "kunyit"] },
  { name: "Laksa", ingredients: ["mie beras", "udang", "santan", "tahu", "tauge", "telur", "cabai", "ketumbar"] },
  { name: "Chow Mein", ingredients: ["mie", "ayam", "tauge", "kol", "wortel", "kecap asin", "daun bawang"] },
  { name: "Nasi goreng", ingredients: ["nasi", "telur", "wortel", "kacang polong", "daun bawang", "udang", "kecap asin"] },
  { name: "Gyoza", ingredients: ["tepung terigu", "kol", "daging babi", "bawang putih", "jahe", "daun bawang", "kecap asin"] },
  { name: "Unadon", ingredients: ["nasi", "belut", "kecap asin", "mirin", "gula", "telur"] },
  { name: "Hamburger", ingredients: ["daging sapi", "roti", "selada", "tomat", "bawang bombay", "keju", "acar"] },
  { name: "Cheeseburger", ingredients: ["daging sapi", "roti", "keju", "selada", "tomat", "bawang bombay", "acar"] },
  { name: "Ayam goreng", ingredients: ["ayam", "tepung terigu", "telur", "minyak", "garam", "merica"] },
  { name: "Iga BBQ", ingredients: ["iga babi", "saus BBQ", "gula merah", "garam", "merica", "bubuk bawang putih"] },
  { name: "Salad Caesar", ingredients: ["selada", "keju parmesan", "crouton", "ikan teri", "telur", "saus Caesar"] },
  { name: "Sandwich BLT", ingredients: ["roti", "bacon", "selada", "tomat", "mayones"] },
  { name: "Spaghetti carbonara", ingredients: ["spaghetti", "telur", "keju parmesan", "pancetta", "merica"] },
  { name: "Lasagna", ingredients: ["lembaran lasagna", "daging sapi cincang", "saus tomat", "keju ricotta", "mozzarella", "keju parmesan", "telur"] },
  { name: "Pizza Margherita", ingredients: ["adonan pizza", "saus tomat", "mozzarella", "kemangi", "minyak zaitun"] },
  { name: "Paella", ingredients: ["nasi", "udang", "kerang", "ayam", "chorizo", "kacang polong", "saffron", "paprika", "paprika"] },
  { name: "Croque Monsieur", ingredients: ["roti", "ham", "keju", "mentega", "susu", "tepung terigu", "mustard"] },
  { name: "Quiche Lorraine", ingredients: ["kulit pie", "telur", "bacon", "keju", "krim", "bawang bombay"] },
  { name: "Ratatouille", ingredients: ["terong", "zucchini", "paprika", "tomat", "bawang bombay", "bawang putih"] },
  { name: "Bouillabaisse", ingredients: ["ikan", "kerang", "udang", "tomat", "bawang putih", "bawang bombay", "adas", "saffron"] },
  { name: "Crêpe", ingredients: ["tepung terigu", "telur", "susu", "mentega", "gula", "garam"] },
  { name: "Tortilla Spanyol", ingredients: ["telur", "kentang", "bawang bombay", "minyak zaitun", "garam"] },
  { name: "Gazpacho", ingredients: ["tomat", "timun", "paprika", "bawang bombay", "bawang putih", "minyak zaitun", "cuka"] },
  { name: "Patatas bravas", ingredients: ["kentang", "minyak zaitun", "paprika", "tomat", "saus alioli"] },
  { name: "Churros", ingredients: ["tepung terigu", "telur", "mentega", "gula", "garam", "minyak", "kayu manis"] },
  { name: "Salad Niçoise dengan tuna", ingredients: ["selada", "tuna", "telur", "kentang", "buncis", "zaitun", "tomat", "ikan teri"] },
  { name: "Tacos", ingredients: ["tortilla", "daging sapi", "selada", "tomat", "keju", "bawang bombay", "sour cream", "guacamole"] },
  { name: "Enchilada", ingredients: ["tortilla", "ayam", "keju", "bawang bombay", "saus enchilada", "sour cream"] },
  { name: "Burrito", ingredients: ["tortilla", "nasi", "kacang", "daging sapi", "selada", "keju", "salsa"] },
  { name: "Ceviche", ingredients: ["ikan", "jeruk nipis", "bawang bombay", "cabai", "ketumbar", "tomat"] },
  { name: "Feijoada", ingredients: ["kacang hitam", "daging babi", "daging sapi", "sosis", "nasi", "bawang bombay", "bawang putih"] },
  { name: "Empanada", ingredients: ["tepung terigu", "daging sapi", "bawang bombay", "telur", "zaitun", "kismis", "paprika"] },
  { name: "Moussaka", ingredients: ["terong", "kentang", "daging sapi cincang", "tomat", "bawang bombay", "saus bechamel"] },
  { name: "Salad Yunani", ingredients: ["tomat", "timun", "zaitun", "keju feta", "bawang bombay", "minyak zaitun"] },
  { name: "Shakshuka", ingredients: ["telur", "tomat", "paprika", "bawang bombay", "bawang putih", "jinten", "paprika"] },
  { name: "Falafel", ingredients: ["chickpea", "bawang bombay", "bawang putih", "peterseli", "ketumbar", "jinten", "tepung terigu"] },
  { name: "Hummus", ingredients: ["chickpea", "tahini", "bawang putih", "lemon", "minyak zaitun"] },
  { name: "Shawarma", ingredients: ["ayam", "daging sapi", "roti pita", "selada", "tomat", "bawang bombay", "yogurt", "bawang putih"] },
  { name: "Couscous", ingredients: ["couscous", "ayam", "wortel", "zucchini", "chickpea", "bawang bombay"] },
  { name: "Tajine", ingredients: ["domba", "aprikot", "almond", "bawang bombay", "kayu manis", "ketumbar", "saffron"] },
  { name: "Ayam mentega", ingredients: ["ayam", "mentega", "krim", "tomat", "bawang bombay", "garam masala"] },
  { name: "Ayam tandoori", ingredients: ["ayam", "yogurt", "garam masala", "jinten", "bawang putih", "jahe", "cabai"] },
  { name: "Palak paneer", ingredients: ["bayam", "paneer", "krim", "bawang bombay", "tomat", "bawang putih", "jinten"] },
  { name: "Dal Tadka", ingredients: ["lentil", "bawang bombay", "tomat", "bawang putih", "jahe", "jinten", "kunyit", "ghee"] },
  { name: "Biryani", ingredients: ["nasi", "ayam", "yogurt", "bawang bombay", "garam masala", "saffron"] },
  { name: "Samosa", ingredients: ["tepung terigu", "kentang", "kacang polong", "bawang bombay", "jinten", "ketumbar"] },
  { name: "Fettuccine Alfredo", ingredients: ["fettuccine", "mentega", "krim", "keju parmesan"] },
  { name: "Ayam parmesan", ingredients: ["ayam", "telur", "tepung roti", "keju parmesan", "mozzarella", "saus tomat"] },
  { name: "Stroganoff daging sapi", ingredients: ["daging sapi", "bawang bombay", "jamur", "sour cream", "mentega", "tepung terigu"] },
  { name: "Telur benedict", ingredients: ["telur", "english muffin", "ham", "saus hollandaise", "mentega"] },
  { name: "Bisque lobster", ingredients: ["lobster", "krim", "mentega", "bawang bombay", "seledri", "wortel", "cognac"] },
  { name: "Clam chowder", ingredients: ["kerang", "kentang", "bawang bombay", "seledri", "bacon", "krim", "mentega"] },
  { name: "Pie ayam", ingredients: ["ayam", "wortel", "kentang", "kacang polong", "bawang bombay", "kulit pie", "krim"] },
  { name: "Meatloaf", ingredients: ["daging sapi", "telur", "tepung roti", "bawang bombay", "saus tomat", "mustard"] },
  { name: "French toast", ingredients: ["roti", "telur", "susu", "kayu manis", "gula", "mentega"] },
  { name: "Pancake", ingredients: ["tepung terigu", "telur", "susu", "baking powder", "gula", "mentega"] },
  { name: "Waffle", ingredients: ["tepung terigu", "telur", "susu", "baking powder", "gula", "mentega"] },
  { name: "Banana bread", ingredients: ["pisang", "tepung terigu", "telur", "gula", "mentega"] },
  { name: "Pie apel", ingredients: ["apel", "tepung terigu", "telur", "gula", "mentega", "kayu manis"] },
  { name: "Pie lemon", ingredients: ["lemon", "telur", "gula", "mentega", "tepung terigu"] },
  { name: "Brownie", ingredients: ["cokelat", "tepung terigu", "telur", "gula", "mentega"] },
  { name: "Cheesecake", ingredients: ["cream cheese", "telur", "gula", "mentega", "graham cracker"] },
  { name: "Sup labu", ingredients: ["labu", "bawang bombay", "bawang putih", "krim", "mentega"] },
  { name: "Minestrone", ingredients: ["kacang", "wortel", "seledri", "bawang bombay", "tomat", "pasta"] },
  { name: "Omelet Prancis", ingredients: ["telur", "susu", "keju", "ham", "bawang bombay", "paprika"] },
  { name: "Telur orak-arik", ingredients: ["telur", "susu", "mentega", "garam", "merica"] },
  { name: "Quesadilla", ingredients: ["tortilla", "keju", "ayam", "paprika", "bawang bombay"] },
  { name: "Fajita", ingredients: ["daging sapi", "bawang bombay", "paprika", "tortilla", "sour cream"] },
  { name: "Pulled pork", ingredients: ["daging babi", "saus BBQ", "gula merah", "bawang bombay", "roti"] },
  { name: "Fish and chips", ingredients: ["ikan", "kentang", "tepung terigu", "telur", "minyak"] },
  { name: "Shepherd's pie", ingredients: ["daging domba cincang", "kentang", "wortel", "bawang bombay", "kacang polong", "saus gravy"] },
  { name: "Steak", ingredients: ["daging sapi", "garam", "merica", "mentega", "bawang putih"] },
  { name: "Lamb chop", ingredients: ["domba", "garam", "merica", "bawang putih", "rosemary"] },
  { name: "Ayam panggang", ingredients: ["ayam", "garam", "merica", "bawang putih", "thyme", "minyak zaitun"] },
  { name: "Kari ayam", ingredients: ["ayam", "bawang bombay", "tomat", "bawang putih", "jahe", "bubuk kari", "santan"] },
  { name: "Udang scampi", ingredients: ["udang", "bawang putih", "mentega", "lemon", "peterseli", "spaghetti"] },
  { name: "Paella seafood", ingredients: ["nasi", "udang", "kerang", "cumi", "kacang polong", "saffron"] },
  { name: "Chicken cacciatore", ingredients: ["ayam", "tomat", "bawang bombay", "paprika", "jamur", "bawang putih"] },
  { name: "Boeuf Bourguignon", ingredients: ["daging sapi", "anggur merah", "bawang bombay", "wortel", "seledri", "bawang putih", "thyme"] },
  { name: "Goulash", ingredients: ["daging sapi", "bawang bombay", "paprika", "tomat", "paprika", "bawang putih"] },
  { name: "Borscht", ingredients: ["bit", "kol", "kentang", "wortel", "bawang bombay", "dill"] },
  { name: "Pierogi", ingredients: ["tepung terigu", "telur", "kentang", "keju", "bawang bombay", "mentega"] },
  { name: "Baklava", ingredients: ["kulit phyllo", "walnut", "pistachio", "gula", "mentega", "madu"] },
  { name: "Dolma", ingredients: ["daun anggur", "nasi", "bawang bombay", "pine nut", "dill"] },
  { name: "Gulungan kol", ingredients: ["kol", "daging sapi", "nasi", "bawang bombay", "saus tomat"] },
  { name: "Irish stew", ingredients: ["domba", "kentang", "wortel", "bawang bombay", "seledri"] },
  { name: "Cassoulet", ingredients: ["kacang putih", "daging babi", "bebek", "sosis", "bawang bombay", "bawang putih"] },
  { name: "Börek", ingredients: ["kulit phyllo", "keju", "kentang", "telur", "wijen"] },
  { name: "Sauerbraten", ingredients: ["daging sapi", "bawang bombay", "wortel", "seledri", "cuka", "jahe"] },
  { name: "Wiener Schnitzel", ingredients: ["daging sapi", "telur", "tepung terigu", "tepung roti", "lemon"] },
  { name: "Zwiebelrostbraten", ingredients: ["daging sapi", "bawang bombay", "mentega", "tepung terigu", "kaldu sapi"] },
  { name: "Rösti", ingredients: ["kentang", "mentega", "bawang bombay", "bacon"] },
  { name: "Spätzle", ingredients: ["tepung terigu", "telur", "susu", "mentega"] },
  { name: "Sup goulash", ingredients: ["daging sapi", "bawang bombay", "paprika", "kentang", "wortel"] },
  { name: "Chicken Kiev", ingredients: ["ayam", "mentega", "bawang putih", "peterseli", "telur", "tepung terigu", "tepung roti"] },
  { name: "Plov", ingredients: ["nasi", "daging sapi", "wortel", "bawang bombay", "jinten"] },
  { name: "Manti", ingredients: ["tepung terigu", "telur", "daging sapi", "bawang bombay", "yogurt"] },
  { name: "Mie gaya Peking", ingredients: ["mie", "daging babi", "telur", "daun bawang", "kecap asin"] },
  { name: "Jollof rice", ingredients: ["nasi", "tomat", "bawang bombay", "paprika", "cabai", "bawang putih"] },
  { name: "Bobotie", ingredients: ["daging sapi", "roti", "telur", "bawang bombay", "susu", "bubuk kari"] },
  { name: "Bunny Chow", ingredients: ["roti", "ayam", "bawang bombay", "tomat", "bubuk kari"] },
  { name: "Chakalaka", ingredients: ["kacang", "bawang bombay", "tomat", "cabai", "wortel", "paprika"] },
  { name: "Pav Bhaji", ingredients: ["roti", "kentang", "kacang polong", "wortel", "bawang bombay", "tomat", "mentega"] },
  { name: "Vada Pav", ingredients: ["roti", "kentang", "cabai", "ketumbar", "bawang putih", "biji mustard"] },
  { name: "Masala Dosa", ingredients: ["nasi", "lentil", "kentang", "bawang bombay", "biji mustard", "daun kari"] },
  { name: "Idli", ingredients: ["nasi", "lentil", "garam"] },
  { name: "Sambar", ingredients: ["lentil", "wortel", "bawang bombay", "tomat", "terong", "drumstick", "campuran rempah"] },
  { name: "Katsu curry", ingredients: ["nasi", "tonkatsu", "saus kari", "bawang bombay", "wortel", "kentang"] },
  { name: "Takoyaki", ingredients: ["tepung terigu", "telur", "gurita", "daun bawang", "tenkasu", "mayones", "saus takoyaki"] },
  { name: "Sukiyaki", ingredients: ["daging sapi", "tahu", "daun bawang", "shiitake", "shirataki", "telur"] },
  { name: "Nabe", ingredients: ["kol", "tahu", "shiitake", "wortel", "ayam", "udon"] },
  { name: "Sup telur", ingredients: ["telur", "kaldu ayam", "tepung kentang", "daun bawang", "kecap asin"] },
  { name: "Sup asam pedas", ingredients: ["tahu", "telur", "jamur", "menma", "cuka", "kecap asin", "merica"] },
  { name: "Tumis daging sapi dan brokoli", ingredients: ["daging sapi", "brokoli", "kecap asin", "bawang putih", "jahe", "bawang bombay"] },
  { name: "Ayam lemon", ingredients: ["ayam", "lemon", "telur", "tepung terigu", "kecap asin", "gula"] },
  { name: "Nasi goreng nanas", ingredients: ["nasi", "nanas", "udang", "telur", "kacang mete", "daun bawang"] },
  { name: "Bánh mì", ingredients: ["baguette", "daging babi", "wortel", "timun", "ketumbar", "mayones", "pâté"] },
  { name: "Khao Soi", ingredients: ["mie telur", "ayam", "santan", "pasta kari", "acar"] },
  { name: "Bak Kut Teh", ingredients: ["iga babi", "bawang putih", "kecap asin", "merica putih", "jamur"] },
  { name: "Laksa Singapura", ingredients: ["mie beras", "udang", "santan", "tahu", "tauge", "telur", "cabai", "ketumbar"] },
  { name: "Gado-gado", ingredients: ["sayuran", "tahu", "telur", "saus kacang", "tauge"] },
  { name: "Nasi Lemak", ingredients: ["nasi", "santan", "telur", "ikan bilis", "kacang tanah", "timun", "saus sambal"] },
  { name: "Pasta dengan pesto arugula", ingredients: ["arugula", "pasta", "keju parmesan", "minyak zaitun", "pine nut"] },
  { name: "Shakshuka dengan keju feta", ingredients: ["telur", "tomat", "paprika", "bawang bombay", "keju feta", "ketumbar"] },
  { name: "Pancake buttermilk", ingredients: ["tepung terigu", "telur", "buttermilk", "gula", "baking powder"] },
  { name: "Salad quinoa", ingredients: ["quinoa", "timun", "tomat", "keju feta", "lemon", "minyak zaitun"] },
  { name: "Salad Caesar kale", ingredients: ["kale", "keju parmesan", "crouton", "ikan teri", "telur", "saus Caesar"] },
  { name: "Buddha bowl vegan", ingredients: ["beras merah", "chickpea", "alpukat", "bayam", "wortel", "tahu"] },
  { name: "Terong parmesan", ingredients: ["terong", "saus tomat", "mozzarella", "keju parmesan", "kemangi"] },
  { name: "Paprika isi", ingredients: ["paprika", "nasi", "daging sapi cincang", "bawang bombay", "tomat", "keju"] },
  { name: "Lamb chop panggang", ingredients: ["domba", "bawang putih", "rosemary", "minyak zaitun", "garam", "merica"] },
  { name: "Sup lentil", ingredients: ["lentil", "wortel", "seledri", "bawang bombay", "tomat", "bawang putih"] },
  { name: "Brussels sprouts panggang", ingredients: ["brussels sprouts", "minyak zaitun", "garam", "merica", "lemon"] },
  { name: "Ayam pesto", ingredients: ["ayam", "pesto kemangi", "keju parmesan", "minyak zaitun"] },
  { name: "Salsa mangga", ingredients: ["mangga", "bawang bombay", "jeruk nipis", "ketumbar", "cabai"] },
  { name: "Cod panggang", ingredients: ["cod", "lemon", "minyak zaitun", "peterseli", "tepung roti"] },
  { name: "Coleslaw Asia", ingredients: ["sawi putih", "wortel", "daun bawang", "kecap asin", "cuka beras", "minyak wijen"] },
  { name: "Salad mie dengan kacang", ingredients: ["mie", "kacang tanah", "wortel", "timun", "kecap asin", "minyak wijen"] },
  { name: "Chili vegan", ingredients: ["kacang hitam", "tomat", "bawang bombay", "bubuk cabai", "jagung", "paprika"] },
  { name: "Taco jackfruit", ingredients: ["jackfruit", "tortilla", "kol", "jeruk nipis", "alpukat", "ketumbar"] },
  { name: "Tumis tahu dan sayuran", ingredients: ["tahu", "brokoli", "paprika", "kecap asin", "jahe", "bawang putih"] },
  { name: "Risotto labu", ingredients: ["labu", "nasi", "keju parmesan", "bawang bombay", "bawang putih"] },
  { name: "Toast ratatouille", ingredients: ["terong", "zucchini", "paprika", "bawang bombay", "roti"] },
  { name: "Salad bit", ingredients: ["bit", "arugula", "walnut", "keju kambing", "balsamic"] },
  { name: "Tajine Maroko", ingredients: ["domba", "aprikot", "almond", "bawang bombay", "kayu manis", "ketumbar", "saffron"] },
  { name: "Steak dengan chimichurri", ingredients: ["daging sapi", "peterseli", "bawang putih", "minyak zaitun", "oregano", "cuka"] },
  { name: "Fritter zucchini", ingredients: ["zucchini", "telur", "tepung terigu", "keju parmesan", "daun bawang"] },
  { name: "Sup miso", ingredients: ["miso", "tahu", "wakame", "daun bawang", "kaldu dashi"] },
  { name: "Wrap falafel", ingredients: ["falafel", "roti pita", "selada", "tomat", "tahini"] },
  { name: "Laksa dengan udang", ingredients: ["udang", "mie beras", "santan", "pasta laksa", "telur", "tauge"] },
  { name: "Bowl couscous", ingredients: ["couscous", "chickpea", "wortel", "zucchini", "lemon"] },
  { name: "Ayam goreng Korea manis", ingredients: ["ayam", "gochujang", "kecap asin", "gula", "sirup jagung", "bawang putih", "jahe", "adonan tepung"] },
  { name: "Budae Jjigae", ingredients: ["ham", "sosis", "kimchi", "tahu", "tauge", "ramen", "gochujang", "bubuk cabai", "daun bawang"] },
  { name: "Sup iga sapi", ingredients: ["iga sapi", "lobak putih", "daun bawang", "bawang putih", "jahe", "kecap asin", "mie ubi jalar"] },
  { name: "Pancake seafood Korea", ingredients: ["cumi", "udang", "daun bawang", "tepung terigu", "telur", "air", "kecap asin", "cuka"] },
  { name: "Yukgaejang", ingredients: ["daging sapi", "pakis", "tauge", "batang talas", "daun bawang", "bubuk cabai", "kecap asin", "bawang putih"] },
  { name: "Bossam", ingredients: ["daging babi", "bawang putih", "jahe", "daun bawang", "miso", "saus udang asin", "kimchi lobak", "sawi putih"] },
  { name: "Samgyetang", ingredients: ["ayam", "ginseng", "kurma merah", "bawang putih", "beras ketan", "daun bawang", "garam"] },
  { name: "Jjimdak", ingredients: ["ayam", "kentang", "wortel", "bawang bombay", "daun bawang", "mie ubi jalar", "kecap asin", "gula", "bawang putih"] },
  { name: "Bibim guksu", ingredients: ["mie", "gochujang", "cuka", "gula", "timun", "selada", "telur", "minyak wijen"] },
  { name: "Kimbap", ingredients: ["nasi", "rumput laut nori", "takuwan", "bayam", "wortel", "telur", "ham", "odeng", "minyak wijen"] },
  { name: "Jeyuk bokkeum", ingredients: ["daging babi", "gochujang", "bubuk cabai", "kecap asin", "gula", "bawang putih", "bawang bombay", "daun bawang"] },
  { name: "Dakbokkeumtang", ingredients: ["ayam", "kentang", "wortel", "bawang bombay", "daun bawang", "gochujang", "bubuk cabai", "bawang putih"] },
  { name: "Doenjang jjigae", ingredients: ["miso", "tahu", "zucchini", "bawang bombay", "daun bawang", "jamur", "cabai", "kaldu ikan teri"] },
  { name: "Agujjim", ingredients: ["ikan monkfish", "tauge", "midodok", "seri", "bubuk cabai", "bawang putih", "kecap asin", "tepung kentang"] },
  { name: "Gopchang jeongol", ingredients: ["usus sapi", "daun bawang", "bawang bombay", "daun perilla", "jamur", "tahu", "bubuk cabai", "bawang putih cincang", "kaldu"] },
  { name: "Ayam goreng pedas Korea", ingredients: ["ayam", "gochujang", "sirup jagung", "saus tomat", "bawang putih", "kecap asin", "kacang tanah", "adonan tepung"] },
  { name: "Gukbap", ingredients: ["nasi", "daging babi", "jeroan", "daun bawang", "bawang putih", "bubuk cabai", "sundae"] },
  { name: "Pasta aglio e olio", ingredients: ["spaghetti", "bawang putih", "minyak zaitun", "cabai", "peterseli"] },
  { name: "Pasta alle vongole", ingredients: ["spaghetti", "kerang", "bawang putih", "minyak zaitun", "anggur putih", "peterseli"] },
  { name: "Udang scampi", ingredients: ["udang", "bawang putih", "minyak zaitun", "cabai", "baguette"] },
  { name: "Bistik dengan saus", ingredients: ["daging sapi", "paprika", "bawang bombay", "jamur", "kecap asin", "saus tomat", "gula", "saus bistik"] },
  { name: "Salad ricotta", ingredients: ["keju ricotta", "sayuran hijau", "vinaigrette balsamic", "tomat", "kacang walnut"] },
  { name: "Pancake kentang Korea", ingredients: ["kentang", "bawang bombay", "adonan pancake", "air", "garam", "minyak"] },
  { name: "Mackerel panggang", ingredients: ["mackerel", "garam", "merica", "lemon", "minyak"] },
  { name: "Tumis gurita kecil", ingredients: ["gurita kecil", "bawang bombay", "daun bawang", "kol", "gochujang", "bubuk cabai", "bawang putih", "gula"] },
  { name: "Tumis kaki ayam", ingredients: ["kaki ayam", "gochujang", "bubuk cabai", "bawang putih", "bawang bombay", "daun bawang", "gula", "sirup jagung"] },
  { name: "Es krim", ingredients: ["susu", "gula", "kuning telur", "krim", "vanila"] },
  { name: "Tiramisu", ingredients: ["keju mascarpone", "ladyfinger", "kopi", "gula", "kuning telur", "bubuk kakao"] },
  { name: "Macaron", ingredients: ["tepung almond", "gula halus", "putih telur", "gula", "pewarna makanan"] },
  { name: "Croffle", ingredients: ["adonan croissant", "waffle maker", "gula", "mentega"] },
  { name: "Egg tart", ingredients: ["kulit pie", "telur", "susu", "gula", "krim", "ekstrak vanila"] },
  { name: "Roti dengan anko dan mentega", ingredients: ["roti", "pasta kacang merah", "mentega"] },
  { name: "Hotteok", ingredients: ["tepung terigu", "gula", "ragi", "air", "biji-bijian", "madu"] },
  { name: "Bungeoppang", ingredients: ["tepung terigu", "telur", "susu", "gula", "pasta kacang merah", "mentega"] },
  { name: "Hot dog", ingredients: ["sosis", "roti", "saus tomat", "mustard", "bawang bombay", "acar"] },
  { name: "Sup bawang Prancis", ingredients: ["bawang bombay", "kaldu sapi", "roti", "keju", "mentega", "tepung terigu"] },
  { name: "Spaghetti dengan bakso", ingredients: ["spaghetti", "daging sapi cincang", "saus tomat", "bawang bombay", "bawang putih", "tepung roti", "telur"] },
  { name: "Taco ikan", ingredients: ["ikan", "tortilla", "kol", "salsa", "jeruk nipis", "ketumbar"] },
  { name: "Scone keju", ingredients: ["tepung terigu", "mentega", "susu", "keju", "baking powder"] },
  { name: "Muffin blueberry", ingredients: ["tepung terigu", "blueberry", "gula", "telur", "susu", "minyak", "baking powder"] }
];

window.INGREDIENTS_DB = [
  "telur", "ayam", "daging sapi", "daging babi", "bawang bombay", "bawang putih", "wortel", "kentang", "spaghetti", "nasi", "tomat", "selada",
  "tahu", "tauge", "kacang tanah", "anggur merah", "miso", "rumput laut nori", "kimchi", "bacon", "keju parmesan", "ikan teri", "roti",
  "keju", "udang", "serai", "lengkuas", "jeruk nipis", "paprika", "terong", "zucchini", "crouton", "kaldu dashi",
  "pancetta", "merica", "jamur", "yogurt", "tepung terigu", "gula", "garam", "mentega", "susu", "krim", "timun",
  "apel", "pisang", "jeruk", "lemon", "jeruk nipis", "brokoli", "bayam", "labu", "ubi jalar", "jagung", "kacang polong",
  "kol", "seledri", "jahe", "kecap asin", "cuka", "minyak zaitun", "minyak canola", "minyak bunga matahari", "minyak wijen",
  "saus ikan", "saus tiram", "pasta kacang manis (tianmianjiang)", "saus tomat", "mustard", "mayones", "kemangi", "ketumbar", "peterseli",
  "rosemary", "thyme", "sage", "mint", "kayu manis", "pala", "cengkeh", "daun salam", "adas bintang", "kapulaga",
  "bubuk kari", "bubuk cabai", "paprika", "kunyit", "jinten", "ketumbar (biji)", "dill", "adas", "vanila",
  "cokelat", "bubuk kakao", "selai", "madu", "sirup maple", "molase", "stroberi", "blueberry", "raspberry",
  "cranberry", "blackberry", "nanas", "mangga", "kiwi", "anggur", "pir", "persik", "aprikot", "plum", "kurma merah",
  "buah ara", "kelapa", "kacang walnut", "almond", "hazelnut", "kacang mete", "pistachio", "macadamia", "pecan", "biji bunga matahari",
  "biji chia", "biji labu", "wijen", "quinoa", "barley", "millet", "buckwheat", "oat", "roti", "pasta",
  "mie", "tortilla", "roti naan", "roti pita", "roti sourdough", "bagel", "croissant", "donat", "adonan pizza", "cracker",
  "sosis", "salami", "ham", "bebek", "domba", "kalkun", "kelinci", "daging sapi muda", "angsa", "ikan teri", "sarden", "tuna",
  "mackerel", "salmon", "cod", "haddock", "whiting", "lele", "tilapia", "cumi", "gurita", "kerang", "kerang hijau",
  "scallop", "lobster", "kepiting", "crawfish", "abalone", "teripang", "bulu babi", "wasabi", "lobak pedas",
  "tabasco", "saus sriracha", "gochujang", "ssamjang", "miso", "miso", "kacang merah", "kacang hitam", "kacang",
  "chickpea", "lentil", "kacang", "kacang putih", "buncis", "kacang polong manis", "kacang polong manis", "edamame", "mozzarella",
  "cheddar", "gouda", "brie", "camembert", "feta", "keju biru", "swiss", "provolone", "ricotta",
  "mascarpone", "cream cheese", "cottage cheese", "sour cream", "yogurt", "buttermilk", "susu kental",
  "susu kental manis", "susu bubuk", "susu almond", "susu kedelai", "susu beras", "santan", "susu oat",
  "pasta udang", "pasta ikan teri", "pasta tomat", "saus tomat", "pesto", "saus pedas", "harissa", "azba",
  "tahini", "hummus", "guacamole", "salsa", "relish", "tapenade", "saus gravy", "kaldu", "kaldu", "kaldu", "gelatin",
  "agar-agar", "tepung kentang", "tepung kentang", "tapioka", "arrowroot", "tepung beras", "semolina", "tepung jagung",
  "polenta", "wheat germ", "wheat bran", "kulit lumpia", "kulit lumpia", "rumput laut nori", "kue beras", "udon", "ramen",
  "mie soun", "soba", "fettuccine", "penne", "makaroni", "lasagna", "spaghetti", "linguine", "angel hair",
  "gnocchi", "ravioli", "tortellini", "gyoza", "wonton", "pierogi", "empanada", "tamale", "daun bawang",
  "bawang merah", "daun bawang", "lobak", "radish", "parsnip", "rutabaga", "bit", "kohlrabi", "lobak putih (daikon)", "jicama", "akar teratai",
  "artichoke", "asparagus", "okra", "rebung (menma)", "kuning telur", "putih telur", "telur puyuh", "telur bebek", "telur angsa",
  "truffle", "morel", "porcini", "enoki", "shiitake", "oyster mushroom", "porcini", "champignon", "portobello",
  "chestnut", "arrowhead", "talas", "ubi", "singkong", "salsify", "jerusalem artichoke", "adas (umbi)",
  "arugula", "pesto kemangi", "paprika", "bok choy", "brussels sprouts", "buttermilk", "caper",
  "karamel", "caraway", "kacang mete", "chia", "minyak cabai", "chive", "biji ketumbar", "cottage cheese",
  "kepiting", "cranberry", "krim", "watercress", "dandelion", "kurma", "kulit lumpia", "spelt", "fenugreek",
  "keju feta", "selai kacang", "keju kambing", "buncis", "jambu biji", "hazelnut", "biji hemp", "campuran herbal",
  "jackfruit", "kale", "jus kimchi", "kumquat", "daun bawang", "pasta lentil", "leci", "chutney mangga",
  "keju manchego", "bacon maple", "marjoram", "mizuna", "monk fruit", "saus jamur", "mustard green",
  "sawi putih", "nektarin", "okra", "zaitun", "kulit jeruk", "pepaya", "markisa", "kecambah kacang polong",
  "pecan", "keju pepper jack", "kesemek", "pine nut", "krim pistachio", "tomat plum", "popcorn", "prosciutto",
  "roti pumpernickel", "quark", "radicchio", "ras el hanout", "lentil merah", "ricotta salata", "arugula", "selada romaine",
  "roquefort", "air mawar", "rutabaga", "sagu", "salsify", "kol savoy", "chive hijau", "bawang merah",
  "shiso", "tahu sutra", "salmon asap", "kacang polong manis", "kacang polong manis", "sorrel", "protein kedelai", "spelt",
  "tinta cumi", "stilton", "jamur nameko", "sumac", "tomat kering", "jagung manis", "swiss chard",
  "asam jawa", "tempeh", "thyme", "wijen sangrai", "yuba", "tomat", "minyak truffle", "daun lobak",
  "jeruk valencia", "keju vegan", "daging rusa", "mie soun", "nasi cuka", "watercress", "tepung terigu",
  "cokelat putih", "beras liar", "ubi", "zaatar", "kulit jeruk", "bunga zucchini", "kacang merah", "amaranth",
  "adas manis", "rebung", "paprika pisang", "biji kemangi", "scallop kecil", "bawang hitam", "jeruk darah",
  "borage", "bresaola", "kaktus", "cumi", "melon canary", "jahe manisan", "daun wortel", "tepung singkong",
  "seledri", "chayote", "jamur shimeji", "chorizo", "cloudberry", "gula kelapa", "bawang putih konfit",
  "salad jagung", "kacang cranberry", "jamur cremini", "dolma", "edamame", "pakis", "telur ikan", "frisee", "garam masala",
  "chive bawang putih", "goji berry", "bit emas", "bawang putih muda", "guanciale", "kaki babi", "akar lobak pedas",
  "jerusalem artichoke", "citrus kobu", "licorice", "rumput laut kombu", "lardon", "lavender", "limoncello", "kacang panjang",
  "biji teratai", "karamel miso", "mijtra", "mulberry", "muscat", "nasturtium", "jelatang", "daun okra",
  "zaitun orali", "daun parsnip", "zucchini pattypan", "pecorino", "pepino", "daun perilla", "acar",
  "kacang", "sage nanas", "merica pink", "plum kering", "paprika poblano", "purslane", "quince", "bawang liar",
  "rhubarb", "bawang putih panggang", "romanesco", "kacang", "daun rutabaga", "telur salmon", "ubi jalar", "asparagus laut",
  "ham", "sosis", "ramen", "lobak putih (daikon)", "chive hijau", "cumi", "midodok", "seledri Jepang", "batang talas", "pakis", "pasta udang asin",
  "ginseng", "kurma merah", "beras ketan", "tepung kentang", "jeroan sapi", "daun perilla", "sup", "sirup malt", "ikan monkfish",
  "boudin", "peperoncino", "baguette", "anggur putih", "saus steak", "sayuran muda", "dressing balsamic", "kacang-kacangan",
  "tepung jeon", "mackerel", "gurita kecil", "kol", "kaki ayam", "tepung almond", "gula halus", "pewarna makanan",
  "adonan croissant", "waffle maker", "kulit pie", "ekstrak vanila", "pasta kacang merah", "ragi", "biji-bijian", "madu", "pasta kacang merah",
  "sosis", "minyak", "baking powder"
];
