const flags = [
    { country: "Afghanistan", img: "https://flagcdn.com/af.svg" },
    { country: "Kepulauan Åland", img: "https://flagcdn.com/ax.svg" },
    { country: "Albania", img: "https://flagcdn.com/al.svg" },
    { country: "Aljazair", img: "https://flagcdn.com/dz.svg" },
    { country: "Samoa Amerika", img: "https://flagcdn.com/as.svg" },
    { country: "Andorra", img: "https://flagcdn.com/ad.svg" },
    { country: "Angola", img: "https://flagcdn.com/ao.svg" },
    { country: "Anguilla", img: "https://flagcdn.com/ai.svg" },
    { country: "Antartika", img: "https://flagcdn.com/aq.svg" },
    { country: "Antigua dan Barbuda", img: "https://flagcdn.com/ag.svg" },
    { country: "Argentina", img: "https://flagcdn.com/ar.svg" },
    { country: "Armenia", img: "https://flagcdn.com/am.svg" },
    { country: "Aruba", img: "https://flagcdn.com/aw.svg" },
    { country: "Australia", img: "https://flagcdn.com/au.svg" },
    { country: "Austria", img: "https://flagcdn.com/at.svg" },
    { country: "Azerbaijan", img: "https://flagcdn.com/az.svg" },
    { country: "Bahama", img: "https://flagcdn.com/bs.svg" },
    { country: "Bahrain", img: "https://flagcdn.com/bh.svg" },
    { country: "Bangladesh", img: "https://flagcdn.com/bd.svg" },
    { country: "Barbados", img: "https://flagcdn.com/bb.svg" },
    { country: "Belarus", img: "https://flagcdn.com/by.svg" },
    { country: "Belgia", img: "https://flagcdn.com/be.svg" },
    { country: "Belize", img: "https://flagcdn.com/bz.svg" },
    { country: "Benin", img: "https://flagcdn.com/bj.svg" },
    { country: "Bermuda", img: "https://flagcdn.com/bm.svg" },
    { country: "Bhutan", img: "https://flagcdn.com/bt.svg" },
    { country: "Bolivia", img: "https://flagcdn.com/bo.svg" },
    { country: "Kepulauan Karibia Belanda", img: "https://flagcdn.com/bq.svg" },
    { country: "Bosnia dan Herzegovina", img: "https://flagcdn.com/ba.svg" },
    { country: "Botswana", img: "https://flagcdn.com/bw.svg" },
    { country: "Pulau Bouvet", img: "https://flagcdn.com/bv.svg" },
    { country: "Brasil", img: "https://flagcdn.com/br.svg" },
    { country: "Wilayah Samudra Hindia Britania", img: "https://flagcdn.com/io.svg" },
    { country: "Kepulauan Virgin Britania Raya", img: "https://flagcdn.com/vg.svg" },
    { country: "Brunei", img: "https://flagcdn.com/bn.svg" },
    { country: "Bulgaria", img: "https://flagcdn.com/bg.svg" },
    { country: "Burkina Faso", img: "https://flagcdn.com/bf.svg" },
    { country: "Burundi", img: "https://flagcdn.com/bi.svg" },
    { country: "Tanjung Verde", img: "https://flagcdn.com/cv.svg" },
    { country: "Kamboja", img: "https://flagcdn.com/kh.svg" },
    { country: "Kamerun", img: "https://flagcdn.com/cm.svg" },
    { country: "Kanada", img: "https://flagcdn.com/ca.svg" },
    { country: "Kepulauan Cayman", img: "https://flagcdn.com/ky.svg" },
    { country: "Republik Afrika Tengah", img: "https://flagcdn.com/cf.svg" },
    { country: "Chad", img: "https://flagcdn.com/td.svg" },
    { country: "Chili", img: "https://flagcdn.com/cl.svg" },
    { country: "Tiongkok", img: "https://flagcdn.com/cn.svg" },
    { country: "Pulau Natal", img: "https://flagcdn.com/cx.svg" },
    { country: "Kepulauan Cocos (Keeling)", img: "https://flagcdn.com/cc.svg" },
    { country: "Kolombia", img: "https://flagcdn.com/co.svg" },
    { country: "Komoro", img: "https://flagcdn.com/km.svg" },
    { country: "Republik Demokratik Kongo", img: "https://flagcdn.com/cd.svg" },
    { country: "Republik Kongo", img: "https://flagcdn.com/cg.svg" },
    { country: "Kepulauan Cook", img: "https://flagcdn.com/ck.svg" },
    { country: "Kosta Rika", img: "https://flagcdn.com/cr.svg" },
    { country: "Pantai Gading", img: "https://flagcdn.com/ci.svg" },
    { country: "Kroasia", img: "https://flagcdn.com/hr.svg" },
    { country: "Kuba", img: "https://flagcdn.com/cu.svg" },
    { country: "Curaçao", img: "https://flagcdn.com/cw.svg" },
    { country: "Siprus", img: "https://flagcdn.com/cy.svg" },
    { country: "Republik Ceko", img: "https://flagcdn.com/cz.svg" },
    { country: "Denmark", img: "https://flagcdn.com/dk.svg" },
    { country: "Djibouti", img: "https://flagcdn.com/dj.svg" },
    { country: "Dominika", img: "https://flagcdn.com/dm.svg" },
    { country: "Republik Dominika", img: "https://flagcdn.com/do.svg" },
    { country: "Ekuador", img: "https://flagcdn.com/ec.svg" },
    { country: "Mesir", img: "https://flagcdn.com/eg.svg" },
    { country: "El Salvador", img: "https://flagcdn.com/sv.svg" },
    { country: "Guinea Ekuatorial", img: "https://flagcdn.com/gq.svg" },
    { country: "Eritrea", img: "https://flagcdn.com/er.svg" },
    { country: "Estonia", img: "https://flagcdn.com/ee.svg" },
    { country: "Eswatini", img: "https://flagcdn.com/sz.svg" },
    { country: "Ethiopia", img: "https://flagcdn.com/et.svg" },
    { country: "Kepulauan Falkland", img: "https://flagcdn.com/fk.svg" },
    { country: "Kepulauan Faroe", img: "https://flagcdn.com/fo.svg" },
    { country: "Fiji", img: "https://flagcdn.com/fj.svg" },
    { country: "Finlandia", img: "https://flagcdn.com/fi.svg" },
    { country: "Prancis", img: "https://flagcdn.com/fr.svg" },
    { country: "Guyana Prancis", img: "https://flagcdn.com/gf.svg" },
    { country: "Polinesia Prancis", img: "https://flagcdn.com/pf.svg" },
    { country: "Teritori Selatan dan Antartika Prancis", img: "https://flagcdn.com/tf.svg" },
    { country: "Gabon", img: "https://flagcdn.com/ga.svg" },
    { country: "Gambia", img: "https://flagcdn.com/gm.svg" },
    { country: "Georgia", img: "https://flagcdn.com/ge.svg" },
    { country: "Jerman", img: "https://flagcdn.com/de.svg" },
    { country: "Ghana", img: "https://flagcdn.com/gh.svg" },
    { country: "Gibraltar", img: "https://flagcdn.com/gi.svg" },
    { country: "Yunani", img: "https://flagcdn.com/gr.svg" },
    { country: "Greenland", img: "https://flagcdn.com/gl.svg" },
    { country: "Grenada", img: "https://flagcdn.com/gd.svg" },
    { country: "Guadeloupe", img: "https://flagcdn.com/gp.svg" },
    { country: "Guam", img: "https://flagcdn.com/gu.svg" },
    { country: "Guatemala", img: "https://flagcdn.com/gt.svg" },
    { country: "Guernsey", img: "https://flagcdn.com/gg.svg" },
    { country: "Guinea", img: "https://flagcdn.com/gn.svg" },
    { country: "Guinea-Bissau", img: "https://flagcdn.com/gw.svg" },
    { country: "Guyana", img: "https://flagcdn.com/gy.svg" },
    { country: "Haiti", img: "https://flagcdn.com/ht.svg" },
    { country: "Kepulauan Heard dan McDonald", img: "https://flagcdn.com/hm.svg" },
    { country: "Vatikan", img: "https://flagcdn.com/va.svg" },
    { country: "Honduras", img: "https://flagcdn.com/hn.svg" },
    { country: "Hong Kong", img: "https://flagcdn.com/hk.svg" },
    { country: "Hungaria", img: "https://flagcdn.com/hu.svg" },
    { country: "Islandia", img: "https://flagcdn.com/is.svg" },
    { country: "India", img: "https://flagcdn.com/in.svg" },
    { country: "Indonesia", img: "https://flagcdn.com/id.svg" },
    { country: "Iran", img: "https://flagcdn.com/ir.svg" },
    { country: "Irak", img: "https://flagcdn.com/iq.svg" },
    { country: "Irlandia", img: "https://flagcdn.com/ie.svg" },
    { country: "Pulau Man", img: "https://flagcdn.com/im.svg" },
    { country: "Israel", img: "https://flagcdn.com/il.svg" },
    { country: "Italia", img: "https://flagcdn.com/it.svg" },
    { country: "Jamaika", img: "https://flagcdn.com/jm.svg" },
    { country: "Jepang", img: "https://flagcdn.com/jp.svg" },
    { country: "Jersey", img: "https://flagcdn.com/je.svg" },
    { country: "Yordania", img: "https://flagcdn.com/jo.svg" },
    { country: "Kazakhstan", img: "https://flagcdn.com/kz.svg" },
    { country: "Kenya", img: "https://flagcdn.com/ke.svg" },
    { country: "Kiribati", img: "https://flagcdn.com/ki.svg" },
    { country: "Korea Utara", img: "https://flagcdn.com/kp.svg" },
    { country: "Korea Selatan", img: "https://flagcdn.com/kr.svg" },
    { country: "Kuwait", img: "https://flagcdn.com/kw.svg" },
    { country: "Kirgizstan", img: "https://flagcdn.com/kg.svg" },
    { country: "Laos", img: "https://flagcdn.com/la.svg" },
    { country: "Latvia", img: "https://flagcdn.com/lv.svg" },
    { country: "Lebanon", img: "https://flagcdn.com/lb.svg" },
    { country: "Lesotho", img: "https://flagcdn.com/ls.svg" },
    { country: "Liberia", img: "https://flagcdn.com/lr.svg" },
    { country: "Libya", img: "https://flagcdn.com/ly.svg" },
    { country: "Liechtenstein", img: "https://flagcdn.com/li.svg" },
    { country: "Lituania", img: "https://flagcdn.com/lt.svg" },
    { country: "Luksemburg", img: "https://flagcdn.com/lu.svg" },
    { country: "Makau", img: "https://flagcdn.com/mo.svg" },
    { country: "Madagaskar", img: "https://flagcdn.com/mg.svg" },
    { country: "Malawi", img: "https://flagcdn.com/mw.svg" },
    { country: "Malaysia", img: "https://flagcdn.com/my.svg" },
    { country: "Maladewa", img: "https://flagcdn.com/mv.svg" },
    { country: "Mali", img: "https://flagcdn.com/ml.svg" },
    { country: "Malta", img: "https://flagcdn.com/mt.svg" },
    { country: "Kepulauan Marshall", img: "https://flagcdn.com/mh.svg" },
    { country: "Martinik", img: "https://flagcdn.com/mq.svg" },
    { country: "Mauritania", img: "https://flagcdn.com/mr.svg" },
    { country: "Mauritius", img: "https://flagcdn.com/mu.svg" },
    { country: "Mayotte", img: "https://flagcdn.com/yt.svg" },
    { country: "Meksiko", img: "https://flagcdn.com/mx.svg" },
    { country: "Mikronesia", img: "https://flagcdn.com/fm.svg" },
    { country: "Moldova", img: "https://flagcdn.com/md.svg" },
    { country: "Monako", img: "https://flagcdn.com/mc.svg" },
    { country: "Mongolia", img: "https://flagcdn.com/mn.svg" },
    { country: "Montenegro", img: "https://flagcdn.com/me.svg" },
    { country: "Montserrat", img: "https://flagcdn.com/ms.svg" },
    { country: "Maroko", img: "https://flagcdn.com/ma.svg" },
    { country: "Mozambik", img: "https://flagcdn.com/mz.svg" },
    { country: "Myanmar", img: "https://flagcdn.com/mm.svg" },
    { country: "Namibia", img: "https://flagcdn.com/na.svg" },
    { country: "Nauru", img: "https://flagcdn.com/nr.svg" },
    { country: "Nepal", img: "https://flagcdn.com/np.svg" },
    { country: "Belanda", img: "https://flagcdn.com/nl.svg" },
    { country: "Kaledonia Baru", img: "https://flagcdn.com/nc.svg" },
    { country: "Selandia Baru", img: "https://flagcdn.com/nz.svg" },
    { country: "Nikaragua", img: "https://flagcdn.com/ni.svg" },
    { country: "Niger", img: "https://flagcdn.com/ne.svg" },
    { country: "Nigeria", img: "https://flagcdn.com/ng.svg" },
    { country: "Niue", img: "https://flagcdn.com/nu.svg" },
    { country: "Pulau Norfolk", img: "https://flagcdn.com/nf.svg" },
    { country: "Kepulauan Mariana Utara", img: "https://flagcdn.com/mp.svg" },
    { country: "Norwegia", img: "https://flagcdn.com/no.svg" },
    { country: "Oman", img: "https://flagcdn.com/om.svg" },
    { country: "Pakistan", img: "https://flagcdn.com/pk.svg" },
    { country: "Palau", img: "https://flagcdn.com/pw.svg" },
    { country: "Palestina", img: "https://flagcdn.com/ps.svg" },
    { country: "Panama", img: "https://flagcdn.com/pa.svg" },
    { country: "Papua Nugini", img: "https://flagcdn.com/pg.svg" },
    { country: "Paraguay", img: "https://flagcdn.com/py.svg" },
    { country: "Peru", img: "https://flagcdn.com/pe.svg" },
    { country: "Filipina", img: "https://flagcdn.com/ph.svg" },
    { country: "Pitcairn", img: "https://flagcdn.com/pn.svg" },
    { country: "Polandia", img: "https://flagcdn.com/pl.svg" },
    { country: "Portugal", img: "https://flagcdn.com/pt.svg" },
    { country: "Puerto Riko", img: "https://flagcdn.com/pr.svg" },
    { country: "Qatar", img: "https://flagcdn.com/qa.svg" },
    { country: "Reunion", img: "https://flagcdn.com/re.svg" },
    { country: "Rumania", img: "https://flagcdn.com/ro.svg" },
    { country: "Rusia", img: "https://flagcdn.com/ru.svg" },
    { country: "Rwanda", img: "https://flagcdn.com/rw.svg" },
    { country: "Saint Barthelemy", img: "https://flagcdn.com/bl.svg" },
    { country: "Saint Helena", img: "https://flagcdn.com/sh.svg" },
    { country: "Saint Kitts dan Nevis", img: "https://flagcdn.com/kn.svg" },
    { country: "Saint Lucia", img: "https://flagcdn.com/lc.svg" },
    { country: "Saint Martin", img: "https://flagcdn.com/mf.svg" },
    { country: "Saint Pierre dan Miquelon", img: "https://flagcdn.com/pm.svg" },
    { country: "Saint Vincent dan Grenadines", img: "https://flagcdn.com/vc.svg" },
    { country: "Samoa", img: "https://flagcdn.com/ws.svg" },
    { country: "San Marino", img: "https://flagcdn.com/sm.svg" },
    { country: "Sao Tome dan Principe", img: "https://flagcdn.com/st.svg" },
    { country: "Arab Saudi", img: "https://flagcdn.com/sa.svg" },
    { country: "Senegal", img: "https://flagcdn.com/sn.svg" },
    { country: "Serbia", img: "https://flagcdn.com/rs.svg" },
    { country: "Seychelles", img: "https://flagcdn.com/sc.svg" },
    { country: "Sierra Leone", img: "https://flagcdn.com/sl.svg" },
    { country: "Singapura", img: "https://flagcdn.com/sg.svg" },
    { country: "Sint Maarten", img: "https://flagcdn.com/sx.svg" },
    { country: "Slovakia", img: "https://flagcdn.com/sk.svg" },
    { country: "Slovenia", img: "https://flagcdn.com/si.svg" },
    { country: "Kepulauan Solomon", img: "https://flagcdn.com/sb.svg" },
    { country: "Somalia", img: "https://flagcdn.com/so.svg" },
    { country: "Afrika Selatan", img: "https://flagcdn.com/za.svg" },
    { country: "Georgia Selatan & Sandwich Selatan", img: "https://flagcdn.com/gs.svg" },
    { country: "Sudan Selatan", img: "https://flagcdn.com/ss.svg" },
    { country: "Spanyol", img: "https://flagcdn.com/es.svg" },
    { country: "Sri Lanka", img: "https://flagcdn.com/lk.svg" },
    { country: "Sudan", img: "https://flagcdn.com/sd.svg" },
    { country: "Suriname", img: "https://flagcdn.com/sr.svg" },
    { country: "Svalbard dan Jan Mayen", img: "https://flagcdn.com/sj.svg" },
    { country: "Swedia", img: "https://flagcdn.com/se.svg" },
    { country: "Swiss", img: "https://flagcdn.com/ch.svg" },
    { country: "Suriah", img: "https://flagcdn.com/sy.svg" },
    { country: "Taiwan", img: "https://flagcdn.com/tw.svg" },
    { country: "Tajikistan", img: "https://flagcdn.com/tj.svg" },
    { country: "Tanzania", img: "https://flagcdn.com/tz.svg" },
    { country: "Thailand", img: "https://flagcdn.com/th.svg" },
    { country: "Timor Leste", img: "https://flagcdn.com/tl.svg" },
    { country: "Togo", img: "https://flagcdn.com/tg.svg" },
    { country: "Tokelau", img: "https://flagcdn.com/tk.svg" },
    { country: "Tonga", img: "https://flagcdn.com/to.svg" },
    { country: "Trinidad dan Tobago", img: "https://flagcdn.com/tt.svg" },
    { country: "Tunisia", img: "https://flagcdn.com/tn.svg" },
    { country: "Turki", img: "https://flagcdn.com/tr.svg" },
    { country: "Turkmenistan", img: "https://flagcdn.com/tm.svg" },
    { country: "Kepulauan Turks dan Caicos", img: "https://flagcdn.com/tc.svg" },
    { country: "Tuvalu", img: "https://flagcdn.com/tv.svg" },
    { country: "Uganda", img: "https://flagcdn.com/ug.svg" },
    { country: "Ukraina", img: "https://flagcdn.com/ua.svg" },
    { country: "Uni Emirat Arab", img: "https://flagcdn.com/ae.svg" },
    { country: "Britania Raya", img: "https://flagcdn.com/gb.svg" },
    { country: "Amerika Serikat", img: "https://flagcdn.com/us.svg" },
    { country: "Pulau-Pulau Terluar Kecil Amerika Serikat", img: "https://flagcdn.com/um.svg" },
    { country: "Uruguay", img: "https://flagcdn.com/uy.svg" },
    { country: "Uzbekistan", img: "https://flagcdn.com/uz.svg" },
    { country: "Vanuatu", img: "https://flagcdn.com/vu.svg" },
    { country: "Venezuela", img: "https://flagcdn.com/ve.svg" },
    { country: "Vietnam", img: "https://flagcdn.com/vn.svg" },
    { country: "Wallis dan Futuna", img: "https://flagcdn.com/wf.svg" },
    { country: "Sahara Barat", img: "https://flagcdn.com/eh.svg" },
    { country: "Yaman", img: "https://flagcdn.com/ye.svg" },
    { country: "Zambia", img: "https://flagcdn.com/zm.svg" },
    { country: "Zimbabwe", img: "https://flagcdn.com/zw.svg" },
    { country: "Kosovo", img: "https://flagcdn.com/xk.svg" }
];
