window.RECIPES_DB = [
  { name: "Jjigae de Kimchi", ingredients: ["kimchi", "cerdo", "tofu", "cebolla", "cebolleta", "ajo", "guindilla en polvo", "gochujang", "salsa de soja"] },
  { name: "Bibimbap", ingredients: ["arroz", "ternera", "espinaca", "brotes de soja", "zanahoria", "calabacín", "huevo", "gochujang", "alga nori"] },
  { name: "Bulgogi", ingredients: ["ternera", "salsa de soja", "cebolla", "pera", "azúcar", "aceite de sésamo", "ajo", "cebolleta", "pimienta"] },
  { name: "Japchae", ingredients: ["fideos de batata", "ternera", "espinaca", "zanahoria", "cebolla", "setas", "huevo", "salsa de soja", "aceite de sésamo"] },
  { name: "Tteokbokki", ingredients: ["pastel de arroz", "odeng", "cebolla", "cebolleta", "gochujang", "azúcar", "salsa de soja", "ajo", "huevo cocido"] },
  { name: "Sundubu Jjigae", ingredients: ["tofu suave", "cerdo", "huevo", "calabacín", "cebolla", "cebolleta", "ajo", "guindilla en polvo", "salsa de soja"] },
  { name: "Samgyeopsal", ingredients: ["panceta de cerdo", "lechuga", "ajo", "ssamjang", "cebolleta", "sal", "pimienta"] },
  { name: "Arroz frito con kimchi", ingredients: ["kimchi", "arroz", "huevo", "cerdo", "cebolleta", "salsa de soja", "aceite de sésamo"] },
  { name: "Galbijjim", ingredients: ["costilla de ternera", "cebolla", "zanahoria", "patata", "salsa de soja", "azúcar", "pera", "ajo", "aceite de sésamo"] },
  { name: "Jajangmyeon", ingredients: ["fideos", "cerdo", "cebolla", "calabacín", "patata", "chunjang", "pepino", "huevo"] },
  { name: "Sushi", ingredients: ["arroz", "vinagre", "azúcar", "sal", "alga nori", "salmón", "atún", "gamba", "aguacate", "pepino"] },
  { name: "Ramen", ingredients: ["fideos", "cerdo", "huevo", "cebolleta", "menma", "alga nori", "salsa de soja", "miso", "ajo"] },
  { name: "Katsudon", ingredients: ["arroz", "tonkatsu", "huevo", "cebolla", "salsa de soja", "azúcar", "mirin"] },
  { name: "Okonomiyaki", ingredients: ["harina de trigo", "huevo", "col", "cerdo", "gamba", "cebolleta", "mayonesa", "salsa okonomiyaki"] },
  { name: "Mapo tofu", ingredients: ["tofu", "carne picada de cerdo", "cebolleta", "ajo", "jengibre", "salsa de soja", "doubanjiang", "pimienta de Sichuan"] },
  { name: "Pato Pekín", ingredients: ["pato", "pepino", "cebolleta", "tianmianjiang", "crepes finos"] },
  { name: "Cerdo agridulce", ingredients: ["cerdo", "piña", "pimiento", "cebolla", "vinagre", "azúcar", "kétchup", "salsa de soja"] },
  { name: "Pad Thai", ingredients: ["fideos de arroz", "gamba", "huevo", "tofu", "brotes de soja", "cacahuetes", "tamarindo", "salsa de pescado", "lima"] },
  { name: "Tom Yum Kung", ingredients: ["gamba", "hierba limón", "lima", "galanga", "setas", "guindilla", "salsa de pescado", "cilantro"] },
  { name: "Pho", ingredients: ["fideos de arroz", "ternera", "cebolla", "jengibre", "canela", "clavo", "salsa de pescado", "brotes de soja", "lima", "albahaca"] },
  { name: "Arroz con pollo Hainan", ingredients: ["pollo", "arroz", "jengibre", "ajo", "pepino", "salsa de soja", "salsa de chile"] },
  { name: "Rollitos de primavera frescos", ingredients: ["papel de arroz", "gamba", "cerdo", "lechuga", "fideos de arroz", "menta", "cilantro"] },
  { name: "Curry verde", ingredients: ["pollo", "pasta de curry verde", "leche de coco", "berenjena", "albahaca", "salsa de pescado", "azúcar"] },
  { name: "Nasi Goreng", ingredients: ["arroz", "pollo", "huevo", "salsa de soja", "gamba", "cebolleta", "guindilla"] },
  { name: "Satay", ingredients: ["pollo", "cacahuetes", "salsa de soja", "hierba limón", "ajo", "cúrcuma"] },
  { name: "Laksa", ingredients: ["fideos de arroz", "gamba", "leche de coco", "tofu", "brotes de soja", "huevo", "guindilla", "cilantro"] },
  { name: "Chow Mein", ingredients: ["fideos", "pollo", "brotes de soja", "col", "zanahoria", "salsa de soja", "cebolleta"] },
  { name: "Arroz frito", ingredients: ["arroz", "huevo", "zanahoria", "guisantes", "cebolleta", "gamba", "salsa de soja"] },
  { name: "Gyoza", ingredients: ["harina de trigo", "col", "cerdo", "ajo", "jengibre", "cebolleta", "salsa de soja"] },
  { name: "Unadon", ingredients: ["arroz", "anguila", "salsa de soja", "mirin", "azúcar", "huevo"] },
  { name: "Hamburguesa", ingredients: ["ternera", "pan", "lechuga", "tomate", "cebolla", "queso", "pepinillos"] },
  { name: "Hamburguesa con queso", ingredients: ["ternera", "pan", "queso", "lechuga", "tomate", "cebolla", "pepinillos"] },
  { name: "Pollo frito", ingredients: ["pollo", "harina de trigo", "huevo", "aceite", "sal", "pimienta"] },
  { name: "Costillas BBQ", ingredients: ["costillas de cerdo", "salsa BBQ", "azúcar moreno", "sal", "pimienta", "ajo en polvo"] },
  { name: "Ensalada César", ingredients: ["lechuga", "queso parmesano", "picatostes", "anchoa", "huevo", "salsa César"] },
  { name: "Sándwich BLT", ingredients: ["pan", "bacon", "lechuga", "tomate", "mayonesa"] },
  { name: "Espaguetis a la carbonara", ingredients: ["espaguetis", "huevo", "queso parmesano", "panceta", "pimienta"] },
  { name: "Lasaña", ingredients: ["láminas de lasaña", "carne picada de ternera", "salsa de tomate", "queso ricotta", "mozzarella", "queso parmesano", "huevo"] },
  { name: "Pizza Margarita", ingredients: ["masa de pizza", "salsa de tomate", "mozzarella", "albahaca", "aceite de oliva"] },
  { name: "Paella", ingredients: ["arroz", "gamba", "mejillones", "pollo", "chorizo", "guisantes", "azafrán", "pimentón", "pimiento"] },
  { name: "Croque Monsieur", ingredients: ["pan", "jamón", "queso", "mantequilla", "leche", "harina de trigo", "mostaza"] },
  { name: "Quiche Lorraine", ingredients: ["masa de tarta", "huevo", "bacon", "queso", "nata", "cebolla"] },
  { name: "Ratatouille", ingredients: ["berenjena", "calabacín", "pimiento", "tomate", "cebolla", "ajo"] },
  { name: "Bouillabaisse", ingredients: ["pescado", "mejillones", "gamba", "tomate", "ajo", "cebolla", "hinojo", "azafrán"] },
  { name: "Crêpe", ingredients: ["harina de trigo", "huevo", "leche", "mantequilla", "azúcar", "sal"] },
  { name: "Tortilla española", ingredients: ["huevo", "patata", "cebolla", "aceite de oliva", "sal"] },
  { name: "Gazpacho", ingredients: ["tomate", "pepino", "pimiento", "cebolla", "ajo", "aceite de oliva", "vinagre"] },
  { name: "Patatas bravas", ingredients: ["patata", "aceite de oliva", "pimentón", "tomate", "salsa alioli"] },
  { name: "Churros", ingredients: ["harina de trigo", "huevo", "mantequilla", "azúcar", "sal", "aceite", "canela"] },
  { name: "Ensalada Niçoise con atún", ingredients: ["lechuga", "atún", "huevo", "patata", "judía verde", "aceituna", "tomate", "anchoa"] },
  { name: "Tacos", ingredients: ["tortilla", "ternera", "lechuga", "tomate", "queso", "cebolla", "crema agria", "guacamole"] },
  { name: "Enchilada", ingredients: ["tortilla", "pollo", "queso", "cebolla", "salsa enchilada", "crema agria"] },
  { name: "Burrito", ingredients: ["tortilla", "arroz", "frijoles", "ternera", "lechuga", "queso", "salsa"] },
  { name: "Ceviche", ingredients: ["pescado", "lima", "cebolla", "guindilla", "cilantro", "tomate"] },
  { name: "Feijoada", ingredients: ["frijoles negros", "cerdo", "ternera", "salchicha", "arroz", "cebolla", "ajo"] },
  { name: "Empanada", ingredients: ["harina de trigo", "ternera", "cebolla", "huevo", "aceituna", "pasas", "pimentón"] },
  { name: "Musaka", ingredients: ["berenjena", "patata", "carne picada de ternera", "tomate", "cebolla", "salsa bechamel"] },
  { name: "Ensalada griega", ingredients: ["tomate", "pepino", "aceituna", "queso feta", "cebolla", "aceite de oliva"] },
  { name: "Shakshuka", ingredients: ["huevo", "tomate", "pimiento", "cebolla", "ajo", "comino", "pimentón"] },
  { name: "Falafel", ingredients: ["garbanzo", "cebolla", "ajo", "perejil", "cilantro", "comino", "harina de trigo"] },
  { name: "Hummus", ingredients: ["garbanzo", "tahini", "ajo", "limón", "aceite de oliva"] },
  { name: "Shawarma", ingredients: ["pollo", "ternera", "pan pita", "lechuga", "tomate", "cebolla", "yogur", "ajo"] },
  { name: "Cuscús", ingredients: ["cuscús", "pollo", "zanahoria", "calabacín", "garbanzo", "cebolla"] },
  { name: "Tajín", ingredients: ["cordero", "albaricoque", "almendra", "cebolla", "canela", "cilantro", "azafrán"] },
  { name: "Pollo a la mantequilla", ingredients: ["pollo", "mantequilla", "nata", "tomate", "cebolla", "garam masala"] },
  { name: "Pollo tandoori", ingredients: ["pollo", "yogur", "garam masala", "comino", "ajo", "jengibre", "guindilla"] },
  { name: "Palak paneer", ingredients: ["espinaca", "paneer", "nata", "cebolla", "tomate", "ajo", "comino"] },
  { name: "Dal Tadka", ingredients: ["lentejas", "cebolla", "tomate", "ajo", "jengibre", "comino", "cúrcuma", "ghee"] },
  { name: "Biryani", ingredients: ["arroz", "pollo", "yogur", "cebolla", "garam masala", "azafrán"] },
  { name: "Samosa", ingredients: ["harina de trigo", "patata", "guisantes", "cebolla", "comino", "cilantro"] },
  { name: "Fettuccine Alfredo", ingredients: ["fettuccine", "mantequilla", "nata", "queso parmesano"] },
  { name: "Pollo a la parmesana", ingredients: ["pollo", "huevo", "pan rallado", "queso parmesano", "mozzarella", "salsa de tomate"] },
  { name: "Stroganoff de ternera", ingredients: ["ternera", "cebolla", "setas", "crema agria", "mantequilla", "harina de trigo"] },
  { name: "Huevos benedictinos", ingredients: ["huevo", "muffin inglés", "jamón", "salsa holandesa", "mantequilla"] },
  { name: "Bisque de langosta", ingredients: ["langosta", "nata", "mantequilla", "cebolla", "apio", "zanahoria", "coñac"] },
  { name: "Clam chowder", ingredients: ["almeja", "patata", "cebolla", "apio", "bacon", "nata", "mantequilla"] },
  { name: "Pastel de pollo", ingredients: ["pollo", "zanahoria", "patata", "guisantes", "cebolla", "masa de tarta", "nata"] },
  { name: "Pastel de carne", ingredients: ["ternera", "huevo", "pan rallado", "cebolla", "kétchup", "mostaza"] },
  { name: "Tostada francesa", ingredients: ["pan", "huevo", "leche", "canela", "azúcar", "mantequilla"] },
  { name: "Panqueques", ingredients: ["harina de trigo", "huevo", "leche", "levadura en polvo", "azúcar", "mantequilla"] },
  { name: "Gofres", ingredients: ["harina de trigo", "huevo", "leche", "levadura en polvo", "azúcar", "mantequilla"] },
  { name: "Pan de plátano", ingredients: ["plátano", "harina de trigo", "huevo", "azúcar", "mantequilla"] },
  { name: "Tarta de manzana", ingredients: ["manzana", "harina de trigo", "huevo", "azúcar", "mantequilla", "canela"] },
  { name: "Tarta de limón", ingredients: ["limón", "huevo", "azúcar", "mantequilla", "harina de trigo"] },
  { name: "Brownie", ingredients: ["chocolate", "harina de trigo", "huevo", "azúcar", "mantequilla"] },
  { name: "Tarta de queso", ingredients: ["queso crema", "huevo", "azúcar", "mantequilla", "galleta graham"] },
  { name: "Sopa de calabaza", ingredients: ["calabaza", "cebolla", "ajo", "nata", "mantequilla"] },
  { name: "Minestrone", ingredients: ["alubias", "zanahoria", "apio", "cebolla", "tomate", "pasta"] },
  { name: "Tortilla francesa", ingredients: ["huevo", "leche", "queso", "jamón", "cebolla", "pimiento"] },
  { name: "Huevos revueltos", ingredients: ["huevo", "leche", "mantequilla", "sal", "pimienta"] },
  { name: "Quesadilla", ingredients: ["tortilla", "queso", "pollo", "pimiento", "cebolla"] },
  { name: "Fajita", ingredients: ["ternera", "cebolla", "pimiento", "tortilla", "crema agria"] },
  { name: "Cerdo desmenuzado", ingredients: ["cerdo", "salsa BBQ", "azúcar moreno", "cebolla", "pan"] },
  { name: "Fish and chips", ingredients: ["pescado", "patata", "harina de trigo", "huevo", "aceite"] },
  { name: "Pastel de pastor", ingredients: ["carne picada de cordero", "patata", "zanahoria", "cebolla", "guisantes", "salsa gravy"] },
  { name: "Filete", ingredients: ["ternera", "sal", "pimienta", "mantequilla", "ajo"] },
  { name: "Chuleta de cordero", ingredients: ["cordero", "sal", "pimienta", "ajo", "romero"] },
  { name: "Pollo asado", ingredients: ["pollo", "sal", "pimienta", "ajo", "tomillo", "aceite de oliva"] },
  { name: "Pollo al curry", ingredients: ["pollo", "cebolla", "tomate", "ajo", "jengibre", "curry en polvo", "leche de coco"] },
  { name: "Gambas al ajillo", ingredients: ["gamba", "ajo", "mantequilla", "limón", "perejil", "espaguetis"] },
  { name: "Paella de mariscos", ingredients: ["arroz", "gamba", "mejillones", "calamar", "guisantes", "azafrán"] },
  { name: "Cacciatore", ingredients: ["pollo", "tomate", "cebolla", "pimiento", "setas", "ajo"] },
  { name: "Boeuf Bourguignon", ingredients: ["ternera", "vino tinto", "cebolla", "zanahoria", "apio", "ajo", "tomillo"] },
  { name: "Goulash", ingredients: ["ternera", "cebolla", "pimentón", "tomate", "pimiento", "ajo"] },
  { name: "Borscht", ingredients: ["remolacha", "col", "patata", "zanahoria", "cebolla", "eneldo"] },
  { name: "Pierogi", ingredients: ["harina de trigo", "huevo", "patata", "queso", "cebolla", "mantequilla"] },
  { name: "Baklava", ingredients: ["masa filo", "nuez", "pistacho", "azúcar", "mantequilla", "miel"] },
  { name: "Dolma", ingredients: ["hoja de parra", "arroz", "cebolla", "piñón", "eneldo"] },
  { name: "Rollos de col", ingredients: ["col", "ternera", "arroz", "cebolla", "salsa de tomate"] },
  { name: "Estofado irlandés", ingredients: ["cordero", "patata", "zanahoria", "cebolla", "apio"] },
  { name: "Cassoulet", ingredients: ["alubias blancas", "cerdo", "pato", "salchicha", "cebolla", "ajo"] },
  { name: "Börek", ingredients: ["masa filo", "queso", "patata", "huevo", "sésamo"] },
  { name: "Sauerbraten", ingredients: ["ternera", "cebolla", "zanahoria", "apio", "vinagre", "jengibre"] },
  { name: "Wiener Schnitzel", ingredients: ["ternera", "huevo", "harina de trigo", "pan rallado", "limón"] },
  { name: "Zwiebelrostbraten", ingredients: ["ternera", "cebolla", "mantequilla", "harina de trigo", "caldo de ternera"] },
  { name: "Rösti", ingredients: ["patata", "mantequilla", "cebolla", "bacon"] },
  { name: "Spätzle", ingredients: ["harina de trigo", "huevo", "leche", "mantequilla"] },
  { name: "Sopa goulash", ingredients: ["ternera", "cebolla", "pimentón", "patata", "zanahoria"] },
  { name: "Pollo Kiev", ingredients: ["pollo", "mantequilla", "ajo", "perejil", "huevo", "harina de trigo", "pan rallado"] },
  { name: "Plov", ingredients: ["arroz", "ternera", "zanahoria", "cebolla", "comino"] },
  { name: "Manti", ingredients: ["harina de trigo", "huevo", "ternera", "cebolla", "yogur"] },
  { name: "Fideos estilo Pekín", ingredients: ["fideos", "cerdo", "huevo", "cebolleta", "salsa de soja"] },
  { name: "Jollof rice", ingredients: ["arroz", "tomate", "cebolla", "pimiento", "guindilla", "ajo"] },
  { name: "Bobotie", ingredients: ["ternera", "pan", "huevo", "cebolla", "leche", "curry en polvo"] },
  { name: "Bunny Chow", ingredients: ["pan", "pollo", "cebolla", "tomate", "curry en polvo"] },
  { name: "Chakalaka", ingredients: ["alubias", "cebolla", "tomate", "guindilla", "zanahoria", "pimiento"] },
  { name: "Pav Bhaji", ingredients: ["pan", "patata", "guisantes", "zanahoria", "cebolla", "tomate", "mantequilla"] },
  { name: "Vada Pav", ingredients: ["pan", "patata", "guindilla", "cilantro", "ajo", "semilla de mostaza"] },
  { name: "Masala Dosa", ingredients: ["arroz", "lentejas", "patata", "cebolla", "semilla de mostaza", "hoja de curry"] },
  { name: "Idli", ingredients: ["arroz", "lentejas", "sal"] },
  { name: "Sambar", ingredients: ["lentejas", "zanahoria", "cebolla", "tomate", "berenjena", "drumstick", "mezcla de especias"] },
  { name: "Katsu curry", ingredients: ["arroz", "tonkatsu", "salsa de curry", "cebolla", "zanahoria", "patata"] },
  { name: "Takoyaki", ingredients: ["harina de trigo", "huevo", "pulpo", "cebolleta", "tenkasu", "mayonesa", "salsa takoyaki"] },
  { name: "Sukiyaki", ingredients: ["ternera", "tofu", "cebolleta", "shiitake", "shirataki", "huevo"] },
  { name: "Nabe", ingredients: ["col", "tofu", "shiitake", "zanahoria", "pollo", "udon"] },
  { name: "Sopa de huevo", ingredients: ["huevo", "caldo de pollo", "fécula de patata", "cebolleta", "salsa de soja"] },
  { name: "Sopa agripicante", ingredients: ["tofu", "huevo", "setas", "menma", "vinagre", "salsa de soja", "pimienta"] },
  { name: "Salteado de ternera y brócoli", ingredients: ["ternera", "brócoli", "salsa de soja", "ajo", "jengibre", "cebolla"] },
  { name: "Pollo al limón", ingredients: ["pollo", "limón", "huevo", "harina de trigo", "salsa de soja", "azúcar"] },
  { name: "Arroz frito con piña", ingredients: ["arroz", "piña", "gamba", "huevo", "anacardo", "cebolleta"] },
  { name: "Bánh mì", ingredients: ["baguette", "cerdo", "zanahoria", "pepino", "cilantro", "mayonesa", "paté"] },
  { name: "Khao Soi", ingredients: ["fideos de huevo", "pollo", "leche de coco", "pasta de curry", "encurtidos"] },
  { name: "Bak Kut Teh", ingredients: ["costillas de cerdo", "ajo", "salsa de soja", "pimienta blanca", "setas"] },
  { name: "Laksa de Singapur", ingredients: ["fideos de arroz", "gamba", "leche de coco", "tofu", "brotes de soja", "huevo", "guindilla", "cilantro"] },
  { name: "Gado-gado", ingredients: ["verduras", "tofu", "huevo", "salsa de cacahuete", "brotes de soja"] },
  { name: "Nasi Lemak", ingredients: ["arroz", "leche de coco", "huevo", "ikan bilis", "cacahuetes", "pepino", "salsa sambal"] },
  { name: "Pasta con pesto de rúcula", ingredients: ["rúcula", "pasta", "queso parmesano", "aceite de oliva", "piñón"] },
  { name: "Shakshuka con queso feta", ingredients: ["huevo", "tomate", "pimiento", "cebolla", "queso feta", "cilantro"] },
  { name: "Panqueques de buttermilk", ingredients: ["harina de trigo", "huevo", "buttermilk", "azúcar", "levadura en polvo"] },
  { name: "Ensalada de quinoa", ingredients: ["quinoa", "pepino", "tomate", "queso feta", "limón", "aceite de oliva"] },
  { name: "Ensalada César de kale", ingredients: ["kale", "queso parmesano", "picatostes", "anchoa", "huevo", "salsa César"] },
  { name: "Buddha bowl vegano", ingredients: ["arroz integral", "garbanzo", "aguacate", "espinaca", "zanahoria", "tofu"] },
  { name: "Berenjena a la parmesana", ingredients: ["berenjena", "salsa de tomate", "mozzarella", "queso parmesano", "albahaca"] },
  { name: "Pimientos rellenos", ingredients: ["pimiento", "arroz", "carne picada de ternera", "cebolla", "tomate", "queso"] },
  { name: "Chuleta de cordero asada", ingredients: ["cordero", "ajo", "romero", "aceite de oliva", "sal", "pimienta"] },
  { name: "Sopa de lentejas", ingredients: ["lentejas", "zanahoria", "apio", "cebolla", "tomate", "ajo"] },
  { name: "Coles de Bruselas asadas", ingredients: ["coles de Bruselas", "aceite de oliva", "sal", "pimienta", "limón"] },
  { name: "Pollo al pesto", ingredients: ["pollo", "pesto de albahaca", "queso parmesano", "aceite de oliva"] },
  { name: "Salsa de mango", ingredients: ["mango", "cebolla", "lima", "cilantro", "guindilla"] },
  { name: "Bacalao asado", ingredients: ["bacalao", "limón", "aceite de oliva", "perejil", "pan rallado"] },
  { name: "Coleslaw asiático", ingredients: ["col china", "zanahoria", "cebolleta", "salsa de soja", "vinagre de arroz", "aceite de sésamo"] },
  { name: "Ensalada de fideos con cacahuete", ingredients: ["fideos", "cacahuete", "zanahoria", "pepino", "salsa de soja", "aceite de sésamo"] },
  { name: "Chili vegano", ingredients: ["frijoles negros", "tomate", "cebolla", "chile en polvo", "maíz", "pimiento"] },
  { name: "Tacos de jackfruit", ingredients: ["jackfruit", "tortilla", "col", "lima", "aguacate", "cilantro"] },
  { name: "Salteado de tofu y verduras", ingredients: ["tofu", "brócoli", "pimiento", "salsa de soja", "jengibre", "ajo"] },
  { name: "Risotto de calabaza", ingredients: ["calabaza", "arroz", "queso parmesano", "cebolla", "ajo"] },
  { name: "Tostada de ratatouille", ingredients: ["berenjena", "calabacín", "pimiento", "cebolla", "pan"] },
  { name: "Ensalada de remolacha", ingredients: ["remolacha", "rúcula", "nuez", "queso de cabra", "balsámico"] },
  { name: "Tajín marroquí", ingredients: ["cordero", "albaricoque", "almendra", "cebolla", "canela", "cilantro", "azafrán"] },
  { name: "Filete con chimichurri", ingredients: ["ternera", "perejil", "ajo", "aceite de oliva", "orégano", "vinagre"] },
  { name: "Buñuelos de calabacín", ingredients: ["calabacín", "huevo", "harina de trigo", "queso parmesano", "cebolleta"] },
  { name: "Sopa de miso", ingredients: ["miso", "tofu", "wakame", "cebolleta", "caldo dashi"] },
  { name: "Wrap de falafel", ingredients: ["falafel", "pan pita", "lechuga", "tomate", "tahini"] },
  { name: "Laksa con gambas", ingredients: ["gamba", "fideos de arroz", "leche de coco", "pasta de laksa", "huevo", "brotes de soja"] },
  { name: "Bowl de cuscús", ingredients: ["cuscús", "garbanzo", "zanahoria", "calabacín", "limón"] },
  { name: "Pollo frito coreano dulce", ingredients: ["pollo", "gochujang", "salsa de soja", "azúcar", "jarabe de maíz", "ajo", "jengibre", "mezcla para rebozar"] },
  { name: "Budae Jjigae", ingredients: ["jamón", "salchicha", "kimchi", "tofu", "brotes de soja", "ramen", "gochujang", "guindilla en polvo", "cebolleta"] },
  { name: "Sopa de costilla de ternera", ingredients: ["costilla de ternera", "daikon", "cebolleta", "ajo", "jengibre", "salsa de soja", "fideos de batata"] },
  { name: "Tortilla coreana de mariscos", ingredients: ["calamar", "gamba", "cebolleta", "harina de trigo", "huevo", "agua", "salsa de soja", "vinagre"] },
  { name: "Yukgaejang", ingredients: ["ternera", "helecho", "brotes de soja", "tallo de taro", "cebolleta", "guindilla en polvo", "salsa de soja", "ajo"] },
  { name: "Bossam", ingredients: ["cerdo", "ajo", "jengibre", "cebolleta", "miso", "salsa de camarón salado", "kimchi de rábano", "col china"] },
  { name: "Samgyetang", ingredients: ["pollo", "ginseng", "azufaifo", "ajo", "arroz glutinoso", "cebolleta", "sal"] },
  { name: "Jjimdak", ingredients: ["pollo", "patata", "zanahoria", "cebolla", "cebolleta", "fideos de batata", "salsa de soja", "azúcar", "ajo"] },
  { name: "Bibim guksu", ingredients: ["fideos", "gochujang", "vinagre", "azúcar", "pepino", "lechuga", "huevo", "aceite de sésamo"] },
  { name: "Kimbap", ingredients: ["arroz", "alga nori", "takuwan", "espinaca", "zanahoria", "huevo", "jamón", "odeng", "aceite de sésamo"] },
  { name: "Jeyuk bokkeum", ingredients: ["cerdo", "gochujang", "guindilla en polvo", "salsa de soja", "azúcar", "ajo", "cebolla", "cebolleta"] },
  { name: "Dakbokkeumtang", ingredients: ["pollo", "patata", "zanahoria", "cebolla", "cebolleta", "gochujang", "guindilla en polvo", "ajo"] },
  { name: "Doenjang jjigae", ingredients: ["miso", "tofu", "calabacín", "cebolla", "cebolleta", "setas", "guindilla", "caldo de anchoa"] },
  { name: "Agujjim", ingredients: ["rape", "brotes de soja", "midodok", "seri", "guindilla en polvo", "ajo", "salsa de soja", "fécula de patata"] },
  { name: "Gopchang jeongol", ingredients: ["intestinos de ternera", "cebolleta", "cebolla", "hoja de perilla", "setas", "tofu", "guindilla en polvo", "ajo picado", "caldo"] },
  { name: "Pollo frito picante coreano", ingredients: ["pollo", "gochujang", "jarabe de maíz", "kétchup", "ajo", "salsa de soja", "cacahuete", "mezcla para rebozar"] },
  { name: "Gukbap", ingredients: ["arroz", "cerdo", "vísceras", "cebolleta", "ajo", "guindilla en polvo", "sundae"] },
  { name: "Pasta aglio e olio", ingredients: ["espaguetis", "ajo", "aceite de oliva", "guindilla", "perejil"] },
  { name: "Pasta alle vongole", ingredients: ["espaguetis", "almeja", "ajo", "aceite de oliva", "vino blanco", "perejil"] },
  { name: "Gambas al ajillo", ingredients: ["gamba", "ajo", "aceite de oliva", "guindilla", "baguette"] },
  { name: "Bistec con salsa", ingredients: ["ternera", "pimiento", "cebolla", "setas", "salsa de soja", "kétchup", "azúcar", "salsa de bistec"] },
  { name: "Ensalada de ricotta", ingredients: ["queso ricotta", "hojas verdes", "vinagreta balsámica", "tomate", "nueces"] },
  { name: "Tortitas de patata coreanas", ingredients: ["patata", "cebolla", "mezcla para tortitas", "agua", "sal", "aceite"] },
  { name: "Caballa a la plancha", ingredients: ["caballa", "sal", "pimienta", "limón", "aceite"] },
  { name: "Salteado de pulpo pequeño", ingredients: ["pulpo pequeño", "cebolla", "cebolleta", "col", "gochujang", "guindilla en polvo", "ajo", "azúcar"] },
  { name: "Salteado de patas de pollo", ingredients: ["patas de pollo", "gochujang", "guindilla en polvo", "ajo", "cebolla", "cebolleta", "azúcar", "jarabe de maíz"] },
  { name: "Helado", ingredients: ["leche", "azúcar", "yema de huevo", "nata", "vainilla"] },
  { name: "Tiramisú", ingredients: ["queso mascarpone", "bizcocho de soletilla", "café", "azúcar", "yema de huevo", "cacao en polvo"] },
  { name: "Macaron", ingredients: ["harina de almendra", "azúcar glas", "clara de huevo", "azúcar", "colorante alimentario"] },
  { name: "Croffle", ingredients: ["masa de croissant", "gofrera", "azúcar", "mantequilla"] },
  { name: "Pastel de huevo", ingredients: ["masa de tarta", "huevo", "leche", "azúcar", "nata", "extracto de vainilla"] },
  { name: "Pan con anko y mantequilla", ingredients: ["pan", "pasta de judía roja", "mantequilla"] },
  { name: "Hotteok", ingredients: ["harina de trigo", "azúcar", "levadura", "agua", "semillas", "miel"] },
  { name: "Bungeoppang", ingredients: ["harina de trigo", "huevo", "leche", "azúcar", "pasta de judía roja", "mantequilla"] },
  { name: "Perro caliente", ingredients: ["salchicha", "pan", "kétchup", "mostaza", "cebolla", "pepinillos"] },
  { name: "Sopa de cebolla francesa", ingredients: ["cebolla", "caldo de ternera", "pan", "queso", "mantequilla", "harina de trigo"] },
  { name: "Espaguetis con albóndigas", ingredients: ["espaguetis", "carne picada de ternera", "salsa de tomate", "cebolla", "ajo", "pan rallado", "huevo"] },
  { name: "Tacos de pescado", ingredients: ["pescado", "tortilla", "col", "salsa", "lima", "cilantro"] },
  { name: "Scone de queso", ingredients: ["harina de trigo", "mantequilla", "leche", "queso", "levadura en polvo"] },
  { name: "Muffin de arándanos", ingredients: ["harina de trigo", "arándano", "azúcar", "huevo", "leche", "aceite", "levadura en polvo"] }
];

window.INGREDIENTS_DB = [
  "huevo", "pollo", "ternera", "cerdo", "cebolla", "ajo", "zanahoria", "patata", "espaguetis", "arroz", "tomate", "lechuga",
  "tofu", "brotes de soja", "cacahuetes", "vino tinto", "miso", "alga nori", "kimchi", "bacon", "queso parmesano", "anchoa", "pan",
  "queso", "gamba", "hierba limón", "galanga", "lima", "pimiento", "berenjena", "calabacín", "picatostes", "caldo dashi",
  "panceta", "pimienta", "setas", "yogur", "harina de trigo", "azúcar", "sal", "mantequilla", "leche", "nata", "pepino",
  "manzana", "plátano", "naranja", "limón", "lima", "brócoli", "espinaca", "calabaza", "batata", "maíz", "guisantes",
  "col", "apio", "jengibre", "salsa de soja", "vinagre", "aceite de oliva", "aceite de canola", "aceite de girasol", "aceite de sésamo",
  "salsa de pescado", "salsa de ostra", "pasta de judía dulce (tianmianjiang)", "kétchup", "mostaza", "mayonesa", "albahaca", "cilantro", "perejil",
  "romero", "tomillo", "salvia", "menta", "canela", "nuez moscada", "clavo", "laurel", "anís estrellado", "cardamomo",
  "curry en polvo", "chile en polvo", "pimentón", "cúrcuma", "comino", "cilantro (semilla)", "eneldo", "hinojo", "vainilla",
  "chocolate", "cacao en polvo", "mermelada", "miel", "jarabe de arce", "melaza", "fresa", "arándano", "frambuesa",
  "arándano rojo", "mora", "piña", "mango", "kiwi", "uva", "pera", "melocotón", "albaricoque", "ciruela", "azufaifo",
  "higo", "coco", "nuez", "almendra", "avellana", "anacardo", "pistacho", "macadamia", "pecana", "semilla de girasol",
  "semilla de chía", "semilla de calabaza", "sésamo", "quinoa", "cebada", "mijo", "alforfón", "avena", "pan", "pasta",
  "fideos", "tortilla", "pan naan", "pan pita", "pan de masa madre", "bagel", "croissant", "donut", "masa de pizza", "galleta salada",
  "salchicha", "salami", "jamón", "pato", "cordero", "pavo", "conejo", "ternera lechal", "ganso", "anchoa", "sardina", "atún",
  "caballa", "salmón", "bacalao", "eglefino", "merlán", "bagre", "tilapia", "calamar", "pulpo", "almeja", "mejillón",
  "vieira", "langosta", "cangrejo", "cangrejo de río", "oreja de mar", "pepino de mar", "erizo de mar", "wasabi", "rábano picante",
  "tabasco", "salsa sriracha", "gochujang", "ssamjang", "miso", "miso", "judía roja", "judía negra", "judía",
  "garbanzo", "lenteja", "alubia", "judía blanca", "judía verde", "guisante dulce", "guisante dulce", "edamame", "mozzarella",
  "cheddar", "gouda", "brie", "camembert", "feta", "queso azul", "suizo", "provolone", "ricotta",
  "mascarpone", "queso crema", "requesón", "crema agria", "yogur", "suero de leche", "leche condensada",
  "leche condensada azucarada", "leche en polvo", "leche de almendra", "leche de soja", "leche de arroz", "leche de coco", "leche de avena",
  "pasta de gamba", "pasta de anchoa", "pasta de tomate", "salsa de tomate", "pesto", "salsa picante", "harissa", "azba",
  "tahini", "hummus", "guacamole", "salsa", "relish", "tapenade", "salsa gravy", "caldo", "caldo", "caldo", "gelatina",
  "agar-agar", "fécula de patata", "fécula de patata", "tapioca", "arrurruz", "harina de arroz", "sémola", "harina de maíz",
  "polenta", "germen de trigo", "salvado de trigo", "hoja de arroz", "hoja de rollito de primavera", "alga nori", "pastel de arroz", "udon", "ramen",
  "fideo de celofán", "alforfón", "fettuccine", "penne", "macarrones", "lasaña", "espaguetis", "linguine", "cabello de ángel",
  "gnocchi", "ravioli", "tortellini", "gyoza", "wonton", "pierogi", "empanada", "tamal", "cebolleta",
  "chalota", "puerro", "nabo", "rábano", "chirivía", "rutabaga", "remolacha", "colinabo", "rábano japonés (daikon)", "jícama", "raíz de loto",
  "alcachofa", "espárrago", "okra", "brote de bambú (menma)", "yema de huevo", "clara de huevo", "huevo de codorniz", "huevo de pato", "huevo de ganso",
  "trufa", "morilla", "boletus", "enoki", "shiitake", "pleurotus", "boletus", "champiñón", "portobello",
  "castaña", "arrowhead", "taro", "ñame", "mandioca", "salsifí", "topinambur", "hinojo (bulbo)",
  "rúcula", "pesto de albahaca", "pimiento", "bok choy", "col de Bruselas", "suero de leche", "alcaparra",
  "caramelo", "alcaravea", "anacardo", "chía", "aceite de chile", "cebollino", "semilla de cilantro", "requesón",
  "cangrejo", "arándano rojo", "nata", "berro", "diente de león", "dátil", "hoja de rollito de huevo", "espelta", "fenogreco",
  "queso feta", "mantequilla de maní", "queso de cabra", "judía verde", "guayaba", "avellana", "semilla de cáñamo", "mezcla de hierbas",
  "jackfruit", "kale", "jugo de kimchi", "kumquat", "puerro", "pasta de lentejas", "lichi", "chutney de mango",
  "queso manchego", "bacon de arce", "mejorana", "mizuna", "monk fruit", "salsa de champiñón", "mostaza verde",
  "col china", "nectarina", "okra", "oliva", "cáscara de naranja", "papaya", "maracuyá", "germinado de guisante",
  "pacana", "queso pepper jack", "caqui", "piñón", "crema de pistacho", "tomate ciruela", "palomitas", "prosciutto",
  "pan pumpernickel", "quark", "achicoria", "ras el hanout", "lenteja roja", "ricotta salada", "rucula", "lechuga romana",
  "roquefort", "agua de rosas", "rutabaga", "sago", "salsifí", "col de Saboya", "cebollino verde", "chalota",
  "shiso", "tofu sedoso", "salmón ahumado", "guisante dulce", "guisante dulce", "acedera", "proteína de soja", "espelta",
  "tinta de calamar", "stilton", "seta nameko", "sumac", "tomate seco", "maíz dulce", "acelga",
  "tamarindo", "tempeh", "tomillo", "sésamo tostado", "yuba", "tomate", "aceite de trufa", "hoja de nabo",
  "naranja valenciana", "queso vegano", "venado", "fideo de celofán", "arroz con vinagre", "berro", "harina de trigo",
  "chocolate blanco", "arroz salvaje", "ñame", "zaatar", "zest", "flor de calabacín", "judía roja", "amaranto",
  "anís", "brote de bambú", "pimiento banana", "semilla de albahaca", "vieira pequeña", "ajo negro", "naranja sanguina",
  "borraja", "bresaola", "cactus", "calamar", "melón canario", "jengibre confitado", "hoja de zanahoria", "harina de mandioca",
  "apio", "chayote", "seta shimeji", "chorizo", "mora de los pantanos", "azúcar de coco", "ajo confitado",
  "ensalada de maíz", "alubia cranberry", "champiñón cremini", "dolma", "edamame", "helecho", "hueva de pescado", "frisee", "garam masala",
  "cebollino de ajo", "bayas de goji", "remolacha dorada", "ajo joven", "guanciale", "pata de cerdo", "raíz de rábano picante",
  "topinambur", "citrus kobu", "regaliz", "alga kombu", "lardon", "lavanda", "limoncello", "haba larga",
  "semilla de loto", "caramelo de miso", "mijtra", "mora", "muscat", "capuchina", "ortiga", "hoja de okra",
  "oliva orali", "hoja de chirivía", "calabacín pattypan", "pecorino", "pepino dulce", "hoja de perilla", "encurtido",
  "judía", "salvia de piña", "pimienta rosa", "ciruela pasa", "pimiento poblano", "verdolaga", "membrillo", "ajo de oso",
  "ruibarbo", "ajo asado", "romanesco", "judía", "hoja de rutabaga", "hueva de salmón", "batata", "espárrago de mar",
  "jamón", "salchicha", "ramen", "rábano japonés (daikon)", "cebollino verde", "calamar", "midodok", "apio japonés", "tallo de taro", "helecho", "pasta de gamba salada",
  "ginseng", "azufaifo", "arroz glutinoso", "fécula de patata", "casquería de ternera", "hoja de perilla", "sopa", "jarabe de malta", "rape",
  "morcilla", "peperoncino", "baguette", "vino blanco", "salsa para filete", "hojas tiernas", "aderezo balsámico", "frutos secos",
  "harina para jeon", "caballa", "pulpo pequeño", "col", "pata de pollo", "almendra en polvo", "azúcar glas", "colorante alimentario",
  "masa de croissant", "máquina de gofres", "masa de tarta", "extracto de vainilla", "pasta de judía roja", "levadura", "semilla", "miel", "pasta de judía roja",
  "salchicha", "aceite", "levadura en polvo"
];
