PAGES = [
 ("util/dice3d/index.html","WebApplication","tool","/util/"),
 ("jp/game/TetrisGame/index.html","VideoGame","game","/jp/game/"),
 ("game/MBTI/index.html","WebApplication","game","/game/"),
 ("kor/report/visa/nigeria.html","WebPage","visa","/kor/report/visa/"),
 ("kor/report/camp/gapyeong.html","WebPage","camp","/kor/report/camp/"),
 ("game/FlappyDot/index.html","VideoGame","game","/game/"),
 ("kor/report/visa/russia.html","WebPage","visa","/kor/report/visa/"),
 ("game/MatrixDefense/index.html","VideoGame","game","/game/"),
 ("kor/report/camp/busan.html","WebPage","camp","/kor/report/camp/"),
 ("game/FlagQuest/index.html","VideoGame","game","/game/"),
 ("game/BlockBreaker/index.html","VideoGame","game","/game/"),
 ("kor/report/camp/gongju.html","WebPage","camp","/kor/report/camp/"),
 ("kor/report/travel/bosnia-mostar.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/montenegro-kotor.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/tanzania-dodoma.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/saudi-mecca.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/myanmar-nyaungshwe.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/turkmenistan-ashgabat.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/uzbekistan-urgench.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/vietnam-thainguyen.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/laos-vangvieng.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/camp/goheung.html","WebPage","camp","/kor/report/camp/"),
 ("kor/report/travel/china-ningbo.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/gpt-stock-guide.html","WebPage","finance","/kor/report/finance/"),
 ("kor/report/travel/norway-alesund.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/morocco-tiflet.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/mongolia-dalanzadgad.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/visa/uganda.html","WebPage","visa","/kor/report/visa/"),
 ("kor/report/travel/russia-yekaterinburg.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/window/windows11-update-error-0x80070306-fix.html","WebPage","windows","/kor/report/window/"),
 ("kor/report/travel/saudi-dammam.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/poland-warsaw.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/visa/georgia.html","WebPage","visa","/kor/report/visa/"),
 ("kor/report/travel/china-lanzhou.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/benin-sakete.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/malaysia-kota-kinabalu.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/morocco-meknes.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/window/windows11-boot-time-optimization.html","WebPage","windows","/kor/report/window/"),
 ("kor/report/travel/japan-utsunomiya.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/honduras-lalima.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/visa/malaysia.html","WebPage","visa","/kor/report/visa/"),
 ("kor/report/travel/japan-sendai.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/russia-khabarovsk.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/finance/dividend-stocks-2026.html","WebPage","finance","/kor/report/finance/"),
 ("kor/report/travel/malaysia-johor-bahru.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/philippines-santa-rosa.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/egypt-cairo.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/ethiopia-giga.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/vietnam-cantho.html","WebPage","travel","/kor/report/travel/"),
 ("kor/report/travel/germany-dresden.html","WebPage","travel","/kor/report/travel/"),
]

BATCHES = [PAGES[i:i + 10] for i in range(0, 50, 10)]
assert len(PAGES) == 50
assert len({row[0] for row in PAGES}) == 50
assert all(len(batch) == 10 for batch in BATCHES)
