const flags = [
	{ country: "अफ़ग़ानिस्तान", img: "https://flagcdn.com/af.svg" },
	{ country: "एलैंड द्वीप समूह", img: "https://flagcdn.com/ax.svg" },
	{ country: "अल्बानिया", img: "https://flagcdn.com/al.svg" },
	{ country: "अल्जीरिया", img: "https://flagcdn.com/dz.svg" },
	{ country: "अमेरिकी समोआ", img: "https://flagcdn.com/as.svg" },
	{ country: "अंडोरा", img: "https://flagcdn.com/ad.svg" },
	{ country: "अंगोला", img: "https://flagcdn.com/ao.svg" },
	{ country: "एंगुइला", img: "https://flagcdn.com/ai.svg" },
	{ country: "अंटार्कटिका", img: "https://flagcdn.com/aq.svg" },
	{ country: "एंटीगुआ और बारबुडा", img: "https://flagcdn.com/ag.svg" },
	{ country: "अर्जेंटीना", img: "https://flagcdn.com/ar.svg" },
	{ country: "आर्मेनिया", img: "https://flagcdn.com/am.svg" },
	{ country: "अरूबा", img: "https://flagcdn.com/aw.svg" },
	{ country: "ऑस्ट्रेलिया", img: "https://flagcdn.com/au.svg" },
	{ country: "ऑस्ट्रिया", img: "https://flagcdn.com/at.svg" },
	{ country: "अज़रबैजान", img: "https://flagcdn.com/az.svg" },
	{ country: "बहामास", img: "https://flagcdn.com/bs.svg" },
	{ country: "बहरीन", img: "https://flagcdn.com/bh.svg" },
	{ country: "बांग्लादेश", img: "https://flagcdn.com/bd.svg" },
	{ country: "बारबाडोस", img: "https://flagcdn.com/bb.svg" },
	{ country: "बेलारूस", img: "https://flagcdn.com/by.svg" },
	{ country: "बेल्जियम", img: "https://flagcdn.com/be.svg" },
	{ country: "बेलीज़", img: "https://flagcdn.com/bz.svg" },
	{ country: "बेनिन", img: "https://flagcdn.com/bj.svg" },
	{ country: "बरमूडा", img: "https://flagcdn.com/bm.svg" },
	{ country: "भूटान", img: "https://flagcdn.com/bt.svg" },
	{ country: "बोलीविया", img: "https://flagcdn.com/bo.svg" },
	{ country: "कैरेबियाई नीदरलैंड", img: "https://flagcdn.com/bq.svg" },
	{ country: "बोस्निया और हर्जेगोविना", img: "https://flagcdn.com/ba.svg" },
	{ country: "बोत्सवाना", img: "https://flagcdn.com/bw.svg" },
	{ country: "बूवेट द्वीप", img: "https://flagcdn.com/bv.svg" },
	{ country: "ब्राजील", img: "https://flagcdn.com/br.svg" },
	{ country: "ब्रिटिश हिंद महासागर क्षेत्र", img: "https://flagcdn.com/io.svg" },
	{ country: "ब्रिटिश वर्जिन द्वीप समूह", img: "https://flagcdn.com/vg.svg" },
	{ country: "ब्रुनेई", img: "https://flagcdn.com/bn.svg" },
	{ country: "बुल्गारिया", img: "https://flagcdn.com/bg.svg" },
	{ country: "बुर्किना फ़ासो", img: "https://flagcdn.com/bf.svg" },
	{ country: "बुरुंडी", img: "https://flagcdn.com/bi.svg" },
	{ country: "केप वर्डे", img: "https://flagcdn.com/cv.svg" },
	{ country: "कंबोडिया", img: "https://flagcdn.com/kh.svg" },
	{ country: "कैमरून", img: "https://flagcdn.com/cm.svg" },
	{ country: "कनाडा", img: "https://flagcdn.com/ca.svg" },
	{ country: "केमैन द्वीप समूह", img: "https://flagcdn.com/ky.svg" },
	{ country: "मध्य अफ़्रीकी गणराज्य", img: "https://flagcdn.com/cf.svg" },
	{ country: "चाड", img: "https://flagcdn.com/td.svg" },
	{ country: "चिली", img: "https://flagcdn.com/cl.svg" },
	{ country: "चीन", img: "https://flagcdn.com/cn.svg" },
	{ country: "क्रिसमस द्वीप", img: "https://flagcdn.com/cx.svg" },
	{ country: "कोकोस (कीलिंग) द्वीप समूह", img: "https://flagcdn.com/cc.svg" },
	{ country: "कोलम्बिया", img: "https://flagcdn.com/co.svg" },
	{ country: "कोमोरोस", img: "https://flagcdn.com/km.svg" },
	{ country: "कांगो (DRC)", img: "https://flagcdn.com/cd.svg" },
	{ country: "कांगो (गणराज्य)", img: "https://flagcdn.com/cg.svg" },
	{ country: "कुक द्वीप समूह", img: "https://flagcdn.com/ck.svg" },
	{ country: "कोस्टा रिका", img: "https://flagcdn.com/cr.svg" },
	{ country: "कोटे डी आइवर", img: "https://flagcdn.com/ci.svg" },
	{ country: "क्रोएशिया", img: "https://flagcdn.com/hr.svg" },
	{ country: "क्यूबा", img: "https://flagcdn.com/cu.svg" },
	{ country: "कुराकाओ", img: "https://flagcdn.com/cw.svg" },
	{ country: "साइप्रस", img: "https://flagcdn.com/cy.svg" },
	{ country: "चेक गणराज्य", img: "https://flagcdn.com/cz.svg" },
	{ country: "डेनमार्क", img: "https://flagcdn.com/dk.svg" },
	{ country: "जिबूती", img: "https://flagcdn.com/dj.svg" },
	{ country: "डोमिनिका", img: "https://flagcdn.com/dm.svg" },
	{ country: "डोमिनिकन गणराज्य", img: "https://flagcdn.com/do.svg" },
	{ country: "इक्वाडोर", img: "https://flagcdn.com/ec.svg" },
	{ country: "मिस्र", img: "https://flagcdn.com/eg.svg" },
	{ country: "अल सल्वाडोर", img: "https://flagcdn.com/sv.svg" },
	{ country: "भूमध्यरेखीय गिनी", img: "https://flagcdn.com/gq.svg" },
	{ country: "इरिट्रिया", img: "https://flagcdn.com/er.svg" },
	{ country: "एस्टोनिया", img: "https://flagcdn.com/ee.svg" },
	{ country: "ईस्वातिनी", img: "https://flagcdn.com/sz.svg" },
	{ country: "इथियोपिया", img: "https://flagcdn.com/et.svg" },
	{ country: "फ़ॉकलैंड द्वीप समूह", img: "https://flagcdn.com/fk.svg" },
	{ country: "फ़ेरो द्वीप समूह", img: "https://flagcdn.com/fo.svg" },
	{ country: "फ़िजी", img: "https://flagcdn.com/fj.svg" },
	{ country: "फ़िनलैंड", img: "https://flagcdn.com/fi.svg" },
	{ country: "फ़्रांस", img: "https://flagcdn.com/fr.svg" },
	{ country: "फ़्रेंच गयाना", img: "https://flagcdn.com/gf.svg" },
	{ country: "फ़्रेंच पोलिनेशिया", img: "https://flagcdn.com/pf.svg" },
	{ country: "फ़्रेंच दक्षिणी और अंटार्कटिक भूमि", img: "https://flagcdn.com/tf.svg" },
	{ country: "गैबॉन", img: "https://flagcdn.com/ga.svg" },
	{ country: "गाम्बिया", img: "https://flagcdn.com/gm.svg" },
	{ country: "जॉर्जिया", img: "https://flagcdn.com/ge.svg" },
	{ country: "जर्मनी", img: "https://flagcdn.com/de.svg" },
	{ country: "घाना", img: "https://flagcdn.com/gh.svg" },
	{ country: "जिब्राल्टर", img: "https://flagcdn.com/gi.svg" },
	{ country: "ग्रीस", img: "https://flagcdn.com/gr.svg" },
	{ country: "ग्रीनलैंड", img: "https://flagcdn.com/gl.svg" },
	{ country: "ग्रेनेडा", img: "https://flagcdn.com/gd.svg" },
	{ country: "गुआदेलूप", img: "https://flagcdn.com/gp.svg" },
	{ country: "गुआम", img: "https://flagcdn.com/gu.svg" },
	{ country: "ग्वाटेमाला", img: "https://flagcdn.com/gt.svg" },
	{ country: "ग्वेर्नसे", img: "https://flagcdn.com/gg.svg" },
	{ country: "गिनी", img: "https://flagcdn.com/gn.svg" },
	{ country: "गिनी-बिसाऊ", img: "https://flagcdn.com/gw.svg" },
	{ country: "गुयाना", img: "https://flagcdn.com/gy.svg" },
	{ country: "हैती", img: "https://flagcdn.com/ht.svg" },
	{ country: "हर्ड द्वीप और मैकडॉनल्ड द्वीप समूह", img: "https://flagcdn.com/hm.svg" },
	{ country: "वेटिकन सिटी", img: "https://flagcdn.com/va.svg" },
	{ country: "होंडुरास", img: "https://flagcdn.com/hn.svg" },
	{ country: "हांगकांग", img: "https://flagcdn.com/hk.svg" },
	{ country: "हंगरी", img: "https://flagcdn.com/hu.svg" },
	{ country: "आइसलैंड", img: "https://flagcdn.com/is.svg" },
	{ country: "भारत", img: "https://flagcdn.com/in.svg" },
	{ country: "इंडोनेशिया", img: "https://flagcdn.com/id.svg" },
	{ country: "ईरान", img: "https://flagcdn.com/ir.svg" },
	{ country: "इराक", img: "https://flagcdn.com/iq.svg" },
	{ country: "आयरलैंड", img: "https://flagcdn.com/ie.svg" },
	{ country: "आइल ऑफ मैन", img: "https://flagcdn.com/im.svg" },
	{ country: "इज़राइल", img: "https://flagcdn.com/il.svg" },
	{ country: "इटली", img: "https://flagcdn.com/it.svg" },
	{ country: "जमैका", img: "https://flagcdn.com/jm.svg" },
	{ country: "जापान", img: "https://flagcdn.com/jp.svg" },
	{ country: "जर्सी", img: "https://flagcdn.com/je.svg" },
	{ country: "जॉर्डन", img: "https://flagcdn.com/jo.svg" },
	{ country: "कज़ाखस्तान", img: "https://flagcdn.com/kz.svg" },
	{ country: "केन्या", img: "https://flagcdn.com/ke.svg" },
	{ country: "किरिबाती", img: "https://flagcdn.com/ki.svg" },
	{ country: "उत्तर कोरिया", img: "https://flagcdn.com/kp.svg" },
	{ country: "दक्षिण कोरिया", img: "https://flagcdn.com/kr.svg" },
	{ country: "कुवैत", img: "https://flagcdn.com/kw.svg" },
	{ country: "किर्गिस्तान", img: "https://flagcdn.com/kg.svg" },
	{ country: "लाओस", img: "https://flagcdn.com/la.svg" },
	{ country: "लातविया", img: "https://flagcdn.com/lv.svg" },
	{ country: "लेबनान", img: "https://flagcdn.com/lb.svg" },
	{ country: "लेसोथो", img: "https://flagcdn.com/ls.svg" },
	{ country: "लाइबेरिया", img: "https://flagcdn.com/lr.svg" },
	{ country: "लीबिया", img: "https://flagcdn.com/ly.svg" },
	{ country: "लिकटेंस्टीन", img: "https://flagcdn.com/li.svg" },
	{ country: "लिथुआनिया", img: "https://flagcdn.com/lt.svg" },
	{ country: "लक्ज़मबर्ग", img: "https://flagcdn.com/lu.svg" },
	{ country: "मकाऊ", img: "https://flagcdn.com/mo.svg" },
	{ country: "मेडागास्कर", img: "https://flagcdn.com/mg.svg" },
	{ country: "मलावी", img: "https://flagcdn.com/mw.svg" },
	{ country: "मलेशिया", img: "https://flagcdn.com/my.svg" },
	{ country: "मालदीव", img: "https://flagcdn.com/mv.svg" },
	{ country: "माली", img: "https://flagcdn.com/ml.svg" },
	{ country: "माल्टा", img: "https://flagcdn.com/mt.svg" },
	{ country: "मार्शल द्वीप समूह", img: "https://flagcdn.com/mh.svg" },
	{ country: "मार्टीनिक", img: "https://flagcdn.com/mq.svg" },
	{ country: "मॉरिटानिया", img: "https://flagcdn.com/mr.svg" },
	{ country: "मॉरीशस", img: "https://flagcdn.com/mu.svg" },
	{ country: "मायोट", img: "https://flagcdn.com/yt.svg" },
	{ country: "मेक्सिको", img: "https://flagcdn.com/mx.svg" },
	{ country: "माइक्रोनेशिया", img: "https://flagcdn.com/fm.svg" },
	{ country: "मोल्दोवा", img: "https://flagcdn.com/md.svg" },
	{ country: "मोनाको", img: "https://flagcdn.com/mc.svg" },
	{ country: "मंगोलिया", img: "https://flagcdn.com/mn.svg" },
	{ country: "मोंटेनेग्रो", img: "https://flagcdn.com/me.svg" },
	{ country: "मोंटसेराट", img: "https://flagcdn.com/ms.svg" },
	{ country: "मोरक्को", img: "https://flagcdn.com/ma.svg" },
	{ country: "मोज़ाम्बिक", img: "https://flagcdn.com/mz.svg" },
	{ country: "म्यांमार", img: "https://flagcdn.com/mm.svg" },
	{ country: "नामीबिया", img: "https://flagcdn.com/na.svg" },
	{ country: "नाउरु", img: "https://flagcdn.com/nr.svg" },
	{ country: "नेपाल", img: "https://flagcdn.com/np.svg" },
	{ country: "नीदरलैंड", img: "https://flagcdn.com/nl.svg" },
	{ country: "न्यू कैलेडोनिया", img: "https://flagcdn.com/nc.svg" },
	{ country: "न्यूजीलैंड", img: "https://flagcdn.com/nz.svg" },
	{ country: "निकारागुआ", img: "https://flagcdn.com/ni.svg" },
	{ country: "नाइजर", img: "https://flagcdn.com/ne.svg" },
	{ country: "नाइजीरिया", img: "https://flagcdn.com/ng.svg" },
	{ country: "नियू", img: "https://flagcdn.com/nu.svg" },
	{ country: "नॉरफ़ॉक द्वीप", img: "https://flagcdn.com/nf.svg" },
	{ country: "उत्तरी मारियाना द्वीप समूह", img: "https://flagcdn.com/mp.svg" },
	{ country: "नॉर्वे", img: "https://flagcdn.com/no.svg" },
	{ country: "ओमान", img: "https://flagcdn.com/om.svg" },
	{ country: "पाकिस्तान", img: "https://flagcdn.com/pk.svg" },
	{ country: "पलाऊ", img: "https://flagcdn.com/pw.svg" },
	{ country: "फिलिस्तीन", img: "https://flagcdn.com/ps.svg" },
	{ country: "पनामा", img: "https://flagcdn.com/pa.svg" },
	{ country: "पापुआ न्यू गिनी", img: "https://flagcdn.com/pg.svg" },
	{ country: "पैरागुए", img: "https://flagcdn.com/py.svg" },
	{ country: "पेरू", img: "https://flagcdn.com/pe.svg" },
	{ country: "फिलीपींस", img: "https://flagcdn.com/ph.svg" },
	{ country: "पिटकेर्न द्वीप समूह", img: "https://flagcdn.com/pn.svg" },
	{ country: "पोलैंड", img: "https://flagcdn.com/pl.svg" },
	{ country: "पुर्तगाल", img: "https://flagcdn.com/pt.svg" },
	{ country: "प्यूर्टो रिको", img: "https://flagcdn.com/pr.svg" },
	{ country: "कतर", img: "https://flagcdn.com/qa.svg" },
	{ country: "रियूनियन", img: "https://flagcdn.com/re.svg" },
	{ country: "रोमानिया", img: "https://flagcdn.com/ro.svg" },
	{ country: "रूस", img: "https://flagcdn.com/ru.svg" },
	{ country: "रवांडा", img: "https://flagcdn.com/rw.svg" },
	{ country: "सेंट बार्थेलेमी", img: "https://flagcdn.com/bl.svg" },
	{ country: "सेंट हेलेना", img: "https://flagcdn.com/sh.svg" },
	{ country: "सेंट किट्स एंड नेविस", img: "https://flagcdn.com/kn.svg" },
	{ country: "सेंट लूसिया", img: "https://flagcdn.com/lc.svg" },
	{ country: "सेंट मार्टिन", img: "https://flagcdn.com/mf.svg" },
	{ country: "सेंट पियरे और मिकेलॉन", img: "https://flagcdn.com/pm.svg" },
	{ country: "सेंट विंसेंट और ग्रेनाडीन्स", img: "https://flagcdn.com/vc.svg" },
	{ country: "समोआ", img: "https://flagcdn.com/ws.svg" },
	{ country: "सैन मैरिनो", img: "https://flagcdn.com/sm.svg" },
	{ country: "साओ टोमे और प्रिंसिपे", img: "https://flagcdn.com/st.svg" },
	{ country: "सऊदी अरब", img: "https://flagcdn.com/sa.svg" },
	{ country: "सेनेगल", img: "https://flagcdn.com/sn.svg" },
	{ country: "सर्बिया", img: "https://flagcdn.com/rs.svg" },
	{ country: "सेशेल्स", img: "https://flagcdn.com/sc.svg" },
	{ country: "सिएरा लियोन", img: "https://flagcdn.com/sl.svg" },
	{ country: "सिंगापुर", img: "https://flagcdn.com/sg.svg" },
	{ country: "सिंट मार्टेन", img: "https://flagcdn.com/sx.svg" },
	{ country: "स्लोवाकिया", img: "https://flagcdn.com/sk.svg" },
	{ country: "स्लोवेनिया", img: "https://flagcdn.com/si.svg" },
	{ country: "सोलोमन द्वीप समूह", img: "https://flagcdn.com/sb.svg" },
	{ country: "सोमालिया", img: "https://flagcdn.com/so.svg" },
	{ country: "दक्षिण अफ्रीका", img: "https://flagcdn.com/za.svg" },
	{ country: "दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीप समूह", img: "https://flagcdn.com/gs.svg" },
	{ country: "दक्षिण सूडान", img: "https://flagcdn.com/ss.svg" },
	{ country: "स्पेन", img: "https://flagcdn.com/es.svg" },
	{ country: "श्रीलंका", img: "https://flagcdn.com/lk.svg" },
	{ country: "सूडान", img: "https://flagcdn.com/sd.svg" },
	{ country: "सूरीनाम", img: "https://flagcdn.com/sr.svg" },
	{ country: "स्वालबार्ड और जान मायेन", img: "https://flagcdn.com/sj.svg" },
	{ country: "स्वीडन", img: "https://flagcdn.com/se.svg" },
	{ country: "स्विट्जरलैंड", img: "https://flagcdn.com/ch.svg" },
	{ country: "सीरिया", img: "https://flagcdn.com/sy.svg" },
	{ country: "ताइवान", img: "https://flagcdn.com/tw.svg" },
	{ country: "ताजिकिस्तान", img: "https://flagcdn.com/tj.svg" },
	{ country: "तंजानिया", img: "https://flagcdn.com/tz.svg" },
	{ country: "थाईलैंड", img: "https://flagcdn.com/th.svg" },
	{ country: "पूर्वी तिमोर", img: "https://flagcdn.com/tl.svg" },
	{ country: "टोगो", img: "https://flagcdn.com/tg.svg" },
	{ country: "टोकेलाऊ", img: "https://flagcdn.com/tk.svg" },
	{ country: "टोंगा", img: "https://flagcdn.com/to.svg" },
	{ country: "त्रिनिदाद और टोबैगो", img: "https://flagcdn.com/tt.svg" },
	{ country: "ट्यूनीशिया", img: "https://flagcdn.com/tn.svg" },
	{ country: "तुर्किये", img: "https://flagcdn.com/tr.svg" },
	{ country: "तुर्कमेनिस्तान", img: "https://flagcdn.com/tm.svg" },
	{ country: "तुर्क और कैकोस द्वीप समूह", img: "https://flagcdn.com/tc.svg" },
	{ country: "तुवालु", img: "https://flagcdn.com/tv.svg" },
	{ country: "युगांडा", img: "https://flagcdn.com/ug.svg" },
	{ country: "यूक्रेन", img: "https://flagcdn.com/ua.svg" },
	{ country: "संयुक्त अरब अमीरात", img: "https://flagcdn.com/ae.svg" },
	{ country: "यूनाइटेड किंगडम", img: "https://flagcdn.com/gb.svg" },
	{ country: "संयुक्त राज्य अमेरिका", img: "https://flagcdn.com/us.svg" },
	{ country: "संयुक्त राज्य अमेरिका के छोटे बाहरी द्वीप", img: "https://flagcdn.com/um.svg" },
	{ country: "उरुग्वे", img: "https://flagcdn.com/uy.svg" },
	{ country: "उज़्बेकिस्तान", img: "https://flagcdn.com/uz.svg" },
	{ country: "वानुअतु", img: "https://flagcdn.com/vu.svg" },
	{ country: "वेनेजुएला", img: "https://flagcdn.com/ve.svg" },
	{ country: "वियतनाम", img: "https://flagcdn.com/vn.svg" },
	{ country: "वालिस और फ़्यूचूना", img: "https://flagcdn.com/wf.svg" },
	{ country: "पश्चिमी सहारा", img: "https://flagcdn.com/eh.svg" },
	{ country: "यमन", img: "https://flagcdn.com/ye.svg" },
	{ country: "ज़ाम्बिया", img: "https://flagcdn.com/zm.svg" },
	{ country: "ज़िम्बाब्वे", img: "https://flagcdn.com/zw.svg" },
	{ country: "कोसोवो", img: "https://flagcdn.com/xk.svg" }
];