window.RECIPES_DB = [
  { name: "Kimchi Jjigae", ingredients: ["kimchi", "porc", "tofu", "oignon", "oignon vert", "ail", "piment en poudre", "gochujang", "sauce soja"] },
{ name: "Bibimbap", ingredients: ["riz", "bœuf", "épinards", "pousses de soja", "carotte", "courgette", "œuf", "gochujang", "algue nori"] },
{ name: "Bulgogi", ingredients: ["bœuf", "sauce soja", "oignon", "poire", "sucre", "huile de sésame", "ail", "oignon vert", "poivre"] },
{ name: "Japchae", ingredients: ["vermicelles de patate douce", "bœuf", "épinards", "carotte", "oignon", "champignons", "œuf", "sauce soja", "huile de sésame"] },
{ name: "Tteokbokki", ingredients: ["gâteau de riz", "odeng", "oignon", "oignon vert", "gochujang", "sucre", "sauce soja", "ail", "œuf dur"] },
{ name: "Sundubu Jjigae", ingredients: ["tofu soyeux", "porc", "œuf", "courgette", "oignon", "oignon vert", "ail", "piment en poudre", "sauce soja"] },
{ name: "Samgyeopsal", ingredients: ["poitrine de porc", "laitue", "ail", "ssamjang", "oignon vert", "sel", "poivre"] },
{ name: "Riz sauté au kimchi", ingredients: ["kimchi", "riz", "œuf", "porc", "oignon vert", "sauce soja", "huile de sésame"] },
{ name: "Galbijjim", ingredients: ["côtes de bœuf", "oignon", "carotte", "pomme de terre", "sauce soja", "sucre", "poire", "ail", "huile de sésame"] },
{ name: "Jajangmyeon", ingredients: ["nouilles", "porc", "oignon", "courgette", "pomme de terre", "chunjang", "concombre", "œuf"] },
{ name: "Sushi", ingredients: ["riz", "vinaigre", "sucre", "sel", "algue nori", "saumon", "thon", "crevette", "avocat", "concombre"] },
{ name: "Ramen", ingredients: ["nouilles", "porc", "œuf", "oignon vert", "menma", "algue nori", "sauce soja", "miso", "ail"] },
{ name: "Katsudon", ingredients: ["riz", "tonkatsu", "œuf", "oignon", "sauce soja", "sucre", "mirin"] },
{ name: "Okonomiyaki", ingredients: ["farine de blé", "œuf", "chou", "porc", "crevette", "oignon vert", "mayonnaise", "sauce okonomiyaki"] },
{ name: "Mapo tofu", ingredients: ["tofu", "porc haché", "oignon vert", "ail", "gingembre", "sauce soja", "doubanjiang", "poivre de Sichuan"] },
{ name: "Canard laqué de Pékin", ingredients: ["canard", "concombre", "oignon vert", "tianmianjiang", "crêpes fines"] },
{ name: "Porc aigre-doux", ingredients: ["porc", "ananas", "poivron", "oignon", "vinaigre", "sucre", "ketchup", "sauce soja"] },
{ name: "Pad Thaï", ingredients: ["nouilles de riz", "crevette", "œuf", "tofu", "pousses de soja", "cacahuètes", "tamarin", "sauce poisson", "citron vert"] },
{ name: "Tom Yum Kung", ingredients: ["crevette", "citronnelle", "citron vert", "galanga", "champignons", "piment", "sauce poisson", "coriandre"] },
{ name: "Phở", ingredients: ["nouilles de riz", "bœuf", "oignon", "gingembre", "cannelle", "clou de girofle", "sauce poisson", "pousses de soja", "citron vert", "basilic"] },
{ name: "Riz au poulet Hainan", ingredients: ["poulet", "riz", "gingembre", "ail", "concombre", "sauce soja", "sauce chili"] },
{ name: "Rouleaux de printemps frais", ingredients: ["galette de riz", "crevette", "porc", "laitue", "nouilles de riz", "menthe", "coriandre"] },
{ name: "Curry vert", ingredients: ["poulet", "pâte de curry vert", "lait de coco", "aubergine", "basilic", "sauce poisson", "sucre"] },
{ name: "Nasi Goreng", ingredients: ["riz", "poulet", "œuf", "sauce soja", "crevette", "oignon vert", "piment"] },
{ name: "Satay", ingredients: ["poulet", "cacahuètes", "sauce soja", "citronnelle", "ail", "curcuma"] },
{ name: "Laksa", ingredients: ["nouilles de riz", "crevette", "lait de coco", "tofu", "pousses de soja", "œuf", "piment", "coriandre"] },
{ name: "Chow Mein", ingredients: ["nouilles", "poulet", "pousses de soja", "chou", "carotte", "sauce soja", "oignon vert"] },
{ name: "Riz sauté", ingredients: ["riz", "œuf", "carotte", "petits pois", "oignon vert", "crevette", "sauce soja"] },
{ name: "Gyoza", ingredients: ["farine de blé", "chou", "porc", "ail", "gingembre", "oignon vert", "sauce soja"] },
{ name: "Unadon", ingredients: ["riz", "anguille", "sauce soja", "mirin", "sucre", "œuf"] },
{ name: "Hamburger", ingredients: ["bœuf", "pain", "laitue", "tomate", "oignon", "fromage", "cornichons"] },
{ name: "Cheeseburger", ingredients: ["bœuf", "pain", "fromage", "laitue", "tomate", "oignon", "cornichons"] },
{ name: "Poulet frit", ingredients: ["poulet", "farine de blé", "œuf", "huile", "sel", "poivre"] },
{ name: "Côtes levées BBQ", ingredients: ["côtes de porc", "sauce BBQ", "sucre brun", "sel", "poivre", "ail en poudre"] },
{ name: "Salade César", ingredients: ["laitue", "parmesan", "croûtons", "anchois", "œuf", "sauce César"] },
{ name: "Sandwich BLT", ingredients: ["pain", "bacon", "laitue", "tomate", "mayonnaise"] },
{ name: "Spaghettis à la carbonara", ingredients: ["spaghettis", "œuf", "parmesan", "lardons", "poivre"] },
{ name: "Lasagnes", ingredients: ["feuilles de lasagne", "bœuf haché", "sauce tomate", "ricotta", "mozzarella", "parmesan", "œuf"] },
{ name: "Pizza Margherita", ingredients: ["pâte à pizza", "sauce tomate", "mozzarella", "basilic", "huile d'olive"] },
{ name: "Paella", ingredients: ["riz", "crevette", "moules", "poulet", "chorizo", "petits pois", "safran", "paprika", "poivron"] },
{ name: "Croque-monsieur", ingredients: ["pain", "jambon", "fromage", "beurre", "lait", "farine de blé", "moutarde"] },
{ name: "Quiche Lorraine", ingredients: ["pâte brisée", "œuf", "lardons", "fromage", "crème", "oignon"] },
{ name: "Ratatouille", ingredients: ["aubergine", "courgette", "poivron", "tomate", "oignon", "ail"] },
{ name: "Bouillabaisse", ingredients: ["poisson", "moules", "crevette", "tomate", "ail", "oignon", "fenouil", "safran"] },
{ name: "Crêpe", ingredients: ["farine de blé", "œuf", "lait", "beurre", "sucre", "sel"] },
{ name: "Tortilla espagnole", ingredients: ["œuf", "pomme de terre", "oignon", "huile d'olive", "sel"] },
{ name: "Gaspacho", ingredients: ["tomate", "concombre", "poivron", "oignon", "ail", "huile d'olive", "vinaigre"] },
{ name: "Patatas bravas", ingredients: ["pomme de terre", "huile d'olive", "paprika", "tomate", "sauce aïoli"] },
{ name: "Churros", ingredients: ["farine de blé", "œuf", "beurre", "sucre", "sel", "huile", "cannelle"] },
{ name: "Salade niçoise au thon", ingredients: ["laitue", "thon", "œuf", "pomme de terre", "haricot vert", "olive", "tomate", "anchois"] },
{ name: "Tacos", ingredients: ["tortilla", "bœuf", "laitue", "tomate", "fromage", "oignon", "crème fraîche", "guacamole"] },
{ name: "Enchilada", ingredients: ["tortilla", "poulet", "fromage", "oignon", "sauce enchilada", "crème fraîche"] },
{ name: "Burrito", ingredients: ["tortilla", "riz", "haricots", "bœuf", "laitue", "fromage", "sauce"] },
{ name: "Ceviche", ingredients: ["poisson", "citron vert", "oignon", "piment", "coriandre", "tomate"] },
{ name: "Feijoada", ingredients: ["haricots noirs", "porc", "bœuf", "saucisse", "riz", "oignon", "ail"] },
{ name: "Empanada", ingredients: ["farine de blé", "bœuf", "oignon", "œuf", "olive", "raisins secs", "paprika"] },
{ name: "Moussaka", ingredients: ["aubergine", "pomme de terre", "bœuf haché", "tomate", "oignon", "sauce béchamel"] },
{ name: "Salade grecque", ingredients: ["tomate", "concombre", "olive", "feta", "oignon", "huile d'olive"] },
{ name: "Shakshuka", ingredients: ["œuf", "tomate", "poivron", "oignon", "ail", "cumin", "paprika"] },
{ name: "Falafel", ingredients: ["pois chiches", "oignon", "ail", "persil", "coriandre", "cumin", "farine de blé"] },
{ name: "Houmous", ingredients: ["pois chiches", "tahini", "ail", "citron", "huile d'olive"] },
{ name: "Shawarma", ingredients: ["poulet", "bœuf", "pain pita", "laitue", "tomate", "oignon", "yaourt", "ail"] },
{ name: "Couscous", ingredients: ["couscous", "poulet", "carotte", "courgette", "pois chiches", "oignon"] },
{ name: "Tajine", ingredients: ["agneau", "abricot", "amande", "oignon", "cannelle", "coriandre", "safran"] },
{ name: "Poulet au beurre", ingredients: ["poulet", "beurre", "crème", "tomate", "oignon", "garam masala"] },
{ name: "Poulet tandoori", ingredients: ["poulet", "yaourt", "garam masala", "cumin", "ail", "gingembre", "piment"] },
{ name: "Palak paneer", ingredients: ["épinards", "paneer", "crème", "oignon", "tomate", "ail", "cumin"] },
{ name: "Dal Tadka", ingredients: ["lentilles", "oignon", "tomate", "ail", "gingembre", "cumin", "curcuma", "ghee"] },
{ name: "Biryani", ingredients: ["riz", "poulet", "yaourt", "oignon", "garam masala", "safran"] },
{ name: "Samosa", ingredients: ["farine de blé", "pomme de terre", "petits pois", "oignon", "cumin", "coriandre"] },
{ name: "Fettuccine Alfredo", ingredients: ["fettuccine", "beurre", "crème", "parmesan"] },
{ name: "Poulet parmesan", ingredients: ["poulet", "œuf", "chapelure", "parmesan", "mozzarella", "sauce tomate"] },
{ name: "Bœuf Stroganoff", ingredients: ["bœuf", "oignon", "champignons", "crème aigre", "beurre", "farine de blé"] },
{ name: "Œufs Bénédicte", ingredients: ["œuf", "muffin anglais", "jambon", "sauce hollandaise", "beurre"] },
{ name: "Bisque de homard", ingredients: ["homard", "crème", "beurre", "oignon", "céleri", "carotte", "cognac"] },
{ name: "Clam chowder", ingredients: ["palourde", "pomme de terre", "oignon", "céleri", "bacon", "crème", "beurre"] },
{ name: "Tourte au poulet", ingredients: ["poulet", "carotte", "pomme de terre", "petits pois", "oignon", "pâte brisée", "crème"] },
{ name: "Pain de viande", ingredients: ["bœuf", "œuf", "chapelure", "oignon", "ketchup", "moutarde"] },
{ name: "Pain perdu", ingredients: ["pain", "œuf", "lait", "cannelle", "sucre", "beurre"] },
{ name: "Pancakes", ingredients: ["farine de blé", "œuf", "lait", "levure chimique", "sucre", "beurre"] },
{ name: "Gaufres", ingredients: ["farine de blé", "œuf", "lait", "levure chimique", "sucre", "beurre"] },
{ name: "Banana bread", ingredients: ["banane", "farine de blé", "œuf", "sucre", "beurre"] },
{ name: "Tarte aux pommes", ingredients: ["pomme", "farine de blé", "œuf", "sucre", "beurre", "cannelle"] },
{ name: "Tarte au citron", ingredients: ["citron", "œuf", "sucre", "beurre", "farine de blé"] },
{ name: "Brownie", ingredients: ["chocolat", "farine de blé", "œuf", "sucre", "beurre"] },
{ name: "Cheesecake", ingredients: ["fromage frais", "œuf", "sucre", "beurre", "biscuit graham"] },
{ name: "Soupe à la courge", ingredients: ["courge", "oignon", "ail", "crème", "beurre"] },
{ name: "Minestrone", ingredients: ["haricots", "carotte", "céleri", "oignon", "tomate", "pâtes"] },
{ name: "Omelette", ingredients: ["œuf", "lait", "fromage", "jambon", "oignon", "poivron"] },
{ name: "Œufs brouillés", ingredients: ["œuf", "lait", "beurre", "sel", "poivre"] },
{ name: "Quesadilla", ingredients: ["tortilla", "fromage", "poulet", "poivron", "oignon"] },
{ name: "Fajita", ingredients: ["bœuf", "oignon", "poivron", "tortilla", "crème fraîche"] },
{ name: "Porc effiloché", ingredients: ["porc", "sauce BBQ", "sucre brun", "oignon", "pain"] },
{ name: "Fish and chips", ingredients: ["poisson", "pomme de terre", "farine de blé", "œuf", "huile"] },
{ name: "Hachis parmentier", ingredients: ["agneau haché", "pomme de terre", "carotte", "oignon", "petits pois", "sauce gravy"] },
{ name: "Steak", ingredients: ["bœuf", "sel", "poivre", "beurre", "ail"] },
{ name: "Côtelette d’agneau", ingredients: ["agneau", "sel", "poivre", "ail", "romarin"] },
{ name: "Poulet rôti", ingredients: ["poulet", "sel", "poivre", "ail", "thym", "huile d'olive"] },
{ name: "Poulet au curry", ingredients: ["poulet", "oignon", "tomate", "ail", "gingembre", "poudre de curry", "lait de coco"] },
{ name: "Crevettes à l'ail", ingredients: ["crevette", "ail", "beurre", "citron", "persil", "spaghettis"] },
{ name: "Paella aux fruits de mer", ingredients: ["riz", "crevette", "moules", "calamar", "petits pois", "safran"] },
{ name: "Poulet cacciatore", ingredients: ["poulet", "tomate", "oignon", "poivron", "champignons", "ail"] },
{ name: "Bœuf bourguignon", ingredients: ["bœuf", "vin rouge", "oignon", "carotte", "céleri", "ail", "thym"] },
{ name: "Goulash", ingredients: ["bœuf", "oignon", "paprika", "tomate", "poivron", "ail"] },
{ name: "Bortsch", ingredients: ["betterave", "chou", "pomme de terre", "carotte", "oignon", "aneth"] },
{ name: "Pierogi", ingredients: ["farine de blé", "œuf", "pomme de terre", "fromage", "oignon", "beurre"] },
{ name: "Baklava", ingredients: ["pâte filo", "noix", "pistache", "sucre", "beurre", "miel"] },
{ name: "Dolma", ingredients: ["feuille de vigne", "riz", "oignon", "pignon", "aneth"] },
{ name: "Chou farci", ingredients: ["chou", "bœuf", "riz", "oignon", "sauce tomate"] },
{ name: "Ragoût irlandais", ingredients: ["agneau", "pomme de terre", "carotte", "oignon", "céleri"] },
{ name: "Cassoulet", ingredients: ["haricots blancs", "porc", "canard", "saucisse", "oignon", "ail"] },
{ name: "Börek", ingredients: ["pâte filo", "fromage", "pomme de terre", "œuf", "sésame"] },
{ name: "Sauerbraten", ingredients: ["bœuf", "oignon", "carotte", "céleri", "vinaigre", "gingembre"] },
{ name: "Wiener Schnitzel", ingredients: ["veau", "œuf", "farine de blé", "chapelure", "citron"] },
{ name: "Zwiebelrostbraten", ingredients: ["bœuf", "oignon", "beurre", "farine de blé", "bouillon de bœuf"] },
{ name: "Rösti", ingredients: ["pomme de terre", "beurre", "oignon", "bacon"] },
{ name: "Spätzle", ingredients: ["farine de blé", "œuf", "lait", "beurre"] },
{ name: "Soupe goulash", ingredients: ["bœuf", "oignon", "paprika", "pomme de terre", "carotte"] },
{ name: "Poulet Kiev", ingredients: ["poulet", "beurre", "ail", "persil", "œuf", "farine de blé", "chapelure"] },
{ name: "Plov", ingredients: ["riz", "bœuf", "carotte", "oignon", "cumin"] },
{ name: "Manti", ingredients: ["farine de blé", "œuf", "bœuf", "oignon", "yaourt"] },
{ name: "Nouilles de Pékin", ingredients: ["nouilles", "porc", "œuf", "oignon vert", "sauce soja"] },
{ name: "Riz Jollof", ingredients: ["riz", "tomate", "oignon", "poivron", "piment", "ail"] },
{ name: "Bobotie", ingredients: ["bœuf", "pain", "œuf", "oignon", "lait", "poudre de curry"] },
{ name: "Bunny Chow", ingredients: ["pain", "poulet", "oignon", "tomate", "poudre de curry"] },
{ name: "Chakalaka", ingredients: ["haricots", "oignon", "tomate", "piment", "carotte", "poivron"] },
{ name: "Pav Bhaji", ingredients: ["pain", "pomme de terre", "petits pois", "carotte", "oignon", "tomate", "beurre"] },
{ name: "Vada Pav", ingredients: ["pain", "pomme de terre", "piment", "coriandre", "ail", "graine de moutarde"] },
{ name: "Masala Dosa", ingredients: ["riz", "lentilles", "pomme de terre", "oignon", "graine de moutarde", "feuille de curry"] },
{ name: "Idli", ingredients: ["riz", "lentilles", "sel"] },
{ name: "Sambar", ingredients: ["lentilles", "carotte", "oignon", "tomate", "aubergine", "gombo", "mélange d'épices"] },
{ name: "Katsu curry", ingredients: ["riz", "tonkatsu", "sauce curry", "oignon", "carotte", "pomme de terre"] },
{ name: "Takoyaki", ingredients: ["farine de blé", "œuf", "pieuvre", "oignon vert", "tenkasu", "mayonnaise", "sauce takoyaki"] },
{ name: "Sukiyaki", ingredients: ["bœuf", "tofu", "oignon vert", "shiitake", "shirataki", "œuf"] },
{ name: "Nabe", ingredients: ["chou", "tofu", "shiitake", "carotte", "poulet", "udon"] },
{ name: "Soupe aux œufs", ingredients: ["œuf", "bouillon de poulet", "fécule de pomme de terre", "oignon vert", "sauce soja"] },
{ name: "Soupe aigre-piquante", ingredients: ["tofu", "œuf", "champignons", "menma", "vinaigre", "sauce soja", "poivre"] },
{ name: "Bœuf sauté au brocoli", ingredients: ["bœuf", "brocoli", "sauce soja", "ail", "gingembre", "oignon"] },
{ name: "Poulet au citron", ingredients: ["poulet", "citron", "œuf", "farine de blé", "sauce soja", "sucre"] },
{ name: "Riz sauté à l’ananas", ingredients: ["riz", "ananas", "crevette", "œuf", "noix de cajou", "oignon vert"] },
{ name: "Bánh mì", ingredients: ["baguette", "porc", "carotte", "concombre", "coriandre", "mayonnaise", "pâté"] },
{ name: "Khao Soi", ingredients: ["nouilles aux œufs", "poulet", "lait de coco", "pâte de curry", "légumes marinés"] },
{ name: "Bak Kut Teh", ingredients: ["côtes de porc", "ail", "sauce soja", "poivre blanc", "champignons"] },
{ name: "Laksa de Singapour", ingredients: ["nouilles de riz", "crevette", "lait de coco", "tofu", "pousses de soja", "œuf", "piment", "coriandre"] },
{ name: "Gado-gado", ingredients: ["légumes", "tofu", "œuf", "sauce aux cacahuètes", "pousses de soja"] },
{ name: "Nasi Lemak", ingredients: ["riz", "lait de coco", "œuf", "ikan bilis", "cacahuètes", "concombre", "sauce sambal"] },
{ name: "Pâtes au pesto de roquette", ingredients: ["roquette", "pâtes", "parmesan", "huile d'olive", "pignon"] },
{ name: "Shakshuka au feta", ingredients: ["œuf", "tomate", "poivron", "oignon", "feta", "coriandre"] },
{ name: "Pancakes au babeurre", ingredients: ["farine de blé", "œuf", "babeurre", "sucre", "levure chimique"] },
{ name: "Salade de quinoa", ingredients: ["quinoa", "concombre", "tomate", "feta", "citron", "huile d'olive"] },
{ name: "Salade César au chou kale", ingredients: ["chou kale", "parmesan", "croûtons", "anchois", "œuf", "sauce César"] },
{ name: "Buddha bowl vegan", ingredients: ["riz complet", "pois chiches", "avocat", "épinards", "carotte", "tofu"] },
{ name: "Aubergines à la parmesane", ingredients: ["aubergine", "sauce tomate", "mozzarella", "parmesan", "basilic"] },
{ name: "Poivrons farcis", ingredients: ["poivron", "riz", "bœuf haché", "oignon", "tomate", "fromage"] },
{ name: "Côtelette d’agneau rôtie", ingredients: ["agneau", "ail", "romarin", "huile d'olive", "sel", "poivre"] },
{ name: "Soupe de lentilles", ingredients: ["lentilles", "carotte", "céleri", "oignon", "tomate", "ail"] },
{ name: "Choux de Bruxelles rôtis", ingredients: ["choux de Bruxelles", "huile d'olive", "sel", "poivre", "citron"] },
{ name: "Poulet au pesto", ingredients: ["poulet", "pesto au basilic", "parmesan", "huile d'olive"] },
{ name: "Sauce mangue", ingredients: ["mangue", "oignon", "citron vert", "coriandre", "piment"] },
{ name: "Cabillaud rôti", ingredients: ["cabillaud", "citron", "huile d'olive", "persil", "chapelure"] },
{ name: "Coleslaw asiatique", ingredients: ["chou chinois", "carotte", "oignon vert", "sauce soja", "vinaigre de riz", "huile de sésame"] },
{ name: "Salade de nouilles aux cacahuètes", ingredients: ["nouilles", "cacahuètes", "carotte", "concombre", "sauce soja", "huile de sésame"] },
{ name: "Chili vegan", ingredients: ["haricots noirs", "tomate", "oignon", "poudre de chili", "maïs", "poivron"] },
{ name: "Tacos au jackfruit", ingredients: ["jackfruit", "tortilla", "chou", "citron vert", "avocat", "coriandre"] },
{ name: "Tofu sauté aux légumes", ingredients: ["tofu", "brocoli", "poivron", "sauce soja", "gingembre", "ail"] },
{ name: "Risotto à la courge", ingredients: ["courge", "riz", "parmesan", "oignon", "ail"] },
{ name: "Tartine de ratatouille", ingredients: ["aubergine", "courgette", "poivron", "oignon", "pain"] },
{ name: "Salade de betterave", ingredients: ["betterave", "roquette", "noix", "fromage de chèvre", "vinaigre balsamique"] },
{ name: "Tajine marocain", ingredients: ["agneau", "abricot", "amande", "oignon", "cannelle", "coriandre", "safran"] },
{ name: "Steak au chimichurri", ingredients: ["bœuf", "persil", "ail", "huile d'olive", "origan", "vinaigre"] },
{ name: "Beignets de courgette", ingredients: ["courgette", "œuf", "farine de blé", "parmesan", "oignon vert"] },
{ name: "Soupe miso", ingredients: ["miso", "tofu", "wakame", "oignon vert", "bouillon dashi"] },
{ name: "Wrap de falafel", ingredients: ["falafel", "pain pita", "laitue", "tomate", "tahini"] },
{ name: "Laksa aux crevettes", ingredients: ["crevette", "nouilles de riz", "lait de coco", "pâte de laksa", "œuf", "pousses de soja"] },
{ name: "Bowl de couscous", ingredients: ["couscous", "pois chiches", "carotte", "courgette", "citron"] },
{ name: "Poulet frit coréen sucré", ingredients: ["poulet", "gochujang", "sauce soja", "sucre", "sirop de maïs", "ail", "gingembre", "mélange à frire"] },
{ name: "Budae Jjigae", ingredients: ["jambon", "saucisse", "kimchi", "tofu", "pousses de soja", "ramen", "gochujang", "piment en poudre", "oignon vert"] },
{ name: "Soupe de côtes de bœuf", ingredients: ["côte de bœuf", "radis blanc", "oignon vert", "ail", "gingembre", "sauce soja", "vermicelles de patate douce"] },
{ name: "Crêpe coréenne aux fruits de mer", ingredients: ["calamar", "crevette", "oignon vert", "farine de blé", "œuf", "eau", "sauce soja", "vinaigre"] },
{ name: "Yukgaejang", ingredients: ["bœuf", "fougère", "pousses de soja", "tige de taro", "oignon vert", "piment en poudre", "sauce soja", "ail"] },
{ name: "Bossam", ingredients: ["porc", "ail", "gingembre", "oignon vert", "miso", "sauce de crevettes fermentées", "kimchi de radis", "chou chinois"] },
{ name: "Samgyetang", ingredients: ["poulet", "ginseng", "jujube", "ail", "riz gluant", "oignon vert", "sel"] },
{ name: "Jjimdak", ingredients: ["poulet", "pomme de terre", "carotte", "oignon", "oignon vert", "vermicelles de patate douce", "sauce soja", "sucre", "ail"] },
{ name: "Bibim guksu", ingredients: ["nouilles", "gochujang", "vinaigre", "sucre", "concombre", "laitue", "œuf", "huile de sésame"] },
{ name: "Kimbap", ingredients: ["riz", "algue nori", "takuwan", "épinards", "carotte", "œuf", "jambon", "odeng", "huile de sésame"] },
{ name: "Jeyuk bokkeum", ingredients: ["porc", "gochujang", "piment en poudre", "sauce soja", "sucre", "ail", "oignon", "oignon vert"] },
{ name: "Dakbokkeumtang", ingredients: ["poulet", "pomme de terre", "carotte", "oignon", "oignon vert", "gochujang", "piment en poudre", "ail"] },
{ name: "Doenjang jjigae", ingredients: ["miso coréen", "tofu", "courgette", "oignon", "oignon vert", "champignons", "piment", "bouillon d'anchois"] },
{ name: "Agujjim", ingredients: ["lotte", "pousses de soja", "midodok", "seri", "piment en poudre", "ail", "sauce soja", "fécule de pomme de terre"] },
{ name: "Gopchang jeongol", ingredients: ["tripes de bœuf", "oignon vert", "oignon", "feuille de pérille", "champignons", "tofu", "piment en poudre", "ail haché", "bouillon"] },
{ name: "Poulet frit coréen épicé", ingredients: ["poulet", "gochujang", "sirop de maïs", "ketchup", "ail", "sauce soja", "cacahuètes", "mélange à frire"] },
{ name: "Gukbap", ingredients: ["riz", "porc", "abats", "oignon vert", "ail", "piment en poudre", "boudin coréen"] },
{ name: "Pâtes aglio e olio", ingredients: ["spaghettis", "ail", "huile d'olive", "piment", "persil"] },
{ name: "Pâtes alle vongole", ingredients: ["spaghettis", "palourdes", "ail", "huile d'olive", "vin blanc", "persil"] },
{ name: "Crevettes à l'ail", ingredients: ["crevette", "ail", "huile d'olive", "piment", "baguette"] },
{ name: "Steak sauce", ingredients: ["bœuf", "poivron", "oignon", "champignons", "sauce soja", "ketchup", "sucre", "sauce steak"] },
{ name: "Salade à la ricotta", ingredients: ["ricotta", "jeunes pousses", "vinaigrette balsamique", "tomate", "noix"] },
{ name: "Galettes de pomme de terre coréennes", ingredients: ["pomme de terre", "oignon", "préparation pour galettes", "eau", "sel", "huile"] },
{ name: "Maquereau grillé", ingredients: ["maquereau", "sel", "poivre", "citron", "huile"] },
{ name: "Sauté de petit poulpe", ingredients: ["petit poulpe", "oignon", "oignon vert", "chou", "gochujang", "piment en poudre", "ail", "sucre"] },
{ name: "Sauté de pattes de poulet", ingredients: ["pattes de poulet", "gochujang", "piment en poudre", "ail", "oignon", "oignon vert", "sucre", "sirop de maïs"] },
{ name: "Glace", ingredients: ["lait", "sucre", "jaune d'œuf", "crème", "vanille"] },
{ name: "Tiramisu", ingredients: ["mascarpone", "biscuits à la cuillère", "café", "sucre", "jaune d'œuf", "cacao en poudre"] },
{ name: "Macaron", ingredients: ["poudre d'amande", "sucre glace", "blanc d'œuf", "sucre", "colorant alimentaire"] },
{ name: "Croffle", ingredients: ["pâte à croissant", "gaufrier", "sucre", "beurre"] },
{ name: "Tartelette aux œufs", ingredients: ["pâte à tarte", "œuf", "lait", "sucre", "crème", "extrait de vanille"] },
{ name: "Pain à l'anko et au beurre", ingredients: ["pain", "pâte de haricots rouges", "beurre"] },
{ name: "Hotteok", ingredients: ["farine de blé", "sucre", "levure", "eau", "graines", "miel"] },
{ name: "Bungeoppang", ingredients: ["farine de blé", "œuf", "lait", "sucre", "pâte de haricots rouges", "beurre"] },
{ name: "Hot-dog", ingredients: ["saucisse", "pain", "ketchup", "moutarde", "oignon", "cornichons"] },
{ name: "Soupe à l’oignon", ingredients: ["oignon", "bouillon de bœuf", "pain", "fromage", "beurre", "farine de blé"] },
{ name: "Spaghettis aux boulettes", ingredients: ["spaghettis", "bœuf haché", "sauce tomate", "oignon", "ail", "chapelure", "œuf"] },
{ name: "Tacos au poisson", ingredients: ["poisson", "tortilla", "chou", "sauce", "citron vert", "coriandre"] },
{ name: "Scone au fromage", ingredients: ["farine de blé", "beurre", "lait", "fromage", "levure chimique"] },
{ name: "Muffin aux myrtilles", ingredients: ["farine de blé", "myrtille", "sucre", "œuf", "lait", "huile", "levure chimique"] },
];

window.INGREDIENTS_DB = [
  "œuf", "poulet", "bœuf", "porc", "oignon", "ail", "carotte", "pomme de terre", "spaghettis", "riz", "tomate", "laitue",
"tofu", "pousses de soja", "cacahuètes", "vin rouge", "miso", "algue nori", "kimchi", "bacon", "parmesan", "anchois", "pain",
"fromage", "crevette", "citronnelle", "galanga", "citron vert", "poivron", "aubergine", "courgette", "croûtons", "bouillon dashi",
"poitrine de porc", "poivre", "champignons", "yaourt", "farine de blé", "sucre", "sel", "beurre", "lait", "crème", "concombre",
"pomme", "banane", "orange", "citron", "brocoli", "épinards", "courge", "patate douce", "maïs", "petits pois",
"chou", "céleri", "gingembre", "sauce soja", "vinaigre", "huile d'olive", "huile de colza", "huile de tournesol", "huile de sésame",
"sauce de poisson", "sauce d’huître", "tianmianjiang (pâte de haricots douce)", "ketchup", "moutarde", "mayonnaise", "basilic", "coriandre", "persil",
"romarin", "thym", "sauge", "menthe", "cannelle", "noix de muscade", "clou de girofle", "laurier", "anis étoilé", "cardamome",
"curry en poudre", "poudre de chili", "paprika", "curcuma", "cumin", "graine de coriandre", "aneth", "fenouil", "vanille",
"chocolat", "cacao en poudre", "confiture", "miel", "sirop d’érable", "mélasse", "fraise", "myrtille", "framboise",
"canneberge", "mûre", "ananas", "mangue", "kiwi", "raisin", "poire", "pêche", "abricot", "prune", "jujube",
"figue", "noix de coco", "noix", "amande", "noisette", "noix de cajou", "pistache", "macadamia", "pecan", "graine de tournesol",
"graine de chia", "graine de courge", "sésame", "quinoa", "orge", "millet", "sarrasin", "avoine", "pain", "pâtes",
"nouilles", "tortilla", "naan", "pita", "pain au levain", "bagel", "croissant", "donut", "pâte à pizza", "biscuit salé",
"saucisse", "salami", "jambon", "canard", "agneau", "dinde", "lapin", "veau", "oie", "anchois", "sardine", "thon",
"maquereau", "saumon", "cabillaud", "aiglefin", "merlan", "poisson-chat", "tilapia", "calamar", "poulpe", "palourde", "moule",
"coquille Saint-Jacques", "homard", "crabe", "écrevisse", "ormeau", "concombre de mer", "oursin", "wasabi", "raifort",
"tabasco", "sauce sriracha", "gochujang", "ssamjang", "miso", "haricot rouge", "haricot noir", "haricot",
"pois chiche", "lentille", "haricot", "haricot blanc", "haricot vert", "pois mange-tout", "edamame", "mozzarella",
"cheddar", "gouda", "brie", "camembert", "feta", "bleu", "emmental", "provolone", "ricotta",
"mascarpone", "fromage frais", "cottage cheese", "crème aigre", "yaourt", "babeurre", "lait concentré",
"lait concentré sucré", "lait en poudre", "lait d’amande", "lait de soja", "lait de riz", "lait de coco", "lait d’avoine",
"pâte de crevette", "pâte d’anchois", "pâte de tomate", "sauce tomate", "pesto", "sauce piquante", "harissa", "ajvar",
"tahini", "houmous", "guacamole", "salsa", "relish", "tapenade", "sauce gravy", "bouillon", "gélatine",
"agar-agar", "fécule de pomme de terre", "tapioca", "arrow-root", "farine de riz", "semoule", "farine de maïs",
"polenta", "germe de blé", "son de blé", "feuille de riz", "feuille de rouleau de printemps", "algue nori", "gâteau de riz", "udon", "ramen",
"vermicelles", "sarrasin", "fettuccine", "penne", "macaroni", "lasagnes", "spaghettis", "linguine", "capellini",
"gnocchi", "ravioli", "tortellini", "gyoza", "wonton", "pierogi", "empanada", "tamal", "oignon vert",
"échalote", "poireau", "navet", "radis", "panais", "rutabaga", "betterave", "chou-rave", "radis blanc (daikon)", "jicama", "racine de lotus",
"artichaut", "asperge", "gombo", "pousse de bambou (menma)", "jaune d’œuf", "blanc d’œuf", "œuf de caille", "œuf de canard", "œuf d’oie",
"truffe", "morille", "cèpe", "enoki", "shiitake", "pleurote", "champignon de Paris", "portobello",
"châtaigne", "sagittaire", "taro", "igname", "manioc", "salsifis", "topinambour", "fenouil (bulbe)",
"roquette", "pesto au basilic", "poivron", "bok choy", "choux de Bruxelles", "babeurre", "câpre",
"caramel", "carvi", "noix de cajou", "chia", "huile de piment", "ciboulette", "graine de coriandre", "cottage cheese",
"crabe", "canneberge", "crème", "cresson", "pissenlit", "datte", "feuille de rouleau d’œuf", "épeautre", "fenugrec",
"feta", "beurre de cacahuète", "fromage de chèvre", "haricot vert", "goyave", "noisette", "graine de chanvre", "mélange d’herbes",
"jacquier", "chou kale", "jus de kimchi", "kumquat", "poireau", "pâtes de lentilles", "litchi", "chutney de mangue",
"manchego", "bacon fumé à l’érable", "marjolaine", "mizuna", "fruit du moine", "sauce aux champignons", "moutarde verte",
"chou chinois", "nectarine", "gombo", "olive", "zeste d’orange", "papaye", "fruit de la passion", "pousse de pois",
"noix de pécan", "fromage pepper jack", "kaki", "pignon", "crème de pistache", "tomate cerise", "pop-corn", "prosciutto",
"pain pumpernickel", "quark", "chicorée", "ras el-hanout", "lentille corail", "ricotta salée", "roquette", "laitue romaine",
"roquefort", "eau de rose", "rutabaga", "sago", "salsifis", "chou de Savoie", "ciboule", "échalote",
"shiso", "tofu soyeux", "saumon fumé", "pois mange-tout", "oseille", "protéine de soja", "épeautre",
"encre de seiche", "stilton", "nameko", "sumac", "tomate séchée", "maïs doux", "bette",
"tamarin", "tempeh", "thym", "sésame grillé", "yuba", "tomate", "huile de truffe", "feuille de navet",
"orange de Valence", "fromage vegan", "gibier", "vermicelles", "riz vinaigré", "cresson", "farine de blé",
"chocolat blanc", "riz sauvage", "igname", "zaatar", "zeste", "fleur de courgette", "haricot rouge", "amarante",
"anis", "pousse de bambou", "poivron banane", "graine de basilic", "petite coquille Saint-Jacques", "ail noir", "orange sanguine",
"bourrache", "bresaola", "cactus", "calamar", "melon jaune", "gingembre confit", "feuille de carotte", "farine de manioc",
"céleri", "chayotte", "shimeji", "chorizo", "mûre arctique", "sucre de coco", "ail confit",
"salade de maïs", "haricot cranberry", "champignon crémini", "dolma", "edamame", "fougère", "œufs de poisson", "frisée", "garam masala",
"ciboule d’ail", "baies de goji", "betterave jaune", "ail jeune", "guanciale", "pied de porc", "racine de raifort",
"topinambour", "kabosu", "réglisse", "algue kombu", "lardon", "lavande", "limoncello", "haricot long",
"graine de lotus", "caramel au miso", "mitraille", "mûre", "muscat", "capucine", "ortie", "feuille d’okra",
"olive noire", "feuille de panais", "pattypan", "pecorino", "melon amer", "feuille de pérille", "cornichon",
"haricot", "sauge ananas", "poivre rose", "pruneau", "piment poblano", "pourpier", "coing", "ail des ours",
"rhubarbe", "ail rôti", "romanesco", "haricot", "feuille de rutabaga", "œufs de saumon", "patate douce", "salicorne",
"jambon", "saucisse", "ramen", "radis blanc (daikon)", "ciboule", "calamar", "midodok", "céleri japonais", "tige de taro", "fougère", "pâte de crevette salée",
"ginseng", "jujube", "riz gluant", "fécule de pomme de terre", "abats de bœuf", "feuille de pérille", "soupe", "sirop de malt", "lotte",
"boudin noir", "peperoncino", "baguette", "vin blanc", "sauce pour steak", "jeunes pousses", "vinaigrette balsamique", "fruits à coque",
"préparation pour jeon", "maquereau", "petit poulpe", "chou", "patte de poulet", "poudre d’amande", "sucre glace", "colorant alimentaire",
"pâte à croissant", "gaufrier", "pâte à tarte", "extrait de vanille", "pâte de haricots rouges", "levure", "graine", "miel", "pâte de haricots rouges",
"saucisse", "huile", "levure chimique"

];
