window.RECIPES_DB = [
  { name: "Jjigae de Kimchi", ingredients: ["kimchi", "porco", "tofu", "cebola", "cebolinha", "alho", "pimenta em pó", "gochujang", "molho de soja"] },
  { name: "Bibimbap", ingredients: ["arroz", "carne bovina", "espinafre", "brotos de soja", "cenoura", "abobrinha", "ovo", "gochujang", "alga nori"] },
  { name: "Bulgogi", ingredients: ["carne bovina", "molho de soja", "cebola", "pêra", "açúcar", "óleo de gergelim", "alho", "cebolinha", "pimenta"] },
  { name: "Japchae", ingredients: ["macarrão de batata-doce", "carne bovina", "espinafre", "cenoura", "cebola", "cogumelos", "ovo", "molho de soja", "óleo de gergelim"] },
  { name: "Tteokbokki", ingredients: ["bolo de arroz", "odeng", "cebola", "cebolinha", "gochujang", "açúcar", "molho de soja", "alho", "ovo cozido"] },
  { name: "Sundubu Jjigae", ingredients: ["tofu macio", "porco", "ovo", "abobrinha", "cebola", "cebolinha", "alho", "pimenta em pó", "molho de soja"] },
  { name: "Samgyeopsal", ingredients: ["panceta de porco", "alface", "alho", "ssamjang", "cebolinha", "sal", "pimenta"] },
  { name: "Arroz frito com kimchi", ingredients: ["kimchi", "arroz", "ovo", "porco", "cebolinha", "molho de soja", "óleo de gergelim"] },
  { name: "Galbijjim", ingredients: ["costela bovina", "cebola", "cenoura", "batata", "molho de soja", "açúcar", "pêra", "alho", "óleo de gergelim"] },
  { name: "Jajangmyeon", ingredients: ["macarrão", "porco", "cebola", "abobrinha", "batata", "chunjang", "pepino", "ovo"] },
  { name: "Sushi", ingredients: ["arroz", "vinagre", "açúcar", "sal", "alga nori", "salmão", "atum", "camarão", "abacate", "pepino"] },
  { name: "Ramen", ingredients: ["macarrão", "porco", "ovo", "cebolinha", "menma", "alga nori", "molho de soja", "missô", "alho"] },
  { name: "Katsudon", ingredients: ["arroz", "tonkatsu", "ovo", "cebola", "molho de soja", "açúcar", "mirin"] },
  { name: "Okonomiyaki", ingredients: ["farinha de trigo", "ovo", "repolho", "porco", "camarão", "cebolinha", "maionese", "molho okonomiyaki"] },
  { name: "Mapo tofu", ingredients: ["tofu", "carne suína moída", "cebolinha", "alho", "gengibre", "molho de soja", "doubanjiang", "pimenta de Sichuan"] },
  { name: "Pato de Pequim", ingredients: ["pato", "pepino", "cebolinha", "tianmianjiang", "crepes finos"] },
  { name: "Porco agridoce", ingredients: ["porco", "abacaxi", "pimentão", "cebola", "vinagre", "açúcar", "ketchup", "molho de soja"] },
  { name: "Pad Thai", ingredients: ["macarrão de arroz", "camarão", "ovo", "tofu", "brotos de soja", "amendoim", "tamarindo", "molho de peixe", "lima"] },
  { name: "Tom Yum Kung", ingredients: ["camarão", "capim-limão", "lima", "galanga", "cogumelos", "pimenta", "molho de peixe", "coentro"] },
  { name: "Pho", ingredients: ["macarrão de arroz", "carne bovina", "cebola", "gengibre", "canela", "cravo", "molho de peixe", "brotos de soja", "lima", "manjericão"] },
  { name: "Arroz com frango Hainan", ingredients: ["frango", "arroz", "gengibre", "alho", "pepino", "molho de soja", "molho de pimenta"] },
  { name: "Rolinhos primavera frescos", ingredients: ["papel de arroz", "camarão", "porco", "alface", "macarrão de arroz", "hortelã", "coentro"] },
  { name: "Curry verde", ingredients: ["frango", "pasta de curry verde", "leite de coco", "berinjela", "manjericão", "molho de peixe", "açúcar"] },
  { name: "Nasi Goreng", ingredients: ["arroz", "frango", "ovo", "molho de soja", "camarão", "cebolinha", "pimenta"] },
  { name: "Satay", ingredients: ["frango", "amendoim", "molho de soja", "capim-limão", "alho", "açafrão"] },
  { name: "Laksa", ingredients: ["macarrão de arroz", "camarão", "leite de coco", "tofu", "brotos de soja", "ovo", "pimenta", "coentro"] },
  { name: "Chow Mein", ingredients: ["macarrão", "frango", "brotos de soja", "repolho", "cenoura", "molho de soja", "cebolinha"] },
  { name: "Arroz frito", ingredients: ["arroz", "ovo", "cenoura", "ervilhas", "cebolinha", "camarão", "molho de soja"] },
  { name: "Gyoza", ingredients: ["farinha de trigo", "repolho", "porco", "alho", "gengibre", "cebolinha", "molho de soja"] },
  { name: "Unadon", ingredients: ["arroz", "enguia", "molho de soja", "mirin", "açúcar", "ovo"] },
  { name: "Hambúrguer", ingredients: ["carne bovina", "pão", "alface", "tomate", "cebola", "queijo", "picles"] },
  { name: "Hambúrguer com queijo", ingredients: ["carne bovina", "pão", "queijo", "alface", "tomate", "cebola", "picles"] },
  { name: "Frango frito", ingredients: ["frango", "farinha de trigo", "ovo", "óleo", "sal", "pimenta"] },
  { name: "Costelas BBQ", ingredients: ["costelas de porco", "molho BBQ", "açúcar mascavo", "sal", "pimenta", "alho em pó"] },
  { name: "Salada Caesar", ingredients: ["alface", "queijo parmesão", "croutons", "anchova", "ovo", "molho Caesar"] },
  { name: "Sanduíche BLT", ingredients: ["pão", "bacon", "alface", "tomate", "maionese"] },
  { name: "Espaguete à carbonara", ingredients: ["espaguete", "ovo", "queijo parmesão", "panceta", "pimenta"] },
  { name: "Lasanha", ingredients: ["massa de lasanha", "carne bovina moída", "molho de tomate", "queijo ricota", "mussarela", "queijo parmesão", "ovo"] },
  { name: "Pizza Margherita", ingredients: ["massa de pizza", "molho de tomate", "mussarela", "manjericão", "azeite de oliva"] },
  { name: "Paella", ingredients: ["arroz", "camarão", "mexilhões", "frango", "chouriço", "ervilhas", "açafrão", "pimentão doce", "pimentão"] },
  { name: "Croque Monsieur", ingredients: ["pão", "presunto", "queijo", "manteiga", "leite", "farinha de trigo", "mostarda"] },
  { name: "Quiche Lorraine", ingredients: ["massa de torta", "ovo", "bacon", "queijo", "nata", "cebola"] },
  { name: "Ratatouille", ingredients: ["berinjela", "abobrinha", "pimentão", "tomate", "cebola", "alho"] },
  { name: "Bouillabaisse", ingredients: ["peixe", "mexilhões", "camarão", "tomate", "alho", "cebola", "funcho", "açafrão"] },
  { name: "Crepe", ingredients: ["farinha de trigo", "ovo", "leite", "manteiga", "açúcar", "sal"] },
  { name: "Tortilla espanhola", ingredients: ["ovo", "batata", "cebola", "azeite de oliva", "sal"] },
  { name: "Gazpacho", ingredients: ["tomate", "pepino", "pimentão", "cebola", "alho", "azeite de oliva", "vinagre"] },
  { name: "Batatas bravas", ingredients: ["batata", "azeite de oliva", "pimentão doce", "tomate", "molho aioli"] },
  { name: "Churros", ingredients: ["farinha de trigo", "ovo", "manteiga", "açúcar", "sal", "óleo", "canela"] },
  { name: "Salada Niçoise com atum", ingredients: ["alface", "atum", "ovo", "batata", "vagem", "azeitona", "tomate", "anchova"] },
  { name: "Tacos", ingredients: ["tortilla", "carne bovina", "alface", "tomate", "queijo", "cebola", "creme azedo", "guacamole"] },
  { name: "Enchilada", ingredients: ["tortilla", "frango", "queijo", "cebola", "molho enchilada", "creme azedo"] },
  { name: "Burrito", ingredients: ["tortilla", "arroz", "feijão", "carne bovina", "alface", "queijo", "molho"] },
  { name: "Ceviche", ingredients: ["peixe", "lima", "cebola", "pimenta", "coentro", "tomate"] },
  { name: "Feijoada", ingredients: ["feijão preto", "porco", "carne bovina", "linguiça", "arroz", "cebola", "alho"] },
  { name: "Empanada", ingredients: ["farinha de trigo", "carne bovina", "cebola", "ovo", "azeitona", "passas", "pimentão doce"] },
  { name: "Moussaka", ingredients: ["berinjela", "batata", "carne bovina moída", "tomate", "cebola", "molho bechamel"] },
  { name: "Salada grega", ingredients: ["tomate", "pepino", "azeitona", "queijo feta", "cebola", "azeite de oliva"] },
  { name: "Shakshuka", ingredients: ["ovo", "tomate", "pimentão", "cebola", "alho", "cominho", "pimentão doce"] },
  { name: "Falafel", ingredients: ["grão-de-bico", "cebola", "alho", "salsa", "coentro", "cominho", "farinha de trigo"] },
  { name: "Hummus", ingredients: ["grão-de-bico", "tahine", "alho", "limão", "azeite de oliva"] },
  { name: "Shawarma", ingredients: ["frango", "carne bovina", "pão pita", "alface", "tomate", "cebola", "iogurte", "alho"] },
  { name: "Cuscuz", ingredients: ["cuscuz", "frango", "cenoura", "abobrinha", "grão-de-bico", "cebola"] },
  { name: "Tajine", ingredients: ["cordeiro", "damasco", "amêndoa", "cebola", "canela", "coentro", "açafrão"] },
  { name: "Frango com manteiga", ingredients: ["frango", "manteiga", "nata", "tomate", "cebola", "garam masala"] },
  { name: "Frango tandoori", ingredients: ["frango", "iogurte", "garam masala", "cominho", "alho", "gengibre", "pimenta"] },
  { name: "Palak paneer", ingredients: ["espinafre", "paneer", "nata", "cebola", "tomate", "alho", "cominho"] },
  { name: "Dal Tadka", ingredients: ["lentilhas", "cebola", "tomate", "alho", "gengibre", "cominho", "açafrão", "ghee"] },
  { name: "Biryani", ingredients: ["arroz", "frango", "iogurte", "cebola", "garam masala", "açafrão"] },
  { name: "Samosa", ingredients: ["farinha de trigo", "batata", "ervilhas", "cebola", "cominho", "coentro"] },
  { name: "Fettuccine Alfredo", ingredients: ["fettuccine", "manteiga", "nata", "queijo parmesão"] },
  { name: "Frango à parmegiana", ingredients: ["frango", "ovo", "farinha de rosca", "queijo parmesão", "mussarela", "molho de tomate"] },
  { name: "Strogonoff de carne", ingredients: ["carne bovina", "cebola", "cogumelos", "creme azedo", "manteiga", "farinha de trigo"] },
  { name: "Ovos Benedict", ingredients: ["ovo", "muffin inglês", "presunto", "molho holandês", "manteiga"] },
  { name: "Bisque de lagosta", ingredients: ["lagosta", "nata", "manteiga", "cebola", "aipo", "cenoura", "conhaque"] },
  { name: "Sopa de amêijoas", ingredients: ["amêijoa", "batata", "cebola", "aipo", "bacon", "nata", "manteiga"] },
  { name: "Torta de frango", ingredients: ["frango", "cenoura", "batata", "ervilhas", "cebola", "massa de torta", "nata"] },
  { name: "Bolo de carne", ingredients: ["carne bovina", "ovo", "farinha de rosca", "cebola", "ketchup", "mostarda"] },
  { name: "Rabanada", ingredients: ["pão", "ovo", "leite", "canela", "açúcar", "manteiga"] },
  { name: "Panquecas", ingredients: ["farinha de trigo", "ovo", "leite", "fermento em pó", "açúcar", "manteiga"] },
  { name: "Waffles", ingredients: ["farinha de trigo", "ovo", "leite", "fermento em pó", "açúcar", "manteiga"] },
  { name: "Pão de banana", ingredients: ["banana", "farinha de trigo", "ovo", "açúcar", "manteiga"] },
  { name: "Torta de maçã", ingredients: ["maçã", "farinha de trigo", "ovo", "açúcar", "manteiga", "canela"] },
  { name: "Torta de limão", ingredients: ["limão", "ovo", "açúcar", "manteiga", "farinha de trigo"] },
  { name: "Brownie", ingredients: ["chocolate", "farinha de trigo", "ovo", "açúcar", "manteiga"] },
  { name: "Cheesecake", ingredients: ["cream cheese", "ovo", "açúcar", "manteiga", "biscoito graham"] },
  { name: "Sopa de abóbora", ingredients: ["abóbora", "cebola", "alho", "nata", "manteiga"] },
  { name: "Minestrone", ingredients: ["feijão", "cenoura", "aipo", "cebola", "tomate", "massa"] },
  { name: "Omelete francesa", ingredients: ["ovo", "leite", "queijo", "presunto", "cebola", "pimentão"] },
  { name: "Ovos mexidos", ingredients: ["ovo", "leite", "manteiga", "sal", "pimenta"] },
  { name: "Quesadilla", ingredients: ["tortilla", "queijo", "frango", "pimentão", "cebola"] },
  { name: "Fajita", ingredients: ["carne bovina", "cebola", "pimentão", "tortilla", "creme azedo"] },
  { name: "Porco desfiado", ingredients: ["porco", "molho BBQ", "açúcar mascavo", "cebola", "pão"] },
  { name: "Fish and chips", ingredients: ["peixe", "batata", "farinha de trigo", "ovo", "óleo"] },
  { name: "Torta do pastor", ingredients: ["carne de cordeiro moída", "batata", "cenoura", "cebola", "ervilhas", "molho gravy"] },
  { name: "Bife", ingredients: ["carne bovina", "sal", "pimenta", "manteiga", "alho"] },
  { name: "Costeleta de cordeiro", ingredients: ["cordeiro", "sal", "pimenta", "alho", "alecrim"] },
  { name: "Frango assado", ingredients: ["frango", "sal", "pimenta", "alho", "tomilho", "azeite de oliva"] },
  { name: "Frango ao curry", ingredients: ["frango", "cebola", "tomate", "alho", "gengibre", "curry em pó", "leite de coco"] },
  { name: "Camarões ao alho", ingredients: ["camarão", "alho", "manteiga", "limão", "salsa", "espaguete"] },
  { name: "Paella de frutos do mar", ingredients: ["arroz", "camarão", "mexilhões", "lula", "ervilhas", "açafrão"] },
  { name: "Cacciatore", ingredients: ["frango", "tomate", "cebola", "pimentão", "cogumelos", "alho"] },
  { name: "Boeuf Bourguignon", ingredients: ["carne bovina", "vinho tinto", "cebola", "cenoura", "aipo", "alho", "tomilho"] },
  { name: "Goulash", ingredients: ["carne bovina", "cebola", "pimentão doce", "tomate", "pimentão", "alho"] },
  { name: "Borscht", ingredients: ["beterraba", "repolho", "batata", "cenoura", "cebola", "endro"] },
  { name: "Pierogi", ingredients: ["farinha de trigo", "ovo", "batata", "queijo", "cebola", "manteiga"] },
  { name: "Baklava", ingredients: ["massa filo", "noz", "pistache", "açúcar", "manteiga", "mel"] },
  { name: "Dolma", ingredients: ["folha de parreira", "arroz", "cebola", "pinhão", "endro"] },
  { name: "Rolinhos de repolho", ingredients: ["repolho", "carne bovina", "arroz", "cebola", "molho de tomate"] },
  { name: "Ensopado irlandês", ingredients: ["cordeiro", "batata", "cenoura", "cebola", "aipo"] },
  { name: "Cassoulet", ingredients: ["feijão branco", "porco", "pato", "linguiça", "cebola", "alho"] },
  { name: "Börek", ingredients: ["massa filo", "queijo", "batata", "ovo", "gergelim"] },
  { name: "Sauerbraten", ingredients: ["carne bovina", "cebola", "cenoura", "aipo", "vinagre", "gengibre"] },
  { name: "Wiener Schnitzel", ingredients: ["carne bovina", "ovo", "farinha de trigo", "farinha de rosca", "limão"] },
  { name: "Zwiebelrostbraten", ingredients: ["carne bovina", "cebola", "manteiga", "farinha de trigo", "caldo de carne"] },
  { name: "Rösti", ingredients: ["batata", "manteiga", "cebola", "bacon"] },
  { name: "Spätzle", ingredients: ["farinha de trigo", "ovo", "leite", "manteiga"] },
  { name: "Sopa goulash", ingredients: ["carne bovina", "cebola", "pimentão doce", "batata", "cenoura"] },
  { name: "Frango Kiev", ingredients: ["frango", "manteiga", "alho", "salsa", "ovo", "farinha de trigo", "farinha de rosca"] },
  { name: "Plov", ingredients: ["arroz", "carne bovina", "cenoura", "cebola", "cominho"] },
  { name: "Manti", ingredients: ["farinha de trigo", "ovo", "carne bovina", "cebola", "iogurte"] },
  { name: "Macarrão estilo Pequim", ingredients: ["macarrão", "porco", "ovo", "cebolinha", "molho de soja"] },
  { name: "Arroz Jollof", ingredients: ["arroz", "tomate", "cebola", "pimentão", "pimenta", "alho"] },
  { name: "Bobotie", ingredients: ["carne bovina", "pão", "ovo", "cebola", "leite", "curry em pó"] },
  { name: "Bunny Chow", ingredients: ["pão", "frango", "cebola", "tomate", "curry em pó"] },
  { name: "Chakalaka", ingredients: ["feijão", "cebola", "tomate", "pimenta", "cenoura", "pimentão"] },
  { name: "Pav Bhaji", ingredients: ["pão", "batata", "ervilhas", "cenoura", "cebola", "tomate", "manteiga"] },
  { name: "Vada Pav", ingredients: ["pão", "batata", "pimenta", "coentro", "alho", "semente de mostarda"] },
  { name: "Masala Dosa", ingredients: ["arroz", "lentilhas", "batata", "cebola", "semente de mostarda", "folha de curry"] },
  { name: "Idli", ingredients: ["arroz", "lentilhas", "sal"] },
  { name: "Sambar", ingredients: ["lentilhas", "cenoura", "cebola", "tomate", "berinjela", "drumstick", "mistura de especiarias"] },
  { name: "Katsu curry", ingredients: ["arroz", "tonkatsu", "molho de curry", "cebola", "cenoura", "batata"] },
  { name: "Takoyaki", ingredients: ["farinha de trigo", "ovo", "polvo", "cebolinha", "tenkasu", "maionese", "molho takoyaki"] },
  { name: "Sukiyaki", ingredients: ["carne bovina", "tofu", "cebolinha", "shiitake", "shirataki", "ovo"] },
  { name: "Nabe", ingredients: ["repolho", "tofu", "shiitake", "cenoura", "frango", "udon"] },
  { name: "Sopa de ovo", ingredients: ["ovo", "caldo de frango", "amido de batata", "cebolinha", "molho de soja"] },
  { name: "Sopa agridoce", ingredients: ["tofu", "ovo", "cogumelos", "menma", "vinagre", "molho de soja", "pimenta"] },
  { name: "Refogado de carne e brócolis", ingredients: ["carne bovina", "brócolis", "molho de soja", "alho", "gengibre", "cebola"] },
  { name: "Frango ao limão", ingredients: ["frango", "limão", "ovo", "farinha de trigo", "molho de soja", "açúcar"] },
  { name: "Arroz frito com abacaxi", ingredients: ["arroz", "abacaxi", "camarão", "ovo", "castanha de caju", "cebolinha"] },
  { name: "Bánh mì", ingredients: ["baguete", "porco", "cenoura", "pepino", "coentro", "maionese", "patê"] },
  { name: "Khao Soi", ingredients: ["macarrão de ovo", "frango", "leite de coco", "pasta de curry", "conservas"] },
  { name: "Bak Kut Teh", ingredients: ["costelas de porco", "alho", "molho de soja", "pimenta branca", "cogumelos"] },
  { name: "Laksa de Singapura", ingredients: ["macarrão de arroz", "camarão", "leite de coco", "tofu", "brotos de soja", "ovo", "pimenta", "coentro"] },
  { name: "Gado-gado", ingredients: ["vegetais", "tofu", "ovo", "molho de amendoim", "brotos de soja"] },
  { name: "Nasi Lemak", ingredients: ["arroz", "leite de coco", "ovo", "ikan bilis", "amendoim", "pepino", "molho sambal"] },
  { name: "Massa com pesto de rúcula", ingredients: ["rúcula", "massa", "queijo parmesão", "azeite de oliva", "pinhão"] },
  { name: "Shakshuka com queijo feta", ingredients: ["ovo", "tomate", "pimentão", "cebola", "queijo feta", "coentro"] },
  { name: "Panquecas de buttermilk", ingredients: ["farinha de trigo", "ovo", "buttermilk", "açúcar", "fermento em pó"] },
  { name: "Salada de quinoa", ingredients: ["quinoa", "pepino", "tomate", "queijo feta", "limão", "azeite de oliva"] },
  { name: "Salada Caesar de couve", ingredients: ["couve", "queijo parmesão", "croutons", "anchova", "ovo", "molho Caesar"] },
  { name: "Buddha bowl vegano", ingredients: ["arroz integral", "grão-de-bico", "abacate", "espinafre", "cenoura", "tofu"] },
  { name: "Berinjela à parmegiana", ingredients: ["berinjela", "molho de tomate", "mussarela", "queijo parmesão", "manjericão"] },
  { name: "Pimentões recheados", ingredients: ["pimentão", "arroz", "carne bovina moída", "cebola", "tomate", "queijo"] },
  { name: "Costeleta de cordeiro assada", ingredients: ["cordeiro", "alho", "alecrim", "azeite de oliva", "sal", "pimenta"] },
  { name: "Sopa de lentilhas", ingredients: ["lentilhas", "cenoura", "aipo", "cebola", "tomate", "alho"] },
  { name: "Couve-de-bruxelas assada", ingredients: ["couve-de-bruxelas", "azeite de oliva", "sal", "pimenta", "limão"] },
  { name: "Frango ao pesto", ingredients: ["frango", "pesto de manjericão", "queijo parmesão", "azeite de oliva"] },
  { name: "Molho de manga", ingredients: ["manga", "cebola", "lima", "coentro", "pimenta"] },
  { name: "Bacalhau assado", ingredients: ["bacalhau", "limão", "azeite de oliva", "salsa", "farinha de rosca"] },
  { name: "Coleslaw asiático", ingredients: ["repolho chinês", "cenoura", "cebolinha", "molho de soja", "vinagre de arroz", "óleo de gergelim"] },
  { name: "Salada de macarrão com amendoim", ingredients: ["macarrão", "amendoim", "cenoura", "pepino", "molho de soja", "óleo de gergelim"] },
  { name: "Chili vegano", ingredients: ["feijão preto", "tomate", "cebola", "pimenta em pó", "milho", "pimentão"] },
  { name: "Tacos de jaca", ingredients: ["jaca", "tortilla", "repolho", "lima", "abacate", "coentro"] },
  { name: "Refogado de tofu e vegetais", ingredients: ["tofu", "brócolis", "pimentão", "molho de soja", "gengibre", "alho"] },
  { name: "Risotto de abóbora", ingredients: ["abóbora", "arroz", "queijo parmesão", "cebola", "alho"] },
  { name: "Torrada de ratatouille", ingredients: ["berinjela", "abobrinha", "pimentão", "cebola", "pão"] },
  { name: "Salada de beterraba", ingredients: ["beterraba", "rúcula", "noz", "queijo de cabra", "balsâmico"] },
  { name: "Tajine marroquino", ingredients: ["cordeiro", "damasco", "amêndoa", "cebola", "canela", "coentro", "açafrão"] },
  { name: "Bife com chimichurri", ingredients: ["carne bovina", "salsa", "alho", "azeite de oliva", "orégano", "vinagre"] },
  { name: "Bolinhos de abobrinha", ingredients: ["abobrinha", "ovo", "farinha de trigo", "queijo parmesão", "cebolinha"] },
  { name: "Sopa de missô", ingredients: ["missô", "tofu", "wakame", "cebolinha", "caldo dashi"] },
  { name: "Wrap de falafel", ingredients: ["falafel", "pão pita", "alface", "tomate", "tahine"] },
  { name: "Laksa com camarões", ingredients: ["camarão", "macarrão de arroz", "leite de coco", "pasta de laksa", "ovo", "brotos de soja"] },
  { name: "Bowl de cuscuz", ingredients: ["cuscuz", "grão-de-bico", "cenoura", "abobrinha", "limão"] },
  { name: "Frango frito coreano doce", ingredients: ["frango", "gochujang", "molho de soja", "açúcar", "xarope de milho", "alho", "gengibre", "mistura para empanar"] },
  { name: "Budae Jjigae", ingredients: ["presunto", "linguiça", "kimchi", "tofu", "brotos de soja", "ramen", "gochujang", "pimenta em pó", "cebolinha"] },
  { name: "Sopa de costela bovina", ingredients: ["costela bovina", "daikon", "cebolinha", "alho", "gengibre", "molho de soja", "macarrão de batata-doce"] },
  { name: "Omelete coreana de frutos do mar", ingredients: ["lula", "camarão", "cebolinha", "farinha de trigo", "ovo", "água", "molho de soja", "vinagre"] },
  { name: "Yukgaejang", ingredients: ["carne bovina", "samambaia", "brotos de soja", "talo de taro", "cebolinha", "pimenta em pó", "molho de soja", "alho"] },
  { name: "Bossam", ingredients: ["porco", "alho", "gengibre", "cebolinha", "missô", "molho de camarão salgado", "kimchi de rabanete", "repolho chinês"] },
  { name: "Samgyetang", ingredients: ["frango", "ginseng", "jujuba", "alho", "arroz glutinoso", "cebolinha", "sal"] },
  { name: "Jjimdak", ingredients: ["frango", "batata", "cenoura", "cebola", "cebolinha", "macarrão de batata-doce", "molho de soja", "açúcar", "alho"] },
  { name: "Bibim guksu", ingredients: ["macarrão", "gochujang", "vinagre", "açúcar", "pepino", "alface", "ovo", "óleo de gergelim"] },
  { name: "Kimbap", ingredients: ["arroz", "alga nori", "takuwan", "espinafre", "cenoura", "ovo", "presunto", "odeng", "óleo de gergelim"] },
  { name: "Jeyuk bokkeum", ingredients: ["porco", "gochujang", "pimenta em pó", "molho de soja", "açúcar", "alho", "cebola", "cebolinha"] },
  { name: "Dakbokkeumtang", ingredients: ["frango", "batata", "cenoura", "cebola", "cebolinha", "gochujang", "pimenta em pó", "alho"] },
  { name: "Doenjang jjigae", ingredients: ["missô", "tofu", "abobrinha", "cebola", "cebolinha", "cogumelos", "pimenta", "caldo de anchova"] },
  { name: "Agujjim", ingredients: ["tamboril", "brotos de soja", "midodok", "seri", "pimenta em pó", "alho", "molho de soja", "amido de batata"] },
  { name: "Gopchang jeongol", ingredients: ["intestinos bovinos", "cebolinha", "cebola", "folha de perilla", "cogumelos", "tofu", "pimenta em pó", "alho picado", "caldo"] },
  { name: "Frango frito picante coreano", ingredients: ["frango", "gochujang", "xarope de milho", "ketchup", "alho", "molho de soja", "amendoim", "mistura para empanar"] },
  { name: "Gukbap", ingredients: ["arroz", "porco", "vísceras", "cebolinha", "alho", "pimenta em pó", "sundae"] },
  { name: "Massa aglio e olio", ingredients: ["espaguete", "alho", "azeite de oliva", "pimenta", "salsa"] },
  { name: "Massa alle vongole", ingredients: ["espaguete", "amêijoa", "alho", "azeite de oliva", "vinho branco", "salsa"] },
  { name: "Camarões ao alho", ingredients: ["camarão", "alho", "azeite de oliva", "pimenta", "baguete"] },
  { name: "Bife com molho", ingredients: ["carne bovina", "pimentão", "cebola", "cogumelos", "molho de soja", "ketchup", "açúcar", "molho de bife"] },
  { name: "Salada de ricota", ingredients: ["queijo ricota", "folhas verdes", "vinagrete balsâmico", "tomate", "nozes"] },
  { name: "Panquecas de batata coreanas", ingredients: ["batata", "cebola", "mistura para panquecas", "água", "sal", "óleo"] },
  { name: "Cavala grelhada", ingredients: ["cavala", "sal", "pimenta", "limão", "óleo"] },
  { name: "Refogado de polvo pequeno", ingredients: ["polvo pequeno", "cebola", "cebolinha", "repolho", "gochujang", "pimenta em pó", "alho", "açúcar"] },
  { name: "Refogado de pés de frango", ingredients: ["pés de frango", "gochujang", "pimenta em pó", "alho", "cebola", "cebolinha", "açúcar", "xarope de milho"] },
  { name: "Sorvete", ingredients: ["leite", "açúcar", "gema de ovo", "nata", "baunilha"] },
  { name: "Tiramisù", ingredients: ["queijo mascarpone", "biscoito de champagne", "café", "açúcar", "gema de ovo", "cacau em pó"] },
  { name: "Macaron", ingredients: ["farinha de amêndoa", "açúcar de confeiteiro", "clara de ovo", "açúcar", "corante alimentar"] },
  { name: "Croffle", ingredients: ["massa de croissant", "máquina de waffle", "açúcar", "manteiga"] },
  { name: "Pastel de ovo", ingredients: ["massa de torta", "ovo", "leite", "açúcar", "nata", "extrato de baunilha"] },
  { name: "Pão com anko e manteiga", ingredients: ["pão", "pasta de feijão vermelho", "manteiga"] },
  { name: "Hotteok", ingredients: ["farinha de trigo", "açúcar", "fermento", "água", "sementes", "mel"] },
  { name: "Bungeoppang", ingredients: ["farinha de trigo", "ovo", "leite", "açúcar", "pasta de feijão vermelho", "manteiga"] },
  { name: "Cachorro-quente", ingredients: ["salsicha", "pão", "ketchup", "mostarda", "cebola", "picles"] },
  { name: "Sopa de cebola francesa", ingredients: ["cebola", "caldo de carne", "pão", "queijo", "manteiga", "farinha de trigo"] },
  { name: "Espaguete com almôndegas", ingredients: ["espaguete", "carne bovina moída", "molho de tomate", "cebola", "alho", "farinha de rosca", "ovo"] },
  { name: "Tacos de peixe", ingredients: ["peixe", "tortilla", "repolho", "molho", "lima", "coentro"] },
  { name: "Scone de queijo", ingredients: ["farinha de trigo", "manteiga", "leite", "queijo", "fermento em pó"] },
  { name: "Muffin de mirtilo", ingredients: ["farinha de trigo", "mirtilo", "açúcar", "ovo", "leite", "óleo", "fermento em pó"] }
];

window.INGREDIENTS_DB = [
  "ovo", "frango", "carne bovina", "porco", "cebola", "alho", "cenoura", "batata", "espaguete", "arroz", "tomate", "alface",
  "tofu", "brotos de soja", "amendoim", "vinho tinto", "missô", "alga nori", "kimchi", "bacon", "queijo parmesão", "anchova", "pão",
  "queijo", "camarão", "capim-limão", "galanga", "lima", "pimentão", "berinjela", "abobrinha", "croutons", "caldo dashi",
  "panceta", "pimenta", "cogumelos", "iogurte", "farinha de trigo", "açúcar", "sal", "manteiga", "leite", "nata", "pepino",
  "maçã", "banana", "laranja", "limão", "lima", "brócolis", "espinafre", "abóbora", "batata-doce", "milho", "ervilhas",
  "repolho", "aipo", "gengibre", "molho de soja", "vinagre", "azeite de oliva", "óleo de canola", "óleo de girassol", "óleo de gergelim",
  "molho de peixe", "molho de ostra", "pasta de feijão doce (tianmianjiang)", "ketchup", "mostarda", "maionese", "manjericão", "coentro", "salsa",
  "alecrim", "tomilho", "sálvia", "hortelã", "canela", "noz-moscada", "cravo", "louro", "anis estrelado", "cardamomo",
  "curry em pó", "pimenta em pó", "pimentão doce", "açafrão", "cominho", "coentro (semente)", "endro", "funcho", "baunilha",
  "chocolate", "cacau em pó", "geleia", "mel", "xarope de bordo", "melaço", "morango", "mirtilo", "framboesa",
  "cranberry", "amora", "abacaxi", "manga", "kiwi", "uva", "pêra", "pêssego", "damasco", "ameixa", "jujuba",
  "figo", "coco", "noz", "amêndoa", "avelã", "castanha de caju", "pistache", "macadâmia", "pecã", "semente de girassol",
  "semente de chia", "semente de abóbora", "gergelim", "quinoa", "cevada", "painço", "trigo sarraceno", "aveia", "pão", "massa",
  "macarrão", "tortilla", "pão naan", "pão pita", "pão de fermentação natural", "bagel", "croissant", "donut", "massa de pizza", "biscoito salgado",
  "linguiça", "salame", "presunto", "pato", "cordeiro", "peru", "coelho", "vitela", "ganso", "anchova", "sardinha", "atum",
  "cavala", "salmão", "bacalhau", "hadoque", "merlan", "bagre", "tilápia", "lula", "polvo", "amêijoa", "mexilhão",
  "vieira", "lagosta", "caranguejo", "lagostim", "orelha do mar", "pepino do mar", "ouriço do mar", "wasabi", "raiz-forte",
  "tabasco", "molho sriracha", "gochujang", "ssamjang", "missô", "missô", "feijão vermelho", "feijão preto", "feijão",
  "grão-de-bico", "lentilha", "feijão", "feijão branco", "vagem", "ervilha doce", "ervilha doce", "edamame", "mussarela",
  "cheddar", "gouda", "brie", "camembert", "feta", "queijo azul", "suíço", "provolone", "ricota",
  "mascarpone", "cream cheese", "requeijão", "creme azedo", "iogurte", "buttermilk", "leite condensado",
  "leite condensado açucarado", "leite em pó", "leite de amêndoa", "leite de soja", "leite de arroz", "leite de coco", "leite de aveia",
  "pasta de camarão", "pasta de anchova", "extrato de tomate", "molho de tomate", "pesto", "molho picante", "harissa", "azba",
  "tahine", "hummus", "guacamole", "molho", "relish", "tapenade", "molho gravy", "caldo", "caldo", "caldo", "gelatina",
  "ágar-ágar", "amido de batata", "amido de batata", "tapioca", "araruta", "farinha de arroz", "sêmola", "farinha de milho",
  "polenta", "gérmen de trigo", "farelo de trigo", "papel de arroz", "papel de rolinho primavera", "alga nori", "bolo de arroz", "udon", "ramen",
  "macarrão de celofane", "trigo sarraceno", "fettuccine", "penne", "macarrão", "lasanha", "espaguete", "linguine", "cabelo de anjo",
  "gnocchi", "ravioli", "tortellini", "gyoza", "wonton", "pierogi", "empanada", "tamale", "cebolinha",
  "chalota", "alho-poró", "nabo", "rabanete", "pastinaca", "rutabaga", "beterraba", "couve-rábano", "rabanete japonês (daikon)", "jícama", "raiz de lótus",
  "alcachofra", "aspargo", "quiabo", "broto de bambu (menma)", "gema de ovo", "clara de ovo", "ovo de codorna", "ovo de pato", "ovo de ganso",
  "trufa", "morchela", "porcini", "enoki", "shiitake", "pleurotus", "boletus", "champignon", "portobello",
  "castanha", "arrowhead", "taro", "inhame", "mandioca", "salsifis", "topinambur", "funcho (bulbo)",
  "rúcula", "pesto de manjericão", "pimentão", "bok choy", "couve-de-bruxelas", "buttermilk", "alcaparra",
  "caramelo", "alcaravia", "castanha de caju", "chia", "óleo de pimenta", "cebolinha", "semente de coentro", "requeijão",
  "caranguejo", "cranberry", "nata", "agrião", "dente-de-leão", "tâmara", "papel de rolinho de ovo", "espelta", "feno-grego",
  "queijo feta", "manteiga de amendoim", "queijo de cabra", "vagem", "goiaba", "avelã", "semente de cânhamo", "mistura de ervas",
  "jaca", "couve", "suco de kimchi", "kumquat", "alho-poró", "pasta de lentilha", "lichia", "chutney de manga",
  "queijo manchego", "bacon de bordo", "manjerona", "mizuna", "fruta do monge", "molho de cogumelo", "mostarda verde",
  "repolho chinês", "nectarina", "quiabo", "azeitona", "casca de laranja", "mamão", "maracujá", "broto de ervilha",
  "pecã", "queijo pepper jack", "caqui", "pinhão", "creme de pistache", "tomate ameixa", "pipoca", "prosciutto",
  "pão pumpernickel", "quark", "chicória", "ras el hanout", "lentilha vermelha", "ricota salgada", "rúcula", "alface romana",
  "roquefort", "água de rosas", "rutabaga", "sagu", "salsifis", "repolho de saboia", "cebolinha verde", "chalota",
  "shiso", "tofu sedoso", "salmão defumado", "ervilha doce", "ervilha doce", "azedinha", "proteína de soja", "espelta",
  "tinta de lula", "stilton", "cogumelo nameko", "sumac", "tomate seco", "milho doce", "acelga",
  "tamarindo", "tempeh", "tomilho", "gergelim torrado", "yuba", "tomate", "óleo de trufa", "folha de nabo",
  "laranja valenciana", "queijo vegano", "veado", "macarrão de celofane", "arroz com vinagre", "agrião", "farinha de trigo",
  "chocolate branco", "arroz selvagem", "inhame", "zaatar", "raspas", "flor de abobrinha", "feijão vermelho", "amaranto",
  "anis", "broto de bambu", "pimentão banana", "semente de manjericão", "vieira pequena", "alho preto", "laranja sanguínea",
  "borragem", "bresaola", "cacto", "lula", "melão canário", "gengibre cristalizado", "folha de cenoura", "farinha de mandioca",
  "aipo", "chayote", "cogumelo shimeji", "chouriço", "amora dos pântanos", "açúcar de coco", "alho confitado",
  "salada de milho", "feijão cranberry", "cogumelo cremini", "dolma", "edamame", "samambaia", "ovas de peixe", "frisée", "garam masala",
  "cebolinha de alho", "bagas de goji", "beterraba dourada", "alho jovem", "guanciale", "pé de porco", "raiz de raiz-forte",
  "topinambur", "citrus kobu", "alcaçuz", "alga kombu", "lardon", "lavanda", "limoncello", "fava longa",
  "semente de lótus", "caramelo de missô", "mijtra", "amora", "moscatel", "capuchinha", "urtiga", "folha de quiabo",
  "azeitona orali", "folha de pastinaca", "abobrinha pattypan", "pecorino", "pepino doce", "folha de perilla", "conserva",
  "feijão", "sálvia de abacaxi", "pimenta rosa", "ameixa passa", "pimentão poblano", "beldroega", "marmelo", "alho selvagem",
  "ruibarbo", "alho assado", "romanesco", "feijão", "folha de rutabaga", "ovas de salmão", "batata-doce", "aspargo do mar",
  "presunto", "linguiça", "ramen", "rabanete japonês (daikon)", "cebolinha verde", "lula", "midodok", "aipo japonês", "talo de taro", "samambaia", "pasta de camarão salgado",
  "ginseng", "jujuba", "arroz glutinoso", "amido de batata", "vísceras bovinas", "folha de perilla", "sopa", "xarope de malte", "tamboril",
  "morcela", "peperoncino", "baguete", "vinho branco", "molho para bife", "folhas tenras", "molho balsâmico", "nozes",
  "farinha para jeon", "cavala", "polvo pequeno", "repolho", "pé de frango", "farinha de amêndoa", "açúcar de confeiteiro", "corante alimentar",
  "massa de croissant", "máquina de waffle", "massa de torta", "extrato de baunilha", "pasta de feijão vermelho", "fermento", "semente", "mel", "pasta de feijão vermelho",
  "salsicha", "óleo", "fermento em pó"
];
