const flags = [
    { country: "아프가니스탄", img: "https://flagcdn.com/af.svg" },
    { country: "올란드 제도", img: "https://flagcdn.com/ax.svg" },
    { country: "알바니아", img: "https://flagcdn.com/al.svg" },
    { country: "알제리", img: "https://flagcdn.com/dz.svg" },
    { country: "아메리칸사모아", img: "https://flagcdn.com/as.svg" },
    { country: "안도라", img: "https://flagcdn.com/ad.svg" },
    { country: "앙골라", img: "https://flagcdn.com/ao.svg" },
    { country: "앵귈라", img: "https://flagcdn.com/ai.svg" },
    { country: "남극", img: "https://flagcdn.com/aq.svg" },
    { country: "앤티가 바부다", img: "https://flagcdn.com/ag.svg" },
    { country: "아르헨티나", img: "https://flagcdn.com/ar.svg" },
    { country: "아르메니아", img: "https://flagcdn.com/am.svg" },
    { country: "아루바", img: "https://flagcdn.com/aw.svg" },
    { country: "호주", img: "https://flagcdn.com/au.svg" },
    { country: "오스트리아", img: "https://flagcdn.com/at.svg" },
    { country: "아제르바이잔", img: "https://flagcdn.com/az.svg" },
    { country: "바하마", img: "https://flagcdn.com/bs.svg" },
    { country: "바레인", img: "https://flagcdn.com/bh.svg" },
    { country: "방글라데시", img: "https://flagcdn.com/bd.svg" },
    { country: "바베이도스", img: "https://flagcdn.com/bb.svg" },
    { country: "벨라루스", img: "https://flagcdn.com/by.svg" },
    { country: "벨기에", img: "https://flagcdn.com/be.svg" },
    { country: "벨리즈", img: "https://flagcdn.com/bz.svg" },
    { country: "베냉", img: "https://flagcdn.com/bj.svg" },
    { country: "버뮤다", img: "https://flagcdn.com/bm.svg" },
    { country: "부탄", img: "https://flagcdn.com/bt.svg" },
    { country: "볼리비아", img: "https://flagcdn.com/bo.svg" },
    { country: "카리브 네덜란드", img: "https://flagcdn.com/bq.svg" },
    { country: "보스니아 헤르체고비나", img: "https://flagcdn.com/ba.svg" },
    { country: "보츠와나", img: "https://flagcdn.com/bw.svg" },
    { country: "부베섬", img: "https://flagcdn.com/bv.svg" },
    { country: "브라질", img: "https://flagcdn.com/br.svg" },
    { country: "영국령 인도양 지역", img: "https://flagcdn.com/io.svg" },
    { country: "영국령 버진아일랜드", img: "https://flagcdn.com/vg.svg" },
    { country: "브루나이", img: "https://flagcdn.com/bn.svg" },
    { country: "불가리아", img: "https://flagcdn.com/bg.svg" },
    { country: "부르키나파소", img: "https://flagcdn.com/bf.svg" },
    { country: "부룬디", img: "https://flagcdn.com/bi.svg" },
    { country: "카보베르데", img: "https://flagcdn.com/cv.svg" },
    { country: "캄보디아", img: "https://flagcdn.com/kh.svg" },
    { country: "카메룬", img: "https://flagcdn.com/cm.svg" },
    { country: "캐나다", img: "https://flagcdn.com/ca.svg" },
    { country: "케이맨 제도", img: "https://flagcdn.com/ky.svg" },
    { country: "중앙아프리카 공화국", img: "https://flagcdn.com/cf.svg" },
    { country: "차드", img: "https://flagcdn.com/td.svg" },
    { country: "칠레", img: "https://flagcdn.com/cl.svg" },
    { country: "중국", img: "https://flagcdn.com/cn.svg" },
    { country: "크리스마스섬", img: "https://flagcdn.com/cx.svg" },
    { country: "코코스 (킬링) 제도", img: "https://flagcdn.com/cc.svg" },
    { country: "콜롬비아", img: "https://flagcdn.com/co.svg" },
    { country: "코모로", img: "https://flagcdn.com/km.svg" },
    { country: "콩고 (DRC)", img: "https://flagcdn.com/cd.svg" },
    { country: "콩고 (공화국)", img: "https://flagcdn.com/cg.svg" },
    { country: "쿡 제도", img: "https://flagcdn.com/ck.svg" },
    { country: "코스타리카", img: "https://flagcdn.com/cr.svg" },
    { country: "코트디부아르", img: "https://flagcdn.com/ci.svg" },
    { country: "크로아티아", img: "https://flagcdn.com/hr.svg" },
    { country: "쿠바", img: "https://flagcdn.com/cu.svg" },
    { country: "큐라소", img: "https://flagcdn.com/cw.svg" },
    { country: "키프로스", img: "https://flagcdn.com/cy.svg" },
    { country: "체코", img: "https://flagcdn.com/cz.svg" },
    { country: "덴마크", img: "https://flagcdn.com/dk.svg" },
    { country: "지부티", img: "https://flagcdn.com/dj.svg" },
    { country: "도미니카", img: "https://flagcdn.com/dm.svg" },
    { country: "도미니카 공화국", img: "https://flagcdn.com/do.svg" },
    { country: "에콰도르", img: "https://flagcdn.com/ec.svg" },
    { country: "이집트", img: "https://flagcdn.com/eg.svg" },
    { country: "엘살바도르", img: "https://flagcdn.com/sv.svg" },
    { country: "적도 기니", img: "https://flagcdn.com/gq.svg" },
    { country: "에리트레아", img: "https://flagcdn.com/er.svg" },
    { country: "에스토니아", img: "https://flagcdn.com/ee.svg" },
    { country: "에스와티니", img: "https://flagcdn.com/sz.svg" },
    { country: "에티오피아", img: "https://flagcdn.com/et.svg" },
    { country: "포클랜드 제도", img: "https://flagcdn.com/fk.svg" },
    { country: "페로 제도", img: "https://flagcdn.com/fo.svg" },
    { country: "피지", img: "https://flagcdn.com/fj.svg" },
    { country: "핀란드", img: "https://flagcdn.com/fi.svg" },
    { country: "프랑스", img: "https://flagcdn.com/fr.svg" },
    { country: "프랑스령 기아나", img: "https://flagcdn.com/gf.svg" },
    { country: "프랑스령 폴리네시아", img: "https://flagcdn.com/pf.svg" },
    { country: "프랑스령 남방 및 남극 지역", img: "https://flagcdn.com/tf.svg" },
    { country: "가봉", img: "https://flagcdn.com/ga.svg" },
    { country: "감비아", img: "https://flagcdn.com/gm.svg" },
    { country: "조지아", img: "https://flagcdn.com/ge.svg" },
    { country: "독일", img: "https://flagcdn.com/de.svg" },
    { country: "가나", img: "https://flagcdn.com/gh.svg" },
    { country: "지브롤터", img: "https://flagcdn.com/gi.svg" },
    { country: "그리스", img: "https://flagcdn.com/gr.svg" },
    { country: "그린란드", img: "https://flagcdn.com/gl.svg" },
    { country: "그레나다", img: "https://flagcdn.com/gd.svg" },
    { country: "과들루프", img: "https://flagcdn.com/gp.svg" },
    { country: "괌", img: "https://flagcdn.com/gu.svg" },
    { country: "과테말라", img: "https://flagcdn.com/gt.svg" },
    { country: "건지", img: "https://flagcdn.com/gg.svg" },
    { country: "기니", img: "https://flagcdn.com/gn.svg" },
    { country: "기니비사우", img: "https://flagcdn.com/gw.svg" },
    { country: "가이아나", img: "https://flagcdn.com/gy.svg" },
    { country: "아이티", img: "https://flagcdn.com/ht.svg" },
    { country: "허드 맥도널드 제도", img: "https://flagcdn.com/hm.svg" },
    { country: "바티칸 시국", img: "https://flagcdn.com/va.svg" },
    { country: "온두라스", img: "https://flagcdn.com/hn.svg" },
    { country: "홍콩", img: "https://flagcdn.com/hk.svg" },
    { country: "헝가리", img: "https://flagcdn.com/hu.svg" },
    { country: "아이슬란드", img: "https://flagcdn.com/is.svg" },
    { country: "인도", img: "https://flagcdn.com/in.svg" },
    { country: "인도네시아", img: "https://flagcdn.com/id.svg" },
    { country: "이란", img: "https://flagcdn.com/ir.svg" },
    { country: "이라크", img: "https://flagcdn.com/iq.svg" },
    { country: "아일랜드", img: "https://flagcdn.com/ie.svg" },
    { country: "맨섬", img: "https://flagcdn.com/im.svg" },
    { country: "이스라엘", img: "https://flagcdn.com/il.svg" },
    { country: "이탈리아", img: "https://flagcdn.com/it.svg" },
    { country: "자메이카", img: "https://flagcdn.com/jm.svg" },
    { country: "일본", img: "https://flagcdn.com/jp.svg" },
    { country: "저지", img: "https://flagcdn.com/je.svg" },
    { country: "요르단", img: "https://flagcdn.com/jo.svg" },
    { country: "카자흐스탄", img: "https://flagcdn.com/kz.svg" },
    { country: "케냐", img: "https://flagcdn.com/ke.svg" },
    { country: "키리바시", img: "https://flagcdn.com/ki.svg" },
    { country: "북한", img: "https://flagcdn.com/kp.svg" },
    { country: "대한민국", img: "https://flagcdn.com/kr.svg" },
    { country: "쿠웨이트", img: "https://flagcdn.com/kw.svg" },
    { country: "키르기스스탄", img: "https://flagcdn.com/kg.svg" },
    { country: "라오스", img: "https://flagcdn.com/la.svg" },
    { country: "라트비아", img: "https://flagcdn.com/lv.svg" },
    { country: "레바논", img: "https://flagcdn.com/lb.svg" },
    { country: "레소토", img: "https://flagcdn.com/ls.svg" },
    { country: "라이베리아", img: "https://flagcdn.com/lr.svg" },
    { country: "리비아", img: "https://flagcdn.com/ly.svg" },
    { country: "리히텐슈타인", img: "https://flagcdn.com/li.svg" },
    { country: "리투아니아", img: "https://flagcdn.com/lt.svg" },
    { country: "룩셈부르크", img: "https://flagcdn.com/lu.svg" },
    { country: "마카오", img: "https://flagcdn.com/mo.svg" },
    { country: "마다가스카르", img: "https://flagcdn.com/mg.svg" },
    { country: "말라위", img: "https://flagcdn.com/mw.svg" },
    { country: "말레이시아", img: "https://flagcdn.com/my.svg" },
    { country: "몰디브", img: "https://flagcdn.com/mv.svg" },
    { country: "말리", img: "https://flagcdn.com/ml.svg" },
    { country: "몰타", img: "https://flagcdn.com/mt.svg" },
    { country: "마셜 제도", img: "https://flagcdn.com/mh.svg" },
    { country: "마르티니크", img: "https://flagcdn.com/mq.svg" },
    { country: "모리타니", img: "https://flagcdn.com/mr.svg" },
    { country: "모리셔스", img: "https://flagcdn.com/mu.svg" },
    { country: "마요트", img: "https://flagcdn.com/yt.svg" },
    { country: "멕시코", img: "https://flagcdn.com/mx.svg" },
    { country: "미크로네시아", img: "https://flagcdn.com/fm.svg" },
    { country: "몰도바", img: "https://flagcdn.com/md.svg" },
    { country: "모나코", img: "https://flagcdn.com/mc.svg" },
    { country: "몽골", img: "https://flagcdn.com/mn.svg" },
    { country: "몬테네그로", img: "https://flagcdn.com/me.svg" },
    { country: "몬트세랫", img: "https://flagcdn.com/ms.svg" },
    { country: "모로코", img: "https://flagcdn.com/ma.svg" },
    { country: "모잠비크", img: "https://flagcdn.com/mz.svg" },
    { country: "미얀마", img: "https://flagcdn.com/mm.svg" },
    { country: "나미비아", img: "https://flagcdn.com/na.svg" },
    { country: "나우루", img: "https://flagcdn.com/nr.svg" },
    { country: "네팔", img: "https://flagcdn.com/np.svg" },
    { country: "네덜란드", img: "https://flagcdn.com/nl.svg" },
    { country: "누벨칼레도니", img: "https://flagcdn.com/nc.svg" },
    { country: "뉴질랜드", img: "https://flagcdn.com/nz.svg" },
    { country: "니카라과", img: "https://flagcdn.com/ni.svg" },
    { country: "니제르", img: "https://flagcdn.com/ne.svg" },
    { country: "나이지리아", img: "https://flagcdn.com/ng.svg" },
    { country: "니우에", img: "https://flagcdn.com/nu.svg" },
    { country: "노퍽섬", img: "https://flagcdn.com/nf.svg" },
    { country: "북마리아나 제도", img: "https://flagcdn.com/mp.svg" },
    { country: "노르웨이", img: "https://flagcdn.com/no.svg" },
    { country: "오만", img: "https://flagcdn.com/om.svg" },
    { country: "파키스탄", img: "https://flagcdn.com/pk.svg" },
    { country: "팔라우", img: "https://flagcdn.com/pw.svg" },
    { country: "팔레스타인", img: "https://flagcdn.com/ps.svg" },
    { country: "파나마", img: "https://flagcdn.com/pa.svg" },
    { country: "파푸아뉴기니", img: "https://flagcdn.com/pg.svg" },
    { country: "파라과이", img: "https://flagcdn.com/py.svg" },
    { country: "페루", img: "https://flagcdn.com/pe.svg" },
    { country: "필리핀", img: "https://flagcdn.com/ph.svg" },
    { country: "핏케언 제도", img: "https://flagcdn.com/pn.svg" },
    { country: "폴란드", img: "https://flagcdn.com/pl.svg" },
    { country: "포르투갈", img: "https://flagcdn.com/pt.svg" },
    { country: "푸에르토리코", img: "https://flagcdn.com/pr.svg" },
    { country: "카타르", img: "https://flagcdn.com/qa.svg" },
    { country: "레위니옹", img: "https://flagcdn.com/re.svg" },
    { country: "루마니아", img: "https://flagcdn.com/ro.svg" },
    { country: "러시아", img: "https://flagcdn.com/ru.svg" },
    { country: "르완다", img: "https://flagcdn.com/rw.svg" },
    { country: "생바르텔레미", img: "https://flagcdn.com/bl.svg" },
    { country: "세인트헬레나", img: "https://flagcdn.com/sh.svg" },
    { country: "세인트키츠 네비스", img: "https://flagcdn.com/kn.svg" },
    { country: "세인트루시아", img: "https://flagcdn.com/lc.svg" },
    { country: "생마르탱", img: "https://flagcdn.com/mf.svg" },
    { country: "생피에르 미클롱", img: "https://flagcdn.com/pm.svg" },
    { country: "세인트빈센트 그레나딘", img: "https://flagcdn.com/vc.svg" },
    { country: "사모아", img: "https://flagcdn.com/ws.svg" },
    { country: "산마리노", img: "https://flagcdn.com/sm.svg" },
    { country: "상투메 프린시페", img: "https://flagcdn.com/st.svg" },
    { country: "사우디아라비아", img: "https://flagcdn.com/sa.svg" },
    { country: "세네갈", img: "https://flagcdn.com/sn.svg" },
    { country: "세르비아", img: "https://flagcdn.com/rs.svg" },
    { country: "세이셸", img: "https://flagcdn.com/sc.svg" },
    { country: "시에라리온", img: "https://flagcdn.com/sl.svg" },
    { country: "싱가포르", img: "https://flagcdn.com/sg.svg" },
    { country: "신트마르턴", img: "https://flagcdn.com/sx.svg" },
    { country: "슬로바키아", img: "https://flagcdn.com/sk.svg" },
    { country: "슬로베니아", img: "https://flagcdn.com/si.svg" },
    { country: "솔로몬 제도", img: "https://flagcdn.com/sb.svg" },
    { country: "소말리아", img: "https://flagcdn.com/so.svg" },
    { country: "남아프리카 공화국", img: "https://flagcdn.com/za.svg" },
    { country: "사우스조지아", img: "https://flagcdn.com/gs.svg" },
    { country: "남수단", img: "https://flagcdn.com/ss.svg" },
    { country: "스페인", img: "https://flagcdn.com/es.svg" },
    { country: "스리랑카", img: "https://flagcdn.com/lk.svg" },
    { country: "수단", img: "https://flagcdn.com/sd.svg" },
    { country: "수리남", img: "https://flagcdn.com/sr.svg" },
    { country: "스발바르 얀마옌", img: "https://flagcdn.com/sj.svg" },
    { country: "스웨덴", img: "https://flagcdn.com/se.svg" },
    { country: "스위스", img: "https://flagcdn.com/ch.svg" },
    { country: "시리아", img: "https://flagcdn.com/sy.svg" },
    { country: "대만", img: "https://flagcdn.com/tw.svg" },
    { country: "타지키스탄", img: "https://flagcdn.com/tj.svg" },
    { country: "탄자니아", img: "https://flagcdn.com/tz.svg" },
    { country: "태국", img: "https://flagcdn.com/th.svg" },
    { country: "동티모르", img: "https://flagcdn.com/tl.svg" },
    { country: "토고", img: "https://flagcdn.com/tg.svg" },
    { country: "토켈라우", img: "https://flagcdn.com/tk.svg" },
    { country: "통가", img: "https://flagcdn.com/to.svg" },
    { country: "트리니다드 토바고", img: "https://flagcdn.com/tt.svg" },
    { country: "튀니지", img: "https://flagcdn.com/tn.svg" },
    { country: "튀르키예", img: "https://flagcdn.com/tr.svg" },
    { country: "투르크메니스탄", img: "https://flagcdn.com/tm.svg" },
    { country: "터크스 케이커스 제도", img: "https://flagcdn.com/tc.svg" },
    { country: "투발루", img: "https://flagcdn.com/tv.svg" },
    { country: "우간다", img: "https://flagcdn.com/ug.svg" },
    { country: "우크라이나", img: "https://flagcdn.com/ua.svg" },
    { country: "아랍에미리트", img: "https://flagcdn.com/ae.svg" },
    { country: "영국", img: "https://flagcdn.com/gb.svg" },
    { country: "미국", img: "https://flagcdn.com/us.svg" },
    { country: "미국령 군소 제도", img: "https://flagcdn.com/um.svg" },
    { country: "우루과이", img: "https://flagcdn.com/uy.svg" },
    { country: "우즈베키스탄", img: "https://flagcdn.com/uz.svg" },
    { country: "바누아투", img: "https://flagcdn.com/vu.svg" },
    { country: "베네수엘라", img: "https://flagcdn.com/ve.svg" },
    { country: "베트남", img: "https://flagcdn.com/vn.svg" },
    { country: "왈리스 푸투나", img: "https://flagcdn.com/wf.svg" },
    { country: "서사하라", img: "https://flagcdn.com/eh.svg" },
    { country: "예멘", img: "https://flagcdn.com/ye.svg" },
    { country: "잠비아", img: "https://flagcdn.com/zm.svg" },
    { country: "짐바브웨", img: "https://flagcdn.com/zw.svg" },
    { country: "코소보", img: "https://flagcdn.com/xk.svg" }
];