const flags = [
    { country: "Afghanistan", img: "https://flagcdn.com/af.svg" },
    { country: "Îles Åland", img: "https://flagcdn.com/ax.svg" },
    { country: "Albanie", img: "https://flagcdn.com/al.svg" },
    { country: "Algérie", img: "https://flagcdn.com/dz.svg" },
    { country: "Samoa américaines", img: "https://flagcdn.com/as.svg" },
    { country: "Andorre", img: "https://flagcdn.com/ad.svg" },
    { country: "Angola", img: "https://flagcdn.com/ao.svg" },
    { country: "Anguilla", img: "https://flagcdn.com/ai.svg" },
    { country: "Antarctique", img: "https://flagcdn.com/aq.svg" },
    { country: "Antigua-et-Barbuda", img: "https://flagcdn.com/ag.svg" },
    { country: "Argentine", img: "https://flagcdn.com/ar.svg" },
    { country: "Arménie", img: "https://flagcdn.com/am.svg" },
    { country: "Aruba", img: "https://flagcdn.com/aw.svg" },
    { country: "Australie", img: "https://flagcdn.com/au.svg" },
    { country: "Autriche", img: "https://flagcdn.com/at.svg" },
    { country: "Azerbaïdjan", img: "https://flagcdn.com/az.svg" },
    { country: "Bahamas", img: "https://flagcdn.com/bs.svg" },
    { country: "Bahreïn", img: "https://flagcdn.com/bh.svg" },
    { country: "Bangladesh", img: "https://flagcdn.com/bd.svg" },
    { country: "Barbade", img: "https://flagcdn.com/bb.svg" },
    { country: "Biélorussie", img: "https://flagcdn.com/by.svg" },
    { country: "Belgique", img: "https://flagcdn.com/be.svg" },
    { country: "Belize", img: "https://flagcdn.com/bz.svg" },
    { country: "Bénin", img: "https://flagcdn.com/bj.svg" },
    { country: "Bermudes", img: "https://flagcdn.com/bm.svg" },
    { country: "Bhoutan", img: "https://flagcdn.com/bt.svg" },
    { country: "Bolivie", img: "https://flagcdn.com/bo.svg" },
    { country: "Pays-Bas caribéens", img: "https://flagcdn.com/bq.svg" },
    { country: "Bosnie-Herzégovine", img: "https://flagcdn.com/ba.svg" },
    { country: "Botswana", img: "https://flagcdn.com/bw.svg" },
    { country: "Île Bouvet", img: "https://flagcdn.com/bv.svg" },
    { country: "Brésil", img: "https://flagcdn.com/br.svg" },
    { country: "Territoire britannique de l'océan Indien", img: "https://flagcdn.com/io.svg" },
    { country: "Îles Vierges britanniques", img: "https://flagcdn.com/vg.svg" },
    { country: "Brunei", img: "https://flagcdn.com/bn.svg" },
    { country: "Bulgarie", img: "https://flagcdn.com/bg.svg" },
    { country: "Burkina Faso", img: "https://flagcdn.com/bf.svg" },
    { country: "Burundi", img: "https://flagcdn.com/bi.svg" },
    { country: "Cap-Vert", img: "https://flagcdn.com/cv.svg" },
    { country: "Cambodge", img: "https://flagcdn.com/kh.svg" },
    { country: "Cameroun", img: "https://flagcdn.com/cm.svg" },
    { country: "Canada", img: "https://flagcdn.com/ca.svg" },
    { country: "Îles Caïmans", img: "https://flagcdn.com/ky.svg" },
    { country: "République centrafricaine", img: "https://flagcdn.com/cf.svg" },
    { country: "Tchad", img: "https://flagcdn.com/td.svg" },
    { country: "Chili", img: "https://flagcdn.com/cl.svg" },
    { country: "Chine", img: "https://flagcdn.com/cn.svg" },
    { country: "Île Christmas", img: "https://flagcdn.com/cx.svg" },
    { country: "Îles Cocos", img: "https://flagcdn.com/cc.svg" },
    { country: "Colombie", img: "https://flagcdn.com/co.svg" },
    { country: "Comores", img: "https://flagcdn.com/km.svg" },
    { country: "République démocratique du Congo", img: "https://flagcdn.com/cd.svg" },
    { country: "République du Congo", img: "https://flagcdn.com/cg.svg" },
    { country: "Îles Cook", img: "https://flagcdn.com/ck.svg" },
    { country: "Costa Rica", img: "https://flagcdn.com/cr.svg" },
    { country: "Côte d'Ivoire", img: "https://flagcdn.com/ci.svg" },
    { country: "Croatie", img: "https://flagcdn.com/hr.svg" },
    { country: "Cuba", img: "https://flagcdn.com/cu.svg" },
    { country: "Curaçao", img: "https://flagcdn.com/cw.svg" },
    { country: "Chypre", img: "https://flagcdn.com/cy.svg" },
    { country: "Tchéquie", img: "https://flagcdn.com/cz.svg" },
    { country: "Danemark", img: "https://flagcdn.com/dk.svg" },
    { country: "Djibouti", img: "https://flagcdn.com/dj.svg" },
    { country: "Dominique", img: "https://flagcdn.com/dm.svg" },
    { country: "République dominicaine", img: "https://flagcdn.com/do.svg" },
    { country: "Équateur", img: "https://flagcdn.com/ec.svg" },
    { country: "Égypte", img: "https://flagcdn.com/eg.svg" },
    { country: "El Salvador", img: "https://flagcdn.com/sv.svg" },
    { country: "Guinée équatoriale", img: "https://flagcdn.com/gq.svg" },
    { country: "Érythrée", img: "https://flagcdn.com/er.svg" },
    { country: "Estonie", img: "https://flagcdn.com/ee.svg" },
    { country: "Eswatini", img: "https://flagcdn.com/sz.svg" },
    { country: "Éthiopie", img: "https://flagcdn.com/et.svg" },
    { country: "Îles Malouines", img: "https://flagcdn.com/fk.svg" },
    { country: "Îles Féroé", img: "https://flagcdn.com/fo.svg" },
    { country: "Fidji", img: "https://flagcdn.com/fj.svg" },
    { country: "Finlande", img: "https://flagcdn.com/fi.svg" },
    { country: "France", img: "https://flagcdn.com/fr.svg" },
    { country: "Guyane française", img: "https://flagcdn.com/gf.svg" },
    { country: "Polynésie française", img: "https://flagcdn.com/pf.svg" },
    { country: "Terres australes et antarctiques françaises", img: "https://flagcdn.com/tf.svg" },
    { country: "Gabon", img: "https://flagcdn.com/ga.svg" },
    { country: "Gambie", img: "https://flagcdn.com/gm.svg" },
    { country: "Géorgie", img: "https://flagcdn.com/ge.svg" },
    { country: "Allemagne", img: "https://flagcdn.com/de.svg" },
    { country: "Ghana", img: "https://flagcdn.com/gh.svg" },
    { country: "Gibraltar", img: "https://flagcdn.com/gi.svg" },
    { country: "Grèce", img: "https://flagcdn.com/gr.svg" },
    { country: "Groenland", img: "https://flagcdn.com/gl.svg" },
    { country: "Grenade", img: "https://flagcdn.com/gd.svg" },
    { country: "Guadeloupe", img: "https://flagcdn.com/gp.svg" },
    { country: "Guam", img: "https://flagcdn.com/gu.svg" },
    { country: "Guatemala", img: "https://flagcdn.com/gt.svg" },
    { country: "Guernesey", img: "https://flagcdn.com/gg.svg" },
    { country: "Guinée", img: "https://flagcdn.com/gn.svg" },
    { country: "Guinée-Bissau", img: "https://flagcdn.com/gw.svg" },
    { country: "Guyana", img: "https://flagcdn.com/gy.svg" },
    { country: "Haïti", img: "https://flagcdn.com/ht.svg" },
    { country: "Îles Heard-et-MacDonald", img: "https://flagcdn.com/hm.svg" },
    { country: "Vatican", img: "https://flagcdn.com/va.svg" },
    { country: "Honduras", img: "https://flagcdn.com/hn.svg" },
    { country: "Hong Kong", img: "https://flagcdn.com/hk.svg" },
    { country: "Hongrie", img: "https://flagcdn.com/hu.svg" },
    { country: "Islande", img: "https://flagcdn.com/is.svg" },
    { country: "Inde", img: "https://flagcdn.com/in.svg" },
    { country: "Indonésie", img: "https://flagcdn.com/id.svg" },
    { country: "Iran", img: "https://flagcdn.com/ir.svg" },
    { country: "Irak", img: "https://flagcdn.com/iq.svg" },
    { country: "Irlande", img: "https://flagcdn.com/ie.svg" },
    { country: "Île de Man", img: "https://flagcdn.com/im.svg" },
    { country: "Israël", img: "https://flagcdn.com/il.svg" },
    { country: "Italie", img: "https://flagcdn.com/it.svg" },
    { country: "Jamaïque", img: "https://flagcdn.com/jm.svg" },
    { country: "Japon", img: "https://flagcdn.com/jp.svg" },
    { country: "Jersey", img: "https://flagcdn.com/je.svg" },
    { country: "Jordanie", img: "https://flagcdn.com/jo.svg" },
    { country: "Kazakhstan", img: "https://flagcdn.com/kz.svg" },
    { country: "Kenya", img: "https://flagcdn.com/ke.svg" },
    { country: "Kiribati", img: "https://flagcdn.com/ki.svg" },
    { country: "Corée du Nord", img: "https://flagcdn.com/kp.svg" },
    { country: "Corée du Sud", img: "https://flagcdn.com/kr.svg" },
    { country: "Koweït", img: "https://flagcdn.com/kw.svg" },
    { country: "Kirghizistan", img: "https://flagcdn.com/kg.svg" },
    { country: "Laos", img: "https://flagcdn.com/la.svg" },
    { country: "Lettonie", img: "https://flagcdn.com/lv.svg" },
    { country: "Liban", img: "https://flagcdn.com/lb.svg" },
    { country: "Lesotho", img: "https://flagcdn.com/ls.svg" },
    { country: "Libéria", img: "https://flagcdn.com/lr.svg" },
    { country: "Libye", img: "https://flagcdn.com/ly.svg" },
    { country: "Liechtenstein", img: "https://flagcdn.com/li.svg" },
    { country: "Lituanie", img: "https://flagcdn.com/lt.svg" },
    { country: "Luxembourg", img: "https://flagcdn.com/lu.svg" },
    { country: "Macao", img: "https://flagcdn.com/mo.svg" },
    { country: "Madagascar", img: "https://flagcdn.com/mg.svg" },
    { country: "Malawi", img: "https://flagcdn.com/mw.svg" },
    { country: "Malaisie", img: "https://flagcdn.com/my.svg" },
    { country: "Maldives", img: "https://flagcdn.com/mv.svg" },
    { country: "Mali", img: "https://flagcdn.com/ml.svg" },
    { country: "Malte", img: "https://flagcdn.com/mt.svg" },
    { country: "Îles Marshall", img: "https://flagcdn.com/mh.svg" },
    { country: "Martinique", img: "https://flagcdn.com/mq.svg" },
    { country: "Mauritanie", img: "https://flagcdn.com/mr.svg" },
    { country: "Maurice", img: "https://flagcdn.com/mu.svg" },
    { country: "Mayotte", img: "https://flagcdn.com/yt.svg" },
    { country: "Mexique", img: "https://flagcdn.com/mx.svg" },
    { country: "Micronésie", img: "https://flagcdn.com/fm.svg" },
    { country: "Moldavie", img: "https://flagcdn.com/md.svg" },
    { country: "Monaco", img: "https://flagcdn.com/mc.svg" },
    { country: "Mongolie", img: "https://flagcdn.com/mn.svg" },
    { country: "Monténégro", img: "https://flagcdn.com/me.svg" },
    { country: "Montserrat", img: "https://flagcdn.com/ms.svg" },
    { country: "Maroc", img: "https://flagcdn.com/ma.svg" },
    { country: "Mozambique", img: "https://flagcdn.com/mz.svg" },
    { country: "Myanmar", img: "https://flagcdn.com/mm.svg" },
    { country: "Namibie", img: "https://flagcdn.com/na.svg" },
    { country: "Nauru", img: "https://flagcdn.com/nr.svg" },
    { country: "Népal", img: "https://flagcdn.com/np.svg" },
    { country: "Pays-Bas", img: "https://flagcdn.com/nl.svg" },
    { country: "Nouvelle-Calédonie", img: "https://flagcdn.com/nc.svg" },
    { country: "Nouvelle-Zélande", img: "https://flagcdn.com/nz.svg" },
    { country: "Nicaragua", img: "https://flagcdn.com/ni.svg" },
    { country: "Niger", img: "https://flagcdn.com/ne.svg" },
    { country: "Nigéria", img: "https://flagcdn.com/ng.svg" },
    { country: "Niue", img: "https://flagcdn.com/nu.svg" },
    { country: "Île Norfolk", img: "https://flagcdn.com/nf.svg" },
    { country: "Îles Mariannes du Nord", img: "https://flagcdn.com/mp.svg" },
    { country: "Norvège", img: "https://flagcdn.com/no.svg" },
    { country: "Oman", img: "https://flagcdn.com/om.svg" },
    { country: "Pakistan", img: "https://flagcdn.com/pk.svg" },
    { country: "Palaos", img: "https://flagcdn.com/pw.svg" },
    { country: "Palestine", img: "https://flagcdn.com/ps.svg" },
    { country: "Panama", img: "https://flagcdn.com/pa.svg" },
    { country: "Papouasie-Nouvelle-Guinée", img: "https://flagcdn.com/pg.svg" },
    { country: "Paraguay", img: "https://flagcdn.com/py.svg" },
    { country: "Pérou", img: "https://flagcdn.com/pe.svg" },
    { country: "Philippines", img: "https://flagcdn.com/ph.svg" },
    { country: "Pitcairn", img: "https://flagcdn.com/pn.svg" },
    { country: "Pologne", img: "https://flagcdn.com/pl.svg" },
    { country: "Portugal", img: "https://flagcdn.com/pt.svg" },
    { country: "Porto Rico", img: "https://flagcdn.com/pr.svg" },
    { country: "Qatar", img: "https://flagcdn.com/qa.svg" },
    { country: "La Réunion", img: "https://flagcdn.com/re.svg" },
    { country: "Roumanie", img: "https://flagcdn.com/ro.svg" },
    { country: "Russie", img: "https://flagcdn.com/ru.svg" },
    { country: "Rwanda", img: "https://flagcdn.com/rw.svg" },
    { country: "Saint-Barthélemy", img: "https://flagcdn.com/bl.svg" },
    { country: "Sainte-Hélène", img: "https://flagcdn.com/sh.svg" },
    { country: "Saint-Christophe-et-Niévès", img: "https://flagcdn.com/kn.svg" },
    { country: "Sainte-Lucie", img: "https://flagcdn.com/lc.svg" },
    { country: "Saint-Martin", img: "https://flagcdn.com/mf.svg" },
    { country: "Saint-Pierre-et-Miquelon", img: "https://flagcdn.com/pm.svg" },
    { country: "Saint-Vincent-et-les-Grenadines", img: "https://flagcdn.com/vc.svg" },
    { country: "Samoa", img: "https://flagcdn.com/ws.svg" },
    { country: "Saint-Marin", img: "https://flagcdn.com/sm.svg" },
    { country: "Sao Tomé-et-Principe", img: "https://flagcdn.com/st.svg" },
    { country: "Arabie saoudite", img: "https://flagcdn.com/sa.svg" },
    { country: "Sénégal", img: "https://flagcdn.com/sn.svg" },
    { country: "Serbie", img: "https://flagcdn.com/rs.svg" },
    { country: "Seychelles", img: "https://flagcdn.com/sc.svg" },
    { country: "Sierra Leone", img: "https://flagcdn.com/sl.svg" },
    { country: "Singapour", img: "https://flagcdn.com/sg.svg" },
    { country: "Sint Maarten", img: "https://flagcdn.com/sx.svg" },
    { country: "Slovaquie", img: "https://flagcdn.com/sk.svg" },
    { country: "Slovénie", img: "https://flagcdn.com/si.svg" },
    { country: "Îles Salomon", img: "https://flagcdn.com/sb.svg" },
    { country: "Somalie", img: "https://flagcdn.com/so.svg" },
    { country: "Afrique du Sud", img: "https://flagcdn.com/za.svg" },
    { country: "Géorgie du Sud-et-les Îles Sandwich du Sud", img: "https://flagcdn.com/gs.svg" },
    { country: "Soudan du Sud", img: "https://flagcdn.com/ss.svg" },
    { country: "Espagne", img: "https://flagcdn.com/es.svg" },
    { country: "Sri Lanka", img: "https://flagcdn.com/lk.svg" },
    { country: "Soudan", img: "https://flagcdn.com/sd.svg" },
    { country: "Suriname", img: "https://flagcdn.com/sr.svg" },
    { country: "Svalbard et Jan Mayen", img: "https://flagcdn.com/sj.svg" },
    { country: "Suède", img: "https://flagcdn.com/se.svg" },
    { country: "Suisse", img: "https://flagcdn.com/ch.svg" },
    { country: "Syrie", img: "https://flagcdn.com/sy.svg" },
    { country: "Taïwan", img: "https://flagcdn.com/tw.svg" },
    { country: "Tadjikistan", img: "https://flagcdn.com/tj.svg" },
    { country: "Tanzanie", img: "https://flagcdn.com/tz.svg" },
    { country: "Thaïlande", img: "https://flagcdn.com/th.svg" },
    { country: "Timor oriental", img: "https://flagcdn.com/tl.svg" },
    { country: "Togo", img: "https://flagcdn.com/tg.svg" },
    { country: "Tokelau", img: "https://flagcdn.com/tk.svg" },
    { country: "Tonga", img: "https://flagcdn.com/to.svg" },
    { country: "Trinité-et-Tobago", img: "https://flagcdn.com/tt.svg" },
    { country: "Tunisie", img: "https://flagcdn.com/tn.svg" },
    { country: "Turquie", img: "https://flagcdn.com/tr.svg" },
    { country: "Turkménistan", img: "https://flagcdn.com/tm.svg" },
    { country: "Îles Turques-et-Caïques", img: "https://flagcdn.com/tc.svg" },
    { country: "Tuvalu", img: "https://flagcdn.com/tv.svg" },
    { country: "Ouganda", img: "https://flagcdn.com/ug.svg" },
    { country: "Ukraine", img: "https://flagcdn.com/ua.svg" },
    { country: "Émirats arabes unis", img: "https://flagcdn.com/ae.svg" },
    { country: "Royaume-Uni", img: "https://flagcdn.com/gb.svg" },
    { country: "États-Unis", img: "https://flagcdn.com/us.svg" },
    { country: "Îles mineures éloignées des États-Unis", img: "https://flagcdn.com/um.svg" },
    { country: "Uruguay", img: "https://flagcdn.com/uy.svg" },
    { country: "Ouzbékistan", img: "https://flagcdn.com/uz.svg" },
    { country: "Vanuatu", img: "https://flagcdn.com/vu.svg" },
    { country: "Venezuela", img: "https://flagcdn.com/ve.svg" },
    { country: "Viêt Nam", img: "https://flagcdn.com/vn.svg" },
    { country: "Wallis-et-Futuna", img: "https://flagcdn.com/wf.svg" },
    { country: "Sahara occidental", img: "https://flagcdn.com/eh.svg" },
    { country: "Yémen", img: "https://flagcdn.com/ye.svg" },
    { country: "Zambie", img: "https://flagcdn.com/zm.svg" },
    { country: "Zimbabwe", img: "https://flagcdn.com/zw.svg" },
    { country: "Kosovo", img: "https://flagcdn.com/xk.svg" }
];
