window.RECIPES_DB = [
  { name: "Kimchi Jjigae", ingredients: ["kimchi", "pork", "tofu", "onion", "green onion", "garlic", "gochugaru", "gochujang", "soy sauce"] },
  { name: "Bibimbap", ingredients: ["rice", "beef", "spinach", "bean sprouts", "carrot", "zucchini", "egg", "gochujang", "seaweed"] },
  { name: "Bulgogi", ingredients: ["beef", "soy sauce", "onion", "pear", "sugar", "sesame oil", "garlic", "green onion", "black pepper"] },
  { name: "Japchae", ingredients: ["glass noodles", "beef", "spinach", "carrot", "onion", "mushroom", "egg", "soy sauce", "sesame oil"] },
  { name: "Tteokbokki", ingredients: ["rice cake", "fish cake", "onion", "green onion", "gochujang", "sugar", "soy sauce", "garlic", "boiled egg"] },
  { name: "Sundubu Jjigae", ingredients: ["soft tofu", "pork", "egg", "zucchini", "onion", "green onion", "garlic", "gochugaru", "soy sauce"] },
  { name: "Samgyeopsal", ingredients: ["pork belly", "lettuce", "garlic", "ssamjang", "green onion", "salt", "pepper"] },
  { name: "Kimchi Fried Rice", ingredients: ["kimchi", "rice", "egg", "pork", "green onion", "soy sauce", "sesame oil"] },
  { name: "Galbi Jjim", ingredients: ["beef short ribs", "onion", "carrot", "potato", "soy sauce", "sugar", "pear", "garlic", "sesame oil"] },
  { name: "Jajangmyeon", ingredients: ["noodle", "pork", "onion", "zucchini", "potato", "black bean paste", "cucumber", "egg"] },
  { name: "Sushi", ingredients: ["rice", "vinegar", "sugar", "salt", "nori", "salmon", "tuna", "shrimp", "avocado", "cucumber"] },
  { name: "Ramen", ingredients: ["noodle", "pork", "egg", "green onion", "bamboo shoot", "nori", "soy sauce", "miso", "garlic"] },
  { name: "Katsudon", ingredients: ["rice", "pork cutlet", "egg", "onion", "soy sauce", "sugar", "mirin"] },
  { name: "Okonomiyaki", ingredients: ["flour", "egg", "cabbage", "pork", "shrimp", "green onion", "mayonnaise", "okonomiyaki sauce"] },
  { name: "Mapo Tofu", ingredients: ["tofu", "ground pork", "green onion", "garlic", "ginger", "soy sauce", "doubanjiang", "Sichuan pepper"] },
  { name: "Peking Duck", ingredients: ["duck", "cucumber", "spring onion", "hoisin sauce", "pancake"] },
  { name: "Sweet and Sour Pork", ingredients: ["pork", "pineapple", "bell pepper", "onion", "vinegar", "sugar", "ketchup", "soy sauce"] },
  { name: "Pad Thai", ingredients: ["rice noodle", "shrimp", "egg", "tofu", "bean sprout", "peanut", "tamarind", "fish sauce", "lime"] },
  { name: "Tom Yum Goong", ingredients: ["shrimp", "lemongrass", "lime", "galangal", "mushroom", "chili", "fish sauce", "coriander"] },
  { name: "Pho", ingredients: ["rice noodle", "beef", "onion", "ginger", "cinnamon", "clove", "fish sauce", "bean sprout", "lime", "basil"] },
  { name: "Hainanese Chicken Rice", ingredients: ["chicken", "rice", "ginger", "garlic", "cucumber", "soy sauce", "chili sauce"] },
  { name: "Spring Rolls", ingredients: ["rice paper", "shrimp", "pork", "lettuce", "rice noodle", "mint", "coriander"] },
  { name: "Green Curry", ingredients: ["chicken", "green curry paste", "coconut milk", "eggplant", "basil", "fish sauce", "sugar"] },
  { name: "Nasi Goreng", ingredients: ["rice", "chicken", "egg", "soy sauce", "shrimp", "green onion", "chili"] },
  { name: "Satay", ingredients: ["chicken", "peanut", "soy sauce", "lemongrass", "garlic", "turmeric"] },
  { name: "Laksa", ingredients: ["rice noodle", "shrimp", "coconut milk", "tofu", "bean sprout", "egg", "chili", "coriander"] },
  { name: "Chow Mein", ingredients: ["noodle", "chicken", "bean sprout", "cabbage", "carrot", "soy sauce", "green onion"] },
  { name: "Fried Rice", ingredients: ["rice", "egg", "carrot", "pea", "green onion", "shrimp", "soy sauce"] },
  { name: "Gyoza", ingredients: ["flour", "cabbage", "pork", "garlic", "ginger", "green onion", "soy sauce"] },
  { name: "Unagi Don", ingredients: ["rice", "eel", "soy sauce", "mirin", "sugar", "egg"] },
  { name: "Hamburger", ingredients: ["beef", "bun", "lettuce", "tomato", "onion", "cheese", "pickle"] },
  { name: "Cheeseburger", ingredients: ["beef", "bun", "cheese", "lettuce", "tomato", "onion", "pickle"] },
  { name: "Fried Chicken", ingredients: ["chicken", "flour", "egg", "oil", "salt", "pepper"] },
  { name: "BBQ Ribs", ingredients: ["pork ribs", "bbq sauce", "brown sugar", "salt", "pepper", "garlic powder"] },
  { name: "Caesar Salad", ingredients: ["lettuce", "parmesan", "crouton", "anchovy", "egg", "caesar dressing"] },
  { name: "BLT Sandwich", ingredients: ["bread", "bacon", "lettuce", "tomato", "mayonnaise"] },
  { name: "Spaghetti Carbonara", ingredients: ["spaghetti", "egg", "parmesan", "pancetta", "black pepper"] },
  { name: "Lasagna", ingredients: ["lasagna noodles", "ground beef", "tomato sauce", "ricotta", "mozzarella", "parmesan", "egg"] },
  { name: "Margherita Pizza", ingredients: ["pizza dough", "tomato sauce", "mozzarella", "basil", "olive oil"] },
  { name: "Paella", ingredients: ["rice", "shrimp", "mussel", "chicken", "chorizo", "peas", "saffron", "paprika", "bell pepper"] },
  { name: "Croque Monsieur", ingredients: ["bread", "ham", "cheese", "butter", "milk", "flour", "mustard"] },
  { name: "Quiche Lorraine", ingredients: ["pie crust", "egg", "bacon", "cheese", "cream", "onion"] },
  { name: "Ratatouille", ingredients: ["eggplant", "zucchini", "bell pepper", "tomato", "onion", "garlic"] },
  { name: "Bouillabaisse", ingredients: ["fish", "mussel", "shrimp", "tomato", "garlic", "onion", "fennel", "saffron"] },
  { name: "Crepe", ingredients: ["flour", "egg", "milk", "butter", "sugar", "salt"] },
  { name: "Tortilla Espanola", ingredients: ["egg", "potato", "onion", "olive oil", "salt"] },
  { name: "Gazpacho", ingredients: ["tomato", "cucumber", "bell pepper", "onion", "garlic", "olive oil", "vinegar"] },
  { name: "Patatas Bravas", ingredients: ["potato", "olive oil", "paprika", "tomato", "aioli"] },
  { name: "Churros", ingredients: ["flour", "egg", "butter", "sugar", "salt", "oil", "cinnamon"] },
  { name: "Tuna Nicoise Salad", ingredients: ["lettuce", "tuna", "egg", "potato", "green bean", "olive", "tomato", "anchovy"] },
  { name: "Tacos", ingredients: ["tortilla", "beef", "lettuce", "tomato", "cheese", "onion", "sour cream", "guacamole"] },
  { name: "Enchiladas", ingredients: ["tortilla", "chicken", "cheese", "onion", "enchilada sauce", "sour cream"] },
  { name: "Burrito", ingredients: ["tortilla", "rice", "bean", "beef", "lettuce", "cheese", "salsa"] },
  { name: "Ceviche", ingredients: ["fish", "lime", "onion", "chili", "cilantro", "tomato"] },
  { name: "Feijoada", ingredients: ["black bean", "pork", "beef", "sausage", "rice", "onion", "garlic"] },
  { name: "Empanada", ingredients: ["flour", "beef", "onion", "egg", "olive", "raisin", "paprika"] },
  { name: "Moussaka", ingredients: ["eggplant", "potato", "ground beef", "tomato", "onion", "bechamel sauce"] },
  { name: "Greek Salad", ingredients: ["tomato", "cucumber", "olive", "feta", "onion", "olive oil"] },
  { name: "Shakshuka", ingredients: ["egg", "tomato", "bell pepper", "onion", "garlic", "cumin", "paprika"] },
  { name: "Falafel", ingredients: ["chickpea", "onion", "garlic", "parsley", "coriander", "cumin", "flour"] },
  { name: "Hummus", ingredients: ["chickpea", "tahini", "garlic", "lemon", "olive oil"] },
  { name: "Shawarma", ingredients: ["chicken", "beef", "pita", "lettuce", "tomato", "onion", "yogurt", "garlic"] },
  { name: "Couscous", ingredients: ["couscous", "chicken", "carrot", "zucchini", "chickpea", "onion"] },
  { name: "Tagine", ingredients: ["lamb", "apricot", "almond", "onion", "cinnamon", "coriander", "saffron"] },
  { name: "Butter Chicken", ingredients: ["chicken", "butter", "cream", "tomato", "onion", "garam masala"] },
  { name: "Tandoori Chicken", ingredients: ["chicken", "yogurt", "garam masala", "cumin", "garlic", "ginger", "chili"] },
  { name: "Palak Paneer", ingredients: ["spinach", "paneer", "cream", "onion", "tomato", "garlic", "cumin"] },
  { name: "Dal Tadka", ingredients: ["lentil", "onion", "tomato", "garlic", "ginger", "cumin", "turmeric", "ghee"] },
  { name: "Biryani", ingredients: ["rice", "chicken", "yogurt", "onion", "garam masala", "saffron"] },
  { name: "Samosa", ingredients: ["flour", "potato", "pea", "onion", "cumin", "coriander"] },
  { name: "Fettuccine Alfredo", ingredients: ["fettuccine", "butter", "cream", "parmesan"] },
  { name: "Chicken Parmesan", ingredients: ["chicken", "egg", "bread crumb", "parmesan", "mozzarella", "tomato sauce"] },
  { name: "Beef Stroganoff", ingredients: ["beef", "onion", "mushroom", "sour cream", "butter", "flour"] },
  { name: "Eggs Benedict", ingredients: ["egg", "english muffin", "ham", "hollandaise sauce", "butter"] },
  { name: "Lobster Bisque", ingredients: ["lobster", "cream", "butter", "onion", "celery", "carrot", "cognac"] },
  { name: "Clam Chowder", ingredients: ["clam", "potato", "onion", "celery", "bacon", "cream", "butter"] },
  { name: "Chicken Pot Pie", ingredients: ["chicken", "carrot", "potato", "peas", "onion", "pie crust", "cream"] },
  { name: "Meatloaf", ingredients: ["beef", "egg", "bread crumb", "onion", "ketchup", "mustard"] },
  { name: "French Toast", ingredients: ["bread", "egg", "milk", "cinnamon", "sugar", "butter"] },
  { name: "Pancakes", ingredients: ["flour", "egg", "milk", "baking powder", "sugar", "butter"] },
  { name: "Waffles", ingredients: ["flour", "egg", "milk", "baking powder", "sugar", "butter"] },
  { name: "Banana Bread", ingredients: ["banana", "flour", "egg", "sugar", "butter"] },
  { name: "Apple Pie", ingredients: ["apple", "flour", "egg", "sugar", "butter", "cinnamon"] },
  { name: "Lemon Tart", ingredients: ["lemon", "egg", "sugar", "butter", "flour"] },
  { name: "Brownie", ingredients: ["chocolate", "flour", "egg", "sugar", "butter"] },
  { name: "Cheesecake", ingredients: ["cream cheese", "egg", "sugar", "butter", "graham cracker"] },
  { name: "Pumpkin Soup", ingredients: ["pumpkin", "onion", "garlic", "cream", "butter"] },
  { name: "Minestrone Soup", ingredients: ["bean", "carrot", "celery", "onion", "tomato", "pasta"] },
  { name: "Omelette", ingredients: ["egg", "milk", "cheese", "ham", "onion", "bell pepper"] },
  { name: "Scrambled Eggs", ingredients: ["egg", "milk", "butter", "salt", "pepper"] },
  { name: "Quesadilla", ingredients: ["tortilla", "cheese", "chicken", "bell pepper", "onion"] },
  { name: "Fajita", ingredients: ["beef", "onion", "bell pepper", "tortilla", "sour cream"] },
  { name: "Pulled Pork", ingredients: ["pork", "bbq sauce", "brown sugar", "onion", "bun"] },
  { name: "Fish and Chips", ingredients: ["fish", "potato", "flour", "egg", "oil"] },
  { name: "Shepherd's Pie", ingredients: ["ground lamb", "potato", "carrot", "onion", "peas", "gravy"] },
  { name: "Steak", ingredients: ["beef", "salt", "pepper", "butter", "garlic"] },
  { name: "Lamb Chops", ingredients: ["lamb", "salt", "pepper", "garlic", "rosemary"] },
  { name: "Roast Chicken", ingredients: ["chicken", "salt", "pepper", "garlic", "thyme", "olive oil"] },
  { name: "Chicken Curry", ingredients: ["chicken", "onion", "tomato", "garlic", "ginger", "curry powder", "coconut milk"] },
  { name: "Shrimp Scampi", ingredients: ["shrimp", "garlic", "butter", "lemon", "parsley", "spaghetti"] },
  { name: "Seafood Paella", ingredients: ["rice", "shrimp", "mussel", "squid", "peas", "saffron"] },
  { name: "Cacciatore", ingredients: ["chicken", "tomato", "onion", "bell pepper", "mushroom", "garlic"] },
  { name: "Bouef en Daube", ingredients: ["beef", "red wine", "onion", "carrot", "celery", "garlic", "thyme"] },
  { name: "Goulash", ingredients: ["beef", "onion", "paprika", "tomato", "bell pepper", "garlic"] },
  { name: "Borscht", ingredients: ["beet", "cabbage", "potato", "carrot", "onion", "dill"] },
  { name: "Pierogi", ingredients: ["flour", "egg", "potato", "cheese", "onion", "butter"] },
  { name: "Baklava", ingredients: ["phyllo", "walnut", "pistachio", "sugar", "butter", "honey"] },
  { name: "Dolma", ingredients: ["grape leaf", "rice", "onion", "pine nut", "dill"] },
  { name: "Cabbage Roll", ingredients: ["cabbage", "beef", "rice", "onion", "tomato sauce"] },
  { name: "Irish Stew", ingredients: ["lamb", "potato", "carrot", "onion", "celery"] },
  { name: "Cassoulet", ingredients: ["white bean", "pork", "duck", "sausage", "onion", "garlic"] },
  { name: "Bourekas", ingredients: ["phyllo", "cheese", "potato", "egg", "sesame seed"] },
  { name: "Sauerbraten", ingredients: ["beef", "onion", "carrot", "celery", "vinegar", "ginger"] },
  { name: "Wiener Schnitzel", ingredients: ["veal", "egg", "flour", "bread crumb", "lemon"] },
  { name: "Zwiebelrostbraten", ingredients: ["beef", "onion", "butter", "flour", "beef broth"] },
  { name: "Rosti", ingredients: ["potato", "butter", "onion", "bacon"] },
  { name: "Spaetzle", ingredients: ["flour", "egg", "milk", "butter"] },
  { name: "Goulash Soup", ingredients: ["beef", "onion", "paprika", "potato", "carrot"] },
  { name: "Chicken Kiev", ingredients: ["chicken", "butter", "garlic", "parsley", "egg", "flour", "bread crumb"] },
  { name: "Plov", ingredients: ["rice", "beef", "carrot", "onion", "cumin"] },
  { name: "Manti", ingredients: ["flour", "egg", "beef", "onion", "yogurt"] },
  { name: "Peking Noodle Soup", ingredients: ["noodle", "pork", "egg", "green onion", "soy sauce"] },
  { name: "Jollof Rice", ingredients: ["rice", "tomato", "onion", "bell pepper", "chili", "garlic"] },
  { name: "Bobotie", ingredients: ["beef", "bread", "egg", "onion", "milk", "curry powder"] },
  { name: "Bunny Chow", ingredients: ["bread", "chicken", "onion", "tomato", "curry powder"] },
  { name: "Chakalaka", ingredients: ["bean", "onion", "tomato", "chili", "carrot", "bell pepper"] },
  { name: "Pav Bhaji", ingredients: ["bread", "potato", "pea", "carrot", "onion", "tomato", "butter"] },
  { name: "Vada Pav", ingredients: ["bread", "potato", "chili", "coriander", "garlic", "mustard seed"] },
  { name: "Masala Dosa", ingredients: ["rice", "lentil", "potato", "onion", "mustard seed", "curry leaf"] },
  { name: "Idli", ingredients: ["rice", "lentil", "salt"] },
  { name: "Sambar", ingredients: ["lentil", "carrot", "onion", "tomato", "eggplant", "drumstick", "spice mix"] },
  { name: "Katsu Curry", ingredients: ["rice", "pork cutlet", "curry sauce", "onion", "carrot", "potato"] },
  { name: "Okonomiyaki", ingredients: ["flour", "egg", "cabbage", "pork", "shrimp", "mayonnaise", "okonomiyaki sauce"] },
  { name: "Takoyaki", ingredients: ["flour", "egg", "octopus", "green onion", "tempura bits", "mayonnaise", "takoyaki sauce"] },
  { name: "Sukiyaki", ingredients: ["beef", "tofu", "green onion", "shiitake", "konjac", "egg"] },
  { name: "Nabe", ingredients: ["cabbage", "tofu", "shiitake", "carrot", "chicken", "udon"] },
  { name: "Egg Drop Soup", ingredients: ["egg", "chicken broth", "cornstarch", "green onion", "soy sauce"] },
  { name: "Hot and Sour Soup", ingredients: ["tofu", "egg", "mushroom", "bamboo shoot", "vinegar", "soy sauce", "pepper"] },
  { name: "Beef and Broccoli", ingredients: ["beef", "broccoli", "soy sauce", "garlic", "ginger", "onion"] },
  { name: "Lemon Chicken", ingredients: ["chicken", "lemon", "egg", "flour", "soy sauce", "sugar"] },
  { name: "Pineapple Fried Rice", ingredients: ["rice", "pineapple", "shrimp", "egg", "cashew", "green onion"] },
  { name: "Banh Mi", ingredients: ["baguette", "pork", "carrot", "cucumber", "cilantro", "mayonnaise", "pate"] },
  { name: "Khao Soi", ingredients: ["egg noodle", "chicken", "coconut milk", "curry paste", "pickled mustard"] },
  { name: "Bak Kut Teh", ingredients: ["pork rib", "garlic", "soy sauce", "white pepper", "mushroom"] },
  { name: "Hainanese Chicken Rice", ingredients: ["chicken", "rice", "ginger", "garlic", "cucumber", "soy sauce", "chili sauce"] },
  { name: "Singapore Laksa", ingredients: ["rice noodle", "shrimp", "coconut milk", "tofu", "bean sprout", "egg", "chili", "coriander"] },
  { name: "Gado-Gado", ingredients: ["vegetable", "tofu", "egg", "peanut sauce", "bean sprout"] },
  { name: "Nasi Lemak", ingredients: ["rice", "coconut milk", "egg", "anchovy", "peanut", "cucumber", "sambal"] },
  { name: "Arugula Pesto Pasta", ingredients: ["arugula", "pasta", "parmesan", "olive oil", "pine nut"] },
  { name: "Shakshuka with Feta", ingredients: ["egg", "tomato", "bell pepper", "onion", "feta cheese", "coriander"] },
  { name: "Buttermilk Pancakes", ingredients: ["flour", "egg", "buttermilk", "sugar", "baking powder"] },
  { name: "Quinoa Salad", ingredients: ["quinoa", "cucumber", "tomato", "feta cheese", "lemon", "olive oil"] },
  { name: "Kale Caesar Salad", ingredients: ["kale", "parmesan", "crouton", "anchovy", "egg", "caesar dressing"] },
  { name: "Vegan Buddha Bowl", ingredients: ["brown rice", "chickpea", "avocado", "spinach", "carrot", "tofu"] },
  { name: "Eggplant Parmesan", ingredients: ["eggplant", "tomato sauce", "mozzarella", "parmesan", "basil"] },
  { name: "Stuffed Bell Peppers", ingredients: ["bell pepper", "rice", "ground beef", "onion", "tomato", "cheese"] },
  { name: "Grilled Lamb Chops", ingredients: ["lamb", "garlic", "rosemary", "olive oil", "salt", "pepper"] },
  { name: "Lentil Soup", ingredients: ["lentil", "carrot", "celery", "onion", "tomato", "garlic"] },
  { name: "Roasted Brussels Sprouts", ingredients: ["brussels sprout", "olive oil", "salt", "pepper", "lemon"] },
  { name: "Pesto Chicken", ingredients: ["chicken", "basil pesto", "parmesan", "olive oil"] },
  { name: "Mango Salsa", ingredients: ["mango", "onion", "lime", "cilantro", "chili"] },
  { name: "Baked Cod", ingredients: ["cod", "lemon", "olive oil", "parsley", "bread crumb"] },
  { name: "Asian Slaw", ingredients: ["napa cabbage", "carrot", "green onion", "soy sauce", "rice vinegar", "sesame oil"] },
  { name: "Peanut Noodle Salad", ingredients: ["noodle", "peanut", "carrot", "cucumber", "soy sauce", "sesame oil"] },
  { name: "Vegan Chili", ingredients: ["black bean", "tomato", "onion", "chili powder", "corn", "bell pepper"] },
  { name: "Gado-Gado Salad", ingredients: ["vegetable", "tofu", "egg", "peanut sauce", "bean sprout"] },
  { name: "Jackfruit Tacos", ingredients: ["jackfruit", "tortilla", "cabbage", "lime", "avocado", "cilantro"] },
  { name: "Tofu Stir-Fry", ingredients: ["tofu", "broccoli", "bell pepper", "soy sauce", "ginger", "garlic"] },
  { name: "Pumpkin Risotto", ingredients: ["pumpkin", "rice", "parmesan", "onion", "garlic"] },
  { name: "Ratatouille Toast", ingredients: ["eggplant", "zucchini", "bell pepper", "onion", "bread"] },
  { name: "Beetroot Salad", ingredients: ["beet", "arugula", "walnut", "goat cheese", "balsamic"] },
  { name: "Moroccan Tagine", ingredients: ["lamb", "apricot", "almond", "onion", "cinnamon", "coriander", "saffron"] },
  { name: "Chimichurri Steak", ingredients: ["beef", "parsley", "garlic", "olive oil", "oregano", "vinegar"] },
  { name: "Zucchini Fritters", ingredients: ["zucchini", "egg", "flour", "parmesan", "green onion"] },
  { name: "Miso Soup", ingredients: ["miso", "tofu", "wakame", "green onion", "dashi"] },
  { name: "Falafel Wrap", ingredients: ["falafel", "pita", "lettuce", "tomato", "tahini"] },
  { name: "Prawn Laksa", ingredients: ["shrimp", "rice noodle", "coconut milk", "laksa paste", "egg", "bean sprout"] },
  { name: "Couscous Bowl", ingredients: ["couscous", "chickpea", "carrot", "zucchini", "lemon"] },
];


window.INGREDIENTS_DB = [
  "egg","chicken","beef","pork","onion","garlic","carrot","potato","spaghetti","rice","tomato","lettuce",
  "tofu","bean sprouts","peanut","red wine","miso","seaweed","kimchi","bacon","parmesan","anchovy","bun",
  "cheese","shrimp","lemongrass","galangal","lime","bell pepper","eggplant","zucchini","crouton","dashi",
  "pancetta","black pepper","mushroom","yogurt","flour","sugar","salt","butter","milk","cream","cucumber",
  "apple","banana","orange","lemon","lime","broccoli","spinach","pumpkin","sweet potato","corn","peas",
  "cabbage","celery","ginger","soy sauce","vinegar","olive oil","canola oil","sunflower oil","sesame oil",
  "fish sauce","oyster sauce","hoisin sauce","ketchup","mustard","mayonnaise","basil","cilantro","parsley",
  "rosemary","thyme","sage","mint","cinnamon","nutmeg","cloves","bay leaf","star anise","cardamom",
  "curry powder","chili powder","paprika","turmeric","cumin","coriander","dill","fennel","vanilla",
  "chocolate","cocoa powder","jam","honey","maple syrup","molasses","strawberry","blueberry","raspberry",
  "cranberry","blackberry","pineapple","mango","kiwi","grape","pear","peach","apricot","plum","date",
  "fig","coconut","walnut","almond","hazelnut","cashew","pistachio","macadamia","pecan","sunflower seed",
  "chia seed","pumpkin seed","sesame seed","quinoa","barley","millet","buckwheat","oats","bread","pasta",
  "noodle","tortilla","naan","pita","sourdough","bagel","croissant","donut","pizza dough","crackers",
  "sausage","salami","ham","duck","lamb","turkey","rabbit","veal","goose","anchovy","sardine","tuna",
  "mackerel","salmon","cod","haddock","pollock","catfish","tilapia","squid","octopus","clam","mussel",
  "scallop","lobster","crab","crayfish","abalone","sea cucumber","sea urchin","wasabi","horseradish",
  "tabasco","sriracha","gochujang","ssamjang","doenjang","miso paste","red bean","black bean","soybean",
  "chickpea","lentil","kidney bean","navy bean","green bean","snap pea","snow pea","edamame","mozzarella",
  "cheddar","gouda","brie","camembert","feta","blue cheese","swiss cheese","provolone","ricotta",
  "mascarpone","cream cheese","cottage cheese","sour cream","yogurt","buttermilk","evaporated milk",
  "condensed milk","powdered milk","almond milk","soy milk","rice milk","coconut milk","oat milk",
  "shrimp paste","anchovy paste","tomato paste","tomato sauce","pesto","piri piri","harissa","ajvar",
  "tahini","hummus","guacamole","salsa","relish","tapenade","gravy","stock","bouillon","broth","gelatin",
  "agar","cornstarch","potato starch","tapioca starch","arrowroot","rice flour","semolina","cornmeal",
  "polenta","wheat germ","bran","rice paper","spring roll wrapper","nori","rice cake","udon","ramen",
  "vermicelli","soba","fettuccine","penne","macaroni","lasagna","spaghetti","linguine","angel hair",
  "gnocchi","ravioli","tortellini","dumpling","wonton","pierogi","empanada","tamale","spring onion",
  "shallot","leek","turnip","radish","parsnip","rutabaga","beet","swede","daikon","jicama","lotus root",
  "artichoke","asparagus","okra","bamboo shoot","egg yolk","egg white","quail egg","duck egg","goose egg",
  "truffle","morel","porcini","enoki","shiitake","maitake","king oyster","button mushroom","portobello",
  "chestnut","water chestnut","taro","yam","cassava","salsify","jerusalem artichoke","fennel bulb",
  "arugula", "basil pesto", "bell pepper", "bok choy", "brussels sprout", "buttermilk", "caper",
  "caramel", "caraway", "cashew nut", "chia", "chili oil", "chive", "coriander seed", "cottage cheese",
  "crab", "cranberry", "cream", "cress", "dandelion", "dates", "egg roll wrapper", "farro", "fenugreek",
  "feta cheese", "ghee", "goat cheese", "green bean", "guava", "hazelnut", "hemp seed", "herb mix",
  "jackfruit", "kale", "kimchi juice", "kumquat", "leek", "lentil pasta", "lychee", "mango chutney",
  "manchego", "maple bacon", "marjoram", "mizuna", "monk fruit", "mushroom sauce", "mustard green",
  "napa cabbage", "nectarine", "okra", "olive", "orange zest", "papaya", "passionfruit", "pea shoot",
  "pecan", "pepper jack", "persimmon", "pine nut", "pistachio cream", "plum tomato", "popcorn", "prosciutto",
  "pumpernickel", "quark", "radicchio", "ras el hanout", "red lentil", "ricotta salata", "rocket", "romaine",
  "roquefort", "rosewater", "rutabaga", "sago", "salsify", "savoy cabbage", "scallion", "shallot",
  "shiso", "silken tofu", "smoked salmon", "snap pea", "snow pea", "sorrel", "soy protein", "spelt",
  "squid ink", "stilton", "straw mushroom", "sumac", "sun-dried tomato", "sweetcorn", "swiss chard",
  "tamarind", "tempeh", "thyme", "toasted sesame", "tofu skin", "tomatillo", "truffle oil", "turnip green",
  "valencia orange", "vegan cheese", "venison", "vermicelli", "vinegar rice", "watercress", "wheatberry",
  "white chocolate", "wild rice", "yam", "za'atar", "zest", "zucchini blossom", "adzuki bean", "amarant",
  "anise", "bamboo shoot", "banana pepper", "basil seed", "bay scallop", "black garlic", "blood orange",
  "borage", "bresaola", "cactus", "calamari", "canary melon", "candied ginger", "carrot top", "cassava flour",
  "celeriac", "chayote", "chestnut mushroom", "chorizo", "cloudberry", "coconut sugar", "confit garlic",
  "corn salad", "cranberry bean", "cremini", "dulse", "eddo", "fiddlehead", "fish roe", "frisée", "garam masala",
  "garlic chive", "goji berry", "golden beet", "green garlic", "guanciale", "ham hock", "horseradish root",
  "jerusalem artichoke", "kaffir lime", "kanpyo", "kombu", "lardon", "lavender", "limoncello", "long bean",
  "lotus seed", "miso caramel", "mizithra", "mulberry", "muscadine", "nasturtium", "nettles", "okra leaf",
  "olallieberry", "parsnip leaf", "pattypan squash", "pecorino", "pepino melon", "perilla leaf", "pickled radish",
  "pigeon pea", "pineapple sage", "pink peppercorn", "pluot", "poblano", "purslane", "quince", "ramps",
  "rhubarb", "roasted garlic", "romanesco", "runner bean", "rutabaga leaf", "salmon roe", "satsuma", "sea asparagus"
];