const flags = [
    { country: "Afeganistão", img: "https://flagcdn.com/af.svg" },
    { country: "Ilhas Åland", img: "https://flagcdn.com/ax.svg" },
    { country: "Albânia", img: "https://flagcdn.com/al.svg" },
    { country: "Argélia", img: "https://flagcdn.com/dz.svg" },
    { country: "Samoa Americana", img: "https://flagcdn.com/as.svg" },
    { country: "Andorra", img: "https://flagcdn.com/ad.svg" },
    { country: "Angola", img: "https://flagcdn.com/ao.svg" },
    { country: "Anguilla", img: "https://flagcdn.com/ai.svg" },
    { country: "Antártida", img: "https://flagcdn.com/aq.svg" },
    { country: "Antígua e Barbuda", img: "https://flagcdn.com/ag.svg" },
    { country: "Argentina", img: "https://flagcdn.com/ar.svg" },
    { country: "Armênia", img: "https://flagcdn.com/am.svg" },
    { country: "Aruba", img: "https://flagcdn.com/aw.svg" },
    { country: "Austrália", img: "https://flagcdn.com/au.svg" },
    { country: "Áustria", img: "https://flagcdn.com/at.svg" },
    { country: "Azerbaijão", img: "https://flagcdn.com/az.svg" },
    { country: "Bahamas", img: "https://flagcdn.com/bs.svg" },
    { country: "Bahrein", img: "https://flagcdn.com/bh.svg" },
    { country: "Bangladesh", img: "https://flagcdn.com/bd.svg" },
    { country: "Barbados", img: "https://flagcdn.com/bb.svg" },
    { country: "Bielorrússia", img: "https://flagcdn.com/by.svg" },
    { country: "Bélgica", img: "https://flagcdn.com/be.svg" },
    { country: "Belize", img: "https://flagcdn.com/bz.svg" },
    { country: "Benin", img: "https://flagcdn.com/bj.svg" },
    { country: "Bermudas", img: "https://flagcdn.com/bm.svg" },
    { country: "Butão", img: "https://flagcdn.com/bt.svg" },
    { country: "Bolívia", img: "https://flagcdn.com/bo.svg" },
    { country: "Caribe Neerlandês", img: "https://flagcdn.com/bq.svg" },
    { country: "Bósnia e Herzegovina", img: "https://flagcdn.com/ba.svg" },
    { country: "Botswana", img: "https://flagcdn.com/bw.svg" },
    { country: "Ilha Bouvet", img: "https://flagcdn.com/bv.svg" },
    { country: "Brasil", img: "https://flagcdn.com/br.svg" },
    { country: "Território Britânico do Oceano Índico", img: "https://flagcdn.com/io.svg" },
    { country: "Ilhas Virgens Britânicas", img: "https://flagcdn.com/vg.svg" },
    { country: "Brunei", img: "https://flagcdn.com/bn.svg" },
    { country: "Bulgária", img: "https://flagcdn.com/bg.svg" },
    { country: "Burkina Faso", img: "https://flagcdn.com/bf.svg" },
    { country: "Burundi", img: "https://flagcdn.com/bi.svg" },
    { country: "Cabo Verde", img: "https://flagcdn.com/cv.svg" },
    { country: "Camboja", img: "https://flagcdn.com/kh.svg" },
    { country: "Camarões", img: "https://flagcdn.com/cm.svg" },
    { country: "Canadá", img: "https://flagcdn.com/ca.svg" },
    { country: "Ilhas Cayman", img: "https://flagcdn.com/ky.svg" },
    { country: "República Centro-Africana", img: "https://flagcdn.com/cf.svg" },
    { country: "Chade", img: "https://flagcdn.com/td.svg" },
    { country: "Chile", img: "https://flagcdn.com/cl.svg" },
    { country: "China", img: "https://flagcdn.com/cn.svg" },
    { country: "Ilha Christmas", img: "https://flagcdn.com/cx.svg" },
    { country: "Ilhas Cocos", img: "https://flagcdn.com/cc.svg" },
    { country: "Colômbia", img: "https://flagcdn.com/co.svg" },
    { country: "Comores", img: "https://flagcdn.com/km.svg" },
    { country: "República Democrática do Congo", img: "https://flagcdn.com/cd.svg" },
    { country: "República do Congo", img: "https://flagcdn.com/cg.svg" },
    { country: "Ilhas Cook", img: "https://flagcdn.com/ck.svg" },
    { country: "Costa Rica", img: "https://flagcdn.com/cr.svg" },
    { country: "Costa do Marfim", img: "https://flagcdn.com/ci.svg" },
    { country: "Croácia", img: "https://flagcdn.com/hr.svg" },
    { country: "Cuba", img: "https://flagcdn.com/cu.svg" },
    { country: "Curaçao", img: "https://flagcdn.com/cw.svg" },
    { country: "Chipre", img: "https://flagcdn.com/cy.svg" },
    { country: "República Tcheca", img: "https://flagcdn.com/cz.svg" },
    { country: "Dinamarca", img: "https://flagcdn.com/dk.svg" },
    { country: "Djibouti", img: "https://flagcdn.com/dj.svg" },
    { country: "Dominica", img: "https://flagcdn.com/dm.svg" },
    { country: "República Dominicana", img: "https://flagcdn.com/do.svg" },
    { country: "Equador", img: "https://flagcdn.com/ec.svg" },
    { country: "Egito", img: "https://flagcdn.com/eg.svg" },
    { country: "El Salvador", img: "https://flagcdn.com/sv.svg" },
    { country: "Guiné Equatorial", img: "https://flagcdn.com/gq.svg" },
    { country: "Eritreia", img: "https://flagcdn.com/er.svg" },
    { country: "Estônia", img: "https://flagcdn.com/ee.svg" },
    { country: "Eswatini", img: "https://flagcdn.com/sz.svg" },
    { country: "Etiópia", img: "https://flagcdn.com/et.svg" },
    { country: "Ilhas Malvinas", img: "https://flagcdn.com/fk.svg" },
    { country: "Ilhas Faroé", img: "https://flagcdn.com/fo.svg" },
    { country: "Fiji", img: "https://flagcdn.com/fj.svg" },
    { country: "Finlândia", img: "https://flagcdn.com/fi.svg" },
    { country: "França", img: "https://flagcdn.com/fr.svg" },
    { country: "Guiana Francesa", img: "https://flagcdn.com/gf.svg" },
    { country: "Polinésia Francesa", img: "https://flagcdn.com/pf.svg" },
    { country: "Territórios Franceses do Sul e Antárticos", img: "https://flagcdn.com/tf.svg" },
    { country: "Gabão", img: "https://flagcdn.com/ga.svg" },
    { country: "Gâmbia", img: "https://flagcdn.com/gm.svg" },
    { country: "Geórgia", img: "https://flagcdn.com/ge.svg" },
    { country: "Alemanha", img: "https://flagcdn.com/de.svg" },
    { country: "Gana", img: "https://flagcdn.com/gh.svg" },
    { country: "Gibraltar", img: "https://flagcdn.com/gi.svg" },
    { country: "Grécia", img: "https://flagcdn.com/gr.svg" },
    { country: "Groenlândia", img: "https://flagcdn.com/gl.svg" },
    { country: "Granada", img: "https://flagcdn.com/gd.svg" },
    { country: "Guadalupe", img: "https://flagcdn.com/gp.svg" },
    { country: "Guam", img: "https://flagcdn.com/gu.svg" },
    { country: "Guatemala", img: "https://flagcdn.com/gt.svg" },
    { country: "Guernsey", img: "https://flagcdn.com/gg.svg" },
    { country: "Guiné", img: "https://flagcdn.com/gn.svg" },
    { country: "Guiné-Bissau", img: "https://flagcdn.com/gw.svg" },
    { country: "Guiana", img: "https://flagcdn.com/gy.svg" },
    { country: "Haiti", img: "https://flagcdn.com/ht.svg" },
    { country: "Ilhas Heard e McDonald", img: "https://flagcdn.com/hm.svg" },
    { country: "Cidade do Vaticano", img: "https://flagcdn.com/va.svg" },
    { country: "Honduras", img: "https://flagcdn.com/hn.svg" },
    { country: "Hong Kong", img: "https://flagcdn.com/hk.svg" },
    { country: "Hungria", img: "https://flagcdn.com/hu.svg" },
    { country: "Islândia", img: "https://flagcdn.com/is.svg" },
    { country: "Índia", img: "https://flagcdn.com/in.svg" },
    { country: "Indonésia", img: "https://flagcdn.com/id.svg" },
    { country: "Irã", img: "https://flagcdn.com/ir.svg" },
    { country: "Iraque", img: "https://flagcdn.com/iq.svg" },
    { country: "Irlanda", img: "https://flagcdn.com/ie.svg" },
    { country: "Ilha de Man", img: "https://flagcdn.com/im.svg" },
    { country: "Israel", img: "https://flagcdn.com/il.svg" },
    { country: "Itália", img: "https://flagcdn.com/it.svg" },
    { country: "Jamaica", img: "https://flagcdn.com/jm.svg" },
    { country: "Japão", img: "https://flagcdn.com/jp.svg" },
    { country: "Jersey", img: "https://flagcdn.com/je.svg" },
    { country: "Jordânia", img: "https://flagcdn.com/jo.svg" },
    { country: "Cazaquistão", img: "https://flagcdn.com/kz.svg" },
    { country: "Quênia", img: "https://flagcdn.com/ke.svg" },
    { country: "Kiribati", img: "https://flagcdn.com/ki.svg" },
    { country: "Coreia do Norte", img: "https://flagcdn.com/kp.svg" },
    { country: "Coreia do Sul", img: "https://flagcdn.com/kr.svg" },
    { country: "Kuwait", img: "https://flagcdn.com/kw.svg" },
    { country: "Quirguistão", img: "https://flagcdn.com/kg.svg" },
    { country: "Laos", img: "https://flagcdn.com/la.svg" },
    { country: "Letônia", img: "https://flagcdn.com/lv.svg" },
    { country: "Líbano", img: "https://flagcdn.com/lb.svg" },
    { country: "Lesoto", img: "https://flagcdn.com/ls.svg" },
    { country: "Libéria", img: "https://flagcdn.com/lr.svg" },
    { country: "Líbia", img: "https://flagcdn.com/ly.svg" },
    { country: "Liechtenstein", img: "https://flagcdn.com/li.svg" },
    { country: "Lituânia", img: "https://flagcdn.com/lt.svg" },
    { country: "Luxemburgo", img: "https://flagcdn.com/lu.svg" },
    { country: "Macau", img: "https://flagcdn.com/mo.svg" },
    { country: "Madagascar", img: "https://flagcdn.com/mg.svg" },
    { country: "Malawi", img: "https://flagcdn.com/mw.svg" },
    { country: "Malásia", img: "https://flagcdn.com/my.svg" },
    { country: "Maldivas", img: "https://flagcdn.com/mv.svg" },
    { country: "Mali", img: "https://flagcdn.com/ml.svg" },
    { country: "Malta", img: "https://flagcdn.com/mt.svg" },
    { country: "Ilhas Marshall", img: "https://flagcdn.com/mh.svg" },
    { country: "Martinica", img: "https://flagcdn.com/mq.svg" },
    { country: "Mauritânia", img: "https://flagcdn.com/mr.svg" },
    { country: "Maurício", img: "https://flagcdn.com/mu.svg" },
    { country: "Mayotte", img: "https://flagcdn.com/yt.svg" },
    { country: "México", img: "https://flagcdn.com/mx.svg" },
    { country: "Micronésia", img: "https://flagcdn.com/fm.svg" },
    { country: "Moldávia", img: "https://flagcdn.com/md.svg" },
    { country: "Mônaco", img: "https://flagcdn.com/mc.svg" },
    { country: "Mongólia", img: "https://flagcdn.com/mn.svg" },
    { country: "Montenegro", img: "https://flagcdn.com/me.svg" },
    { country: "Montserrat", img: "https://flagcdn.com/ms.svg" },
    { country: "Marrocos", img: "https://flagcdn.com/ma.svg" },
    { country: "Moçambique", img: "https://flagcdn.com/mz.svg" },
    { country: "Myanmar", img: "https://flagcdn.com/mm.svg" },
    { country: "Namíbia", img: "https://flagcdn.com/na.svg" },
    { country: "Nauru", img: "https://flagcdn.com/nr.svg" },
    { country: "Nepal", img: "https://flagcdn.com/np.svg" },
    { country: "Países Baixos", img: "https://flagcdn.com/nl.svg" },
    { country: "Nova Caledônia", img: "https://flagcdn.com/nc.svg" },
    { country: "Nova Zelândia", img: "https://flagcdn.com/nz.svg" },
    { country: "Nicarágua", img: "https://flagcdn.com/ni.svg" },
    { country: "Níger", img: "https://flagcdn.com/ne.svg" },
    { country: "Nigéria", img: "https://flagcdn.com/ng.svg" },
    { country: "Niue", img: "https://flagcdn.com/nu.svg" },
    { country: "Ilha Norfolk", img: "https://flagcdn.com/nf.svg" },
    { country: "Ilhas Marianas do Norte", img: "https://flagcdn.com/mp.svg" },
    { country: "Noruega", img: "https://flagcdn.com/no.svg" },
    { country: "Omã", img: "https://flagcdn.com/om.svg" },
    { country: "Paquistão", img: "https://flagcdn.com/pk.svg" },
    { country: "Palau", img: "https://flagcdn.com/pw.svg" },
    { country: "Palestina", img: "https://flagcdn.com/ps.svg" },
    { country: "Panamá", img: "https://flagcdn.com/pa.svg" },
    { country: "Papua-Nova Guiné", img: "https://flagcdn.com/pg.svg" },
    { country: "Paraguai", img: "https://flagcdn.com/py.svg" },
    { country: "Peru", img: "https://flagcdn.com/pe.svg" },
    { country: "Filipinas", img: "https://flagcdn.com/ph.svg" },
    { country: "Pitcairn", img: "https://flagcdn.com/pn.svg" },
    { country: "Polônia", img: "https://flagcdn.com/pl.svg" },
    { country: "Portugal", img: "https://flagcdn.com/pt.svg" },
    { country: "Porto Rico", img: "https://flagcdn.com/pr.svg" },
    { country: "Catar", img: "https://flagcdn.com/qa.svg" },
    { country: "Reunião", img: "https://flagcdn.com/re.svg" },
    { country: "Romênia", img: "https://flagcdn.com/ro.svg" },
    { country: "Rússia", img: "https://flagcdn.com/ru.svg" },
    { country: "Ruanda", img: "https://flagcdn.com/rw.svg" },
    { country: "São Bartolomeu", img: "https://flagcdn.com/bl.svg" },
    { country: "Santa Helena", img: "https://flagcdn.com/sh.svg" },
    { country: "São Cristóvão e Nevis", img: "https://flagcdn.com/kn.svg" },
    { country: "Santa Lúcia", img: "https://flagcdn.com/lc.svg" },
    { country: "São Martinho", img: "https://flagcdn.com/mf.svg" },
    { country: "São Pedro e Miquelon", img: "https://flagcdn.com/pm.svg" },
    { country: "São Vicente e Granadinas", img: "https://flagcdn.com/vc.svg" },
    { country: "Samoa", img: "https://flagcdn.com/ws.svg" },
    { country: "San Marino", img: "https://flagcdn.com/sm.svg" },
    { country: "São Tomé e Príncipe", img: "https://flagcdn.com/st.svg" },
    { country: "Arábia Saudita", img: "https://flagcdn.com/sa.svg" },
    { country: "Senegal", img: "https://flagcdn.com/sn.svg" },
    { country: "Sérvia", img: "https://flagcdn.com/rs.svg" },
    { country: "Seychelles", img: "https://flagcdn.com/sc.svg" },
    { country: "Serra Leoa", img: "https://flagcdn.com/sl.svg" },
    { country: "Singapura", img: "https://flagcdn.com/sg.svg" },
    { country: "Sint Maarten", img: "https://flagcdn.com/sx.svg" },
    { country: "Eslováquia", img: "https://flagcdn.com/sk.svg" },
    { country: "Eslovênia", img: "https://flagcdn.com/si.svg" },
    { country: "Ilhas Salomão", img: "https://flagcdn.com/sb.svg" },
    { country: "Somália", img: "https://flagcdn.com/so.svg" },
    { country: "África do Sul", img: "https://flagcdn.com/za.svg" },
    { country: "Ilhas Geórgia do Sul e Sandwich do Sul", img: "https://flagcdn.com/gs.svg" },
    { country: "Sudão do Sul", img: "https://flagcdn.com/ss.svg" },
    { country: "Espanha", img: "https://flagcdn.com/es.svg" },
    { country: "Sri Lanka", img: "https://flagcdn.com/lk.svg" },
    { country: "Sudão", img: "https://flagcdn.com/sd.svg" },
    { country: "Suriname", img: "https://flagcdn.com/sr.svg" },
    { country: "Svalbard e Jan Mayen", img: "https://flagcdn.com/sj.svg" },
    { country: "Suécia", img: "https://flagcdn.com/se.svg" },
    { country: "Suíça", img: "https://flagcdn.com/ch.svg" },
    { country: "Síria", img: "https://flagcdn.com/sy.svg" },
    { country: "Taiwan", img: "https://flagcdn.com/tw.svg" },
    { country: "Tajiquistão", img: "https://flagcdn.com/tj.svg" },
    { country: "Tanzânia", img: "https://flagcdn.com/tz.svg" },
    { country: "Tailândia", img: "https://flagcdn.com/th.svg" },
    { country: "Timor-Leste", img: "https://flagcdn.com/tl.svg" },
    { country: "Togo", img: "https://flagcdn.com/tg.svg" },
    { country: "Tokelau", img: "https://flagcdn.com/tk.svg" },
    { country: "Tonga", img: "https://flagcdn.com/to.svg" },
    { country: "Trinidad e Tobago", img: "https://flagcdn.com/tt.svg" },
    { country: "Tunísia", img: "https://flagcdn.com/tn.svg" },
    { country: "Turquia", img: "https://flagcdn.com/tr.svg" },
    { country: "Turcomenistão", img: "https://flagcdn.com/tm.svg" },
    { country: "Ilhas Turcas e Caicos", img: "https://flagcdn.com/tc.svg" },
    { country: "Tuvalu", img: "https://flagcdn.com/tv.svg" },
    { country: "Uganda", img: "https://flagcdn.com/ug.svg" },
    { country: "Ucrânia", img: "https://flagcdn.com/ua.svg" },
    { country: "Emirados Árabes Unidos", img: "https://flagcdn.com/ae.svg" },
    { country: "Reino Unido", img: "https://flagcdn.com/gb.svg" },
    { country: "Estados Unidos", img: "https://flagcdn.com/us.svg" },
    { country: "Ilhas Menores Distantes dos Estados Unidos", img: "https://flagcdn.com/um.svg" },
    { country: "Uruguai", img: "https://flagcdn.com/uy.svg" },
    { country: "Uzbequistão", img: "https://flagcdn.com/uz.svg" },
    { country: "Vanuatu", img: "https://flagcdn.com/vu.svg" },
    { country: "Venezuela", img: "https://flagcdn.com/ve.svg" },
    { country: "Vietnã", img: "https://flagcdn.com/vn.svg" },
    { country: "Wallis e Futuna", img: "https://flagcdn.com/wf.svg" },
    { country: "Saara Ocidental", img: "https://flagcdn.com/eh.svg" },
    { country: "Iêmen", img: "https://flagcdn.com/ye.svg" },
    { country: "Zâmbia", img: "https://flagcdn.com/zm.svg" },
    { country: "Zimbábue", img: "https://flagcdn.com/zw.svg" },
    { country: "Kosovo", img: "https://flagcdn.com/xk.svg" }
];
