const flags = [
    { country: "Afganistán", img: "https://flagcdn.com/af.svg" },
    { country: "Islas Åland", img: "https://flagcdn.com/ax.svg" },
    { country: "Albania", img: "https://flagcdn.com/al.svg" },
    { country: "Argelia", img: "https://flagcdn.com/dz.svg" },
    { country: "Samoa Americana", img: "https://flagcdn.com/as.svg" },
    { country: "Andorra", img: "https://flagcdn.com/ad.svg" },
    { country: "Angola", img: "https://flagcdn.com/ao.svg" },
    { country: "Anguila", img: "https://flagcdn.com/ai.svg" },
    { country: "Antártida", img: "https://flagcdn.com/aq.svg" },
    { country: "Antigua y Barbuda", img: "https://flagcdn.com/ag.svg" },
    { country: "Argentina", img: "https://flagcdn.com/ar.svg" },
    { country: "Armenia", img: "https://flagcdn.com/am.svg" },
    { country: "Aruba", img: "https://flagcdn.com/aw.svg" },
    { country: "Australia", img: "https://flagcdn.com/au.svg" },
    { country: "Austria", img: "https://flagcdn.com/at.svg" },
    { country: "Azerbaiyán", img: "https://flagcdn.com/az.svg" },
    { country: "Bahamas", img: "https://flagcdn.com/bs.svg" },
    { country: "Baréin", img: "https://flagcdn.com/bh.svg" },
    { country: "Bangladés", img: "https://flagcdn.com/bd.svg" },
    { country: "Barbados", img: "https://flagcdn.com/bb.svg" },
    { country: "Bielorrusia", img: "https://flagcdn.com/by.svg" },
    { country: "Bélgica", img: "https://flagcdn.com/be.svg" },
    { country: "Belice", img: "https://flagcdn.com/bz.svg" },
    { country: "Benín", img: "https://flagcdn.com/bj.svg" },
    { country: "Bermudas", img: "https://flagcdn.com/bm.svg" },
    { country: "Bután", img: "https://flagcdn.com/bt.svg" },
    { country: "Bolivia", img: "https://flagcdn.com/bo.svg" },
    { country: "Caribe Neerlandés", img: "https://flagcdn.com/bq.svg" },
    { country: "Bosnia y Herzegovina", img: "https://flagcdn.com/ba.svg" },
    { country: "Botsuana", img: "https://flagcdn.com/bw.svg" },
    { country: "Isla Bouvet", img: "https://flagcdn.com/bv.svg" },
    { country: "Brasil", img: "https://flagcdn.com/br.svg" },
    { country: "Territorio Británico del Océano Índico", img: "https://flagcdn.com/io.svg" },
    { country: "Islas Vírgenes Británicas", img: "https://flagcdn.com/vg.svg" },
    { country: "Brunéi", img: "https://flagcdn.com/bn.svg" },
    { country: "Bulgaria", img: "https://flagcdn.com/bg.svg" },
    { country: "Burkina Faso", img: "https://flagcdn.com/bf.svg" },
    { country: "Burundi", img: "https://flagcdn.com/bi.svg" },
    { country: "Cabo Verde", img: "https://flagcdn.com/cv.svg" },
    { country: "Camboya", img: "https://flagcdn.com/kh.svg" },
    { country: "Camerún", img: "https://flagcdn.com/cm.svg" },
    { country: "Canadá", img: "https://flagcdn.com/ca.svg" },
    { country: "Islas Caimán", img: "https://flagcdn.com/ky.svg" },
    { country: "República Centroafricana", img: "https://flagcdn.com/cf.svg" },
    { country: "Chad", img: "https://flagcdn.com/td.svg" },
    { country: "Chile", img: "https://flagcdn.com/cl.svg" },
    { country: "China", img: "https://flagcdn.com/cn.svg" },
    { country: "Isla de Navidad", img: "https://flagcdn.com/cx.svg" },
    { country: "Islas Cocos", img: "https://flagcdn.com/cc.svg" },
    { country: "Colombia", img: "https://flagcdn.com/co.svg" },
    { country: "Comoras", img: "https://flagcdn.com/km.svg" },
    { country: "República Democrática del Congo", img: "https://flagcdn.com/cd.svg" },
    { country: "República del Congo", img: "https://flagcdn.com/cg.svg" },
    { country: "Islas Cook", img: "https://flagcdn.com/ck.svg" },
    { country: "Costa Rica", img: "https://flagcdn.com/cr.svg" },
    { country: "Costa de Marfil", img: "https://flagcdn.com/ci.svg" },
    { country: "Croacia", img: "https://flagcdn.com/hr.svg" },
    { country: "Cuba", img: "https://flagcdn.com/cu.svg" },
    { country: "Curazao", img: "https://flagcdn.com/cw.svg" },
    { country: "Chipre", img: "https://flagcdn.com/cy.svg" },
    { country: "República Checa", img: "https://flagcdn.com/cz.svg" },
    { country: "Dinamarca", img: "https://flagcdn.com/dk.svg" },
    { country: "Yibuti", img: "https://flagcdn.com/dj.svg" },
    { country: "Dominica", img: "https://flagcdn.com/dm.svg" },
    { country: "República Dominicana", img: "https://flagcdn.com/do.svg" },
    { country: "Ecuador", img: "https://flagcdn.com/ec.svg" },
    { country: "Egipto", img: "https://flagcdn.com/eg.svg" },
    { country: "El Salvador", img: "https://flagcdn.com/sv.svg" },
    { country: "Guinea Ecuatorial", img: "https://flagcdn.com/gq.svg" },
    { country: "Eritrea", img: "https://flagcdn.com/er.svg" },
    { country: "Estonia", img: "https://flagcdn.com/ee.svg" },
    { country: "Esuatini", img: "https://flagcdn.com/sz.svg" },
    { country: "Etiopía", img: "https://flagcdn.com/et.svg" },
    { country: "Islas Malvinas", img: "https://flagcdn.com/fk.svg" },
    { country: "Islas Feroe", img: "https://flagcdn.com/fo.svg" },
    { country: "Fiyi", img: "https://flagcdn.com/fj.svg" },
    { country: "Finlandia", img: "https://flagcdn.com/fi.svg" },
    { country: "Francia", img: "https://flagcdn.com/fr.svg" },
    { country: "Guayana Francesa", img: "https://flagcdn.com/gf.svg" },
    { country: "Polinesia Francesa", img: "https://flagcdn.com/pf.svg" },
    { country: "Territorios Australes y Antárticos Franceses", img: "https://flagcdn.com/tf.svg" },
    { country: "Gabón", img: "https://flagcdn.com/ga.svg" },
    { country: "Gambia", img: "https://flagcdn.com/gm.svg" },
    { country: "Georgia", img: "https://flagcdn.com/ge.svg" },
    { country: "Alemania", img: "https://flagcdn.com/de.svg" },
    { country: "Ghana", img: "https://flagcdn.com/gh.svg" },
    { country: "Gibraltar", img: "https://flagcdn.com/gi.svg" },
    { country: "Grecia", img: "https://flagcdn.com/gr.svg" },
    { country: "Groenlandia", img: "https://flagcdn.com/gl.svg" },
    { country: "Granada", img: "https://flagcdn.com/gd.svg" },
    { country: "Guadalupe", img: "https://flagcdn.com/gp.svg" },
    { country: "Guam", img: "https://flagcdn.com/gu.svg" },
    { country: "Guatemala", img: "https://flagcdn.com/gt.svg" },
    { country: "Guernesey", img: "https://flagcdn.com/gg.svg" },
    { country: "Guinea", img: "https://flagcdn.com/gn.svg" },
    { country: "Guinea-Bisáu", img: "https://flagcdn.com/gw.svg" },
    { country: "Guyana", img: "https://flagcdn.com/gy.svg" },
    { country: "Haití", img: "https://flagcdn.com/ht.svg" },
    { country: "Islas Heard y McDonald", img: "https://flagcdn.com/hm.svg" },
    { country: "Ciudad del Vaticano", img: "https://flagcdn.com/va.svg" },
    { country: "Honduras", img: "https://flagcdn.com/hn.svg" },
    { country: "Hong Kong", img: "https://flagcdn.com/hk.svg" },
    { country: "Hungría", img: "https://flagcdn.com/hu.svg" },
    { country: "Islandia", img: "https://flagcdn.com/is.svg" },
    { country: "India", img: "https://flagcdn.com/in.svg" },
    { country: "Indonesia", img: "https://flagcdn.com/id.svg" },
    { country: "Irán", img: "https://flagcdn.com/ir.svg" },
    { country: "Iraq", img: "https://flagcdn.com/iq.svg" },
    { country: "Irlanda", img: "https://flagcdn.com/ie.svg" },
    { country: "Isla de Man", img: "https://flagcdn.com/im.svg" },
    { country: "Israel", img: "https://flagcdn.com/il.svg" },
    { country: "Italia", img: "https://flagcdn.com/it.svg" },
    { country: "Jamaica", img: "https://flagcdn.com/jm.svg" },
    { country: "Japón", img: "https://flagcdn.com/jp.svg" },
    { country: "Jersey", img: "https://flagcdn.com/je.svg" },
    { country: "Jordania", img: "https://flagcdn.com/jo.svg" },
    { country: "Kazajistán", img: "https://flagcdn.com/kz.svg" },
    { country: "Kenia", img: "https://flagcdn.com/ke.svg" },
    { country: "Kiribati", img: "https://flagcdn.com/ki.svg" },
    { country: "Corea del Norte", img: "https://flagcdn.com/kp.svg" },
    { country: "Corea del Sur", img: "https://flagcdn.com/kr.svg" },
    { country: "Kuwait", img: "https://flagcdn.com/kw.svg" },
    { country: "Kirguistán", img: "https://flagcdn.com/kg.svg" },
    { country: "Laos", img: "https://flagcdn.com/la.svg" },
    { country: "Letonia", img: "https://flagcdn.com/lv.svg" },
    { country: "Líbano", img: "https://flagcdn.com/lb.svg" },
    { country: "Lesoto", img: "https://flagcdn.com/ls.svg" },
    { country: "Liberia", img: "https://flagcdn.com/lr.svg" },
    { country: "Libia", img: "https://flagcdn.com/ly.svg" },
    { country: "Liechtenstein", img: "https://flagcdn.com/li.svg" },
    { country: "Lituania", img: "https://flagcdn.com/lt.svg" },
    { country: "Luxemburgo", img: "https://flagcdn.com/lu.svg" },
    { country: "Macao", img: "https://flagcdn.com/mo.svg" },
    { country: "Madagascar", img: "https://flagcdn.com/mg.svg" },
    { country: "Malaui", img: "https://flagcdn.com/mw.svg" },
    { country: "Malasia", img: "https://flagcdn.com/my.svg" },
    { country: "Maldivas", img: "https://flagcdn.com/mv.svg" },
    { country: "Malí", img: "https://flagcdn.com/ml.svg" },
    { country: "Malta", img: "https://flagcdn.com/mt.svg" },
    { country: "Islas Marshall", img: "https://flagcdn.com/mh.svg" },
    { country: "Martinica", img: "https://flagcdn.com/mq.svg" },
    { country: "Mauritania", img: "https://flagcdn.com/mr.svg" },
    { country: "Mauricio", img: "https://flagcdn.com/mu.svg" },
    { country: "Mayotte", img: "https://flagcdn.com/yt.svg" },
    { country: "México", img: "https://flagcdn.com/mx.svg" },
    { country: "Micronesia", img: "https://flagcdn.com/fm.svg" },
    { country: "Moldavia", img: "https://flagcdn.com/md.svg" },
    { country: "Mónaco", img: "https://flagcdn.com/mc.svg" },
    { country: "Mongolia", img: "https://flagcdn.com/mn.svg" },
    { country: "Montenegro", img: "https://flagcdn.com/me.svg" },
    { country: "Montserrat", img: "https://flagcdn.com/ms.svg" },
    { country: "Marruecos", img: "https://flagcdn.com/ma.svg" },
    { country: "Mozambique", img: "https://flagcdn.com/mz.svg" },
    { country: "Myanmar", img: "https://flagcdn.com/mm.svg" },
    { country: "Namibia", img: "https://flagcdn.com/na.svg" },
    { country: "Nauru", img: "https://flagcdn.com/nr.svg" },
    { country: "Nepal", img: "https://flagcdn.com/np.svg" },
    { country: "Países Bajos", img: "https://flagcdn.com/nl.svg" },
    { country: "Nueva Caledonia", img: "https://flagcdn.com/nc.svg" },
    { country: "Nueva Zelanda", img: "https://flagcdn.com/nz.svg" },
    { country: "Nicaragua", img: "https://flagcdn.com/ni.svg" },
    { country: "Níger", img: "https://flagcdn.com/ne.svg" },
    { country: "Nigeria", img: "https://flagcdn.com/ng.svg" },
    { country: "Niue", img: "https://flagcdn.com/nu.svg" },
    { country: "Isla Norfolk", img: "https://flagcdn.com/nf.svg" },
    { country: "Islas Marianas del Norte", img: "https://flagcdn.com/mp.svg" },
    { country: "Noruega", img: "https://flagcdn.com/no.svg" },
    { country: "Omán", img: "https://flagcdn.com/om.svg" },
    { country: "Pakistán", img: "https://flagcdn.com/pk.svg" },
    { country: "Palaos", img: "https://flagcdn.com/pw.svg" },
    { country: "Palestina", img: "https://flagcdn.com/ps.svg" },
    { country: "Panamá", img: "https://flagcdn.com/pa.svg" },
    { country: "Papúa Nueva Guinea", img: "https://flagcdn.com/pg.svg" },
    { country: "Paraguay", img: "https://flagcdn.com/py.svg" },
    { country: "Perú", img: "https://flagcdn.com/pe.svg" },
    { country: "Filipinas", img: "https://flagcdn.com/ph.svg" },
    { country: "Pitcairn", img: "https://flagcdn.com/pn.svg" },
    { country: "Polonia", img: "https://flagcdn.com/pl.svg" },
    { country: "Portugal", img: "https://flagcdn.com/pt.svg" },
    { country: "Puerto Rico", img: "https://flagcdn.com/pr.svg" },
    { country: "Catar", img: "https://flagcdn.com/qa.svg" },
    { country: "Reunión", img: "https://flagcdn.com/re.svg" },
    { country: "Rumanía", img: "https://flagcdn.com/ro.svg" },
    { country: "Rusia", img: "https://flagcdn.com/ru.svg" },
    { country: "Ruanda", img: "https://flagcdn.com/rw.svg" },
    { country: "San Bartolomé", img: "https://flagcdn.com/bl.svg" },
    { country: "Santa Elena", img: "https://flagcdn.com/sh.svg" },
    { country: "San Cristóbal y Nieves", img: "https://flagcdn.com/kn.svg" },
    { country: "Santa Lucía", img: "https://flagcdn.com/lc.svg" },
    { country: "San Martín", img: "https://flagcdn.com/mf.svg" },
    { country: "San Pedro y Miquelón", img: "https://flagcdn.com/pm.svg" },
    { country: "San Vicente y las Granadinas", img: "https://flagcdn.com/vc.svg" },
    { country: "Samoa", img: "https://flagcdn.com/ws.svg" },
    { country: "San Marino", img: "https://flagcdn.com/sm.svg" },
    { country: "Santo Tomé y Príncipe", img: "https://flagcdn.com/st.svg" },
    { country: "Arabia Saudita", img: "https://flagcdn.com/sa.svg" },
    { country: "Senegal", img: "https://flagcdn.com/sn.svg" },
    { country: "Serbia", img: "https://flagcdn.com/rs.svg" },
    { country: "Seychelles", img: "https://flagcdn.com/sc.svg" },
    { country: "Sierra Leona", img: "https://flagcdn.com/sl.svg" },
    { country: "Singapur", img: "https://flagcdn.com/sg.svg" },
    { country: "Sint Maarten", img: "https://flagcdn.com/sx.svg" },
    { country: "Eslovaquia", img: "https://flagcdn.com/sk.svg" },
    { country: "Eslovenia", img: "https://flagcdn.com/si.svg" },
    { country: "Islas Salomón", img: "https://flagcdn.com/sb.svg" },
    { country: "Somalia", img: "https://flagcdn.com/so.svg" },
    { country: "Sudáfrica", img: "https://flagcdn.com/za.svg" },
    { country: "Islas Georgia del Sur y Sandwich del Sur", img: "https://flagcdn.com/gs.svg" },
    { country: "Sudán del Sur", img: "https://flagcdn.com/ss.svg" },
    { country: "España", img: "https://flagcdn.com/es.svg" },
    { country: "Sri Lanka", img: "https://flagcdn.com/lk.svg" },
    { country: "Sudán", img: "https://flagcdn.com/sd.svg" },
    { country: "Surinam", img: "https://flagcdn.com/sr.svg" },
    { country: "Svalbard y Jan Mayen", img: "https://flagcdn.com/sj.svg" },
    { country: "Suecia", img: "https://flagcdn.com/se.svg" },
    { country: "Suiza", img: "https://flagcdn.com/ch.svg" },
    { country: "Siria", img: "https://flagcdn.com/sy.svg" },
    { country: "Taiwán", img: "https://flagcdn.com/tw.svg" },
    { country: "Tayikistán", img: "https://flagcdn.com/tj.svg" },
    { country: "Tanzania", img: "https://flagcdn.com/tz.svg" },
    { country: "Tailandia", img: "https://flagcdn.com/th.svg" },
    { country: "Timor Oriental", img: "https://flagcdn.com/tl.svg" },
    { country: "Togo", img: "https://flagcdn.com/tg.svg" },
    { country: "Tokelau", img: "https://flagcdn.com/tk.svg" },
    { country: "Tonga", img: "https://flagcdn.com/to.svg" },
    { country: "Trinidad y Tobago", img: "https://flagcdn.com/tt.svg" },
    { country: "Túnez", img: "https://flagcdn.com/tn.svg" },
    { country: "Turquía", img: "https://flagcdn.com/tr.svg" },
    { country: "Turkmenistán", img: "https://flagcdn.com/tm.svg" },
    { country: "Islas Turcas y Caicos", img: "https://flagcdn.com/tc.svg" },
    { country: "Tuvalu", img: "https://flagcdn.com/tv.svg" },
    { country: "Uganda", img: "https://flagcdn.com/ug.svg" },
    { country: "Ucrania", img: "https://flagcdn.com/ua.svg" },
    { country: "Emiratos Árabes Unidos", img: "https://flagcdn.com/ae.svg" },
    { country: "Reino Unido", img: "https://flagcdn.com/gb.svg" },
    { country: "Estados Unidos", img: "https://flagcdn.com/us.svg" },
    { country: "Islas Ultramarinas Menores de los Estados Unidos", img: "https://flagcdn.com/um.svg" },
    { country: "Uruguay", img: "https://flagcdn.com/uy.svg" },
    { country: "Uzbekistán", img: "https://flagcdn.com/uz.svg" },
    { country: "Vanuatu", img: "https://flagcdn.com/vu.svg" },
    { country: "Venezuela", img: "https://flagcdn.com/ve.svg" },
    { country: "Vietnam", img: "https://flagcdn.com/vn.svg" },
    { country: "Wallis y Futuna", img: "https://flagcdn.com/wf.svg" },
    { country: "Sahara Occidental", img: "https://flagcdn.com/eh.svg" },
    { country: "Yemen", img: "https://flagcdn.com/ye.svg" },
    { country: "Zambia", img: "https://flagcdn.com/zm.svg" },
    { country: "Zimbabue", img: "https://flagcdn.com/zw.svg" },
    { country: "Kosovo", img: "https://flagcdn.com/xk.svg" }
];
