window.RECIPES_DB = [
	{ name: "Canh Kimchi", ingredients: ["Kimchi", "Thịt heo", "Đậu phụ", "Hành tây", "Hành lá", "Tỏi", "Bột ớt", "Tương ớt Gochujang", "Nước tương"] },
	{ name: "Cơm trộn Bibimbap", ingredients: ["Cơm", "Thịt bò", "Rau chân vịt", "Giá đỗ", "Cà rốt", "Bí ngòi Hàn Quốc", "Trứng", "Tương ớt Gochujang", "Rong biển"] },
	{ name: "Bulgogi (Thịt bò nướng)", ingredients: ["Thịt bò", "Nước tương", "Hành tây", "Lê", "Đường", "Dầu mè", "Tỏi", "Hành lá", "Tiêu"] },
	{ name: "Japchae (Miến trộn)", ingredients: ["Miến", "Thịt bò", "Rau chân vịt", "Cà rốt", "Hành tây", "Nấm", "Trứng", "Nước tương", "Dầu mè"] },
	{ name: "Tteokbokki (Bánh gạo cay)", ingredients: ["Bánh gạo (Tteok)", "Chả cá", "Hành tây", "Hành lá", "Tương ớt Gochujang", "Đường", "Nước tương", "Tỏi", "Trứng luộc"] },
	{ name: "Sundubu Jjigae (Canh đậu phụ non)", ingredients: ["Đậu phụ non", "Thịt heo", "Trứng", "Bí ngòi Hàn Quốc", "Hành tây", "Hành lá", "Tỏi", "Bột ớt", "Nước tương"] },
	{ name: "Samgyeopsal (Thịt ba chỉ nướng)", ingredients: ["Thịt ba chỉ", "Xà lách", "Tỏi", "Tương chấm Ssamjang", "Hành lá", "Muối", "Tiêu"] },
	{ name: "Cơm chiên Kimchi", ingredients: ["Kimchi", "Cơm", "Trứng", "Thịt heo", "Hành lá", "Nước tương", "Dầu mè"] },
	{ name: "Galbijjim (Sườn hầm)", ingredients: ["Sườn bò", "Hành tây", "Cà rốt", "Khoai tây", "Nước tương", "Đường", "Lê", "Tỏi", "Dầu mè"] },
	{ name: "Jajangmyeon (Mì tương đen)", ingredients: ["Mì", "Thịt heo", "Hành tây", "Bí ngòi Hàn Quốc", "Khoai tây", "Tương đen (Chunjang)", "Dưa chuột", "Trứng"] },
	{ name: "Sushi", ingredients: ["Cơm", "Giấm", "Đường", "Muối", "Rong biển", "Cá hồi", "Cá ngừ", "Tôm", "Quả bơ", "Dưa chuột"] },
	{ name: "Ramyeon (Mì gói)", ingredients: ["Mì", "Thịt heo", "Trứng", "Hành lá", "Măng tre", "Rong biển", "Nước tương", "Tương đậu (Doenjang)", "Tỏi"] },
	{ name: "Katsudon (Cơm thịt heo chiên xù)", ingredients: ["Cơm", "Thịt heo chiên xù (Tonkatsu)", "Trứng", "Hành tây", "Nước tương", "Đường", "Rượu Mirin"] },
	{ name: "Okonomiyaki (Bánh xèo Nhật)", ingredients: ["Bột mì", "Trứng", "Bắp cải", "Thịt heo", "Tôm", "Hành lá", "Sốt mayonnaise", "Sốt Okonomiyaki"] },
	{ name: "Đậu phụ Mapo", ingredients: ["Đậu phụ", "Thịt heo băm", "Hành lá", "Tỏi", "Gừng", "Nước tương", "Tương đậu cay (Doubanjiang)", "Tiêu Tứ Xuyên"] },
	{ name: "Vịt quay Bắc Kinh", ingredients: ["Vịt", "Dưa chuột", "Hành lá", "Tương đen (Hoisin sauce)", "Bánh tráng"] },
	{ name: "Tangsuyuk (Thịt chiên chua ngọt)", ingredients: ["Thịt heo", "Dứa", "Ớt chuông", "Hành tây", "Giấm", "Đường", "Tương cà (Ketchup)", "Nước tương"] },
	{ name: "Pad Thai", ingredients: ["Bún Pad Thai", "Tôm", "Trứng", "Đậu phụ", "Giá đỗ", "Đậu phộng", "Me", "Nước mắm", "Chanh xanh"] },
	{ name: "Tom Yum Goong", ingredients: ["Tôm", "Sả", "Chanh xanh", "Riềng", "Nấm", "Ớt", "Nước mắm", "Ngò rí"] },
	{ name: "Phở", ingredients: ["Phở (Bún phở)", "Thịt bò", "Hành tây", "Gừng", "Quế", "Đinh hương", "Nước mắm", "Giá đỗ", "Chanh xanh", "Húng quế"] },
	{ name: "Cơm gà Hải Nam", ingredients: ["Thịt gà", "Cơm", "Gừng", "Tỏi", "Dưa chuột", "Nước tương", "Sốt ớt"] },
	{ name: "Gỏi cuốn (Chả giò tươi)", ingredients: ["Bánh tráng", "Tôm", "Thịt heo", "Xà lách", "Bún (Bún tươi)", "Bạc hà", "Ngò rí"] },
	{ name: "Cà ri xanh", ingredients: ["Thịt gà", "Bột cà ri xanh", "Nước cốt dừa", "Cà tím", "Húng quế", "Nước mắm", "Đường"] },
	{ name: "Nasi Goreng (Cơm chiên Indonesia)", ingredients: ["Cơm", "Thịt gà", "Trứng", "Nước tương", "Tôm", "Hành lá", "Ớt"] },
	{ name: "Satay", ingredients: ["Thịt gà", "Đậu phộng", "Nước tương", "Sả", "Tỏi", "Nghệ"] },
	{ name: "Laksa", ingredients: ["Bún (Bún laksa)", "Tôm", "Nước cốt dừa", "Đậu phụ", "Giá đỗ", "Trứng", "Ớt", "Ngò rí"] },
	{ name: "Chow Mein", ingredients: ["Mì", "Thịt gà", "Giá đỗ", "Bắp cải", "Cà rốt", "Nước tương", "Hành lá"] },
	{ name: "Cơm chiên", ingredients: ["Cơm", "Trứng", "Cà rốt", "Đậu Hà Lan", "Hành lá", "Tôm", "Nước tương"] },
	{ name: "Gyoza (Bánh xếp Nhật)", ingredients: ["Bột mì", "Bắp cải", "Thịt heo", "Tỏi", "Gừng", "Hành lá", "Nước tương"] },
	{ name: "Cơm lươn nướng", ingredients: ["Cơm", "Lươn", "Nước tương", "Rượu Mirin", "Đường", "Trứng"] },
	{ name: "Hamburger", ingredients: ["Thịt bò", "Bánh mì", "Xà lách", "Cà chua", "Hành tây", "Phô mai", "Dưa chuột muối"] },
	{ name: "Cheeseburger", ingredients: ["Thịt bò", "Bánh mì", "Phô mai", "Xà lách", "Cà chua", "Hành tây", "Dưa chuột muối"] },
	{ name: "Gà rán", ingredients: ["Thịt gà", "Bột mì", "Trứng", "Dầu ăn", "Muối", "Tiêu"] },
	{ name: "Sườn heo nướng BBQ", ingredients: ["Sườn heo", "Sốt BBQ", "Đường nâu", "Muối", "Tiêu", "Bột tỏi"] },
	{ name: "Salad Caesar", ingredients: ["Xà lách", "Phô mai Parmesan", "Bánh mì nướng giòn (Crouton)", "Cá cơm", "Trứng", "Sốt Caesar"] },
	{ name: "Bánh mì BLT", ingredients: ["Bánh mì", "Thịt xông khói (Bacon)", "Xà lách", "Cà chua", "Sốt mayonnaise"] },
	{ name: "Spaghetti Carbonara", ingredients: ["Spaghetti", "Trứng", "Phô mai Parmesan", "Pancetta", "Tiêu"] },
	{ name: "Lasagna", ingredients: ["Lá Lasagna", "Thịt bò băm", "Sốt cà chua", "Phô mai Ricotta", "Phô mai Mozzarella", "Phô mai Parmesan", "Trứng"] },
	{ name: "Pizza Margherita", ingredients: ["Đế bánh pizza", "Sốt cà chua", "Phô mai Mozzarella", "Húng quế", "Dầu ô liu"] },
	{ name: "Paella", ingredients: ["Cơm", "Tôm", "Vẹm", "Thịt gà", "Xúc xích Chorizo", "Đậu Hà Lan", "Nghệ tây", "Ớt bột (Paprika)", "Ớt chuông"] },
	{ name: "Croque Monsieur", ingredients: ["Bánh mì", "Thịt nguội (Ham)", "Phô mai", "Bơ", "Sữa", "Bột mì", "Mù tạt"] },
	{ name: "Quiche Lorraine", ingredients: ["Vỏ bánh tart", "Trứng", "Thịt xông khói (Bacon)", "Phô mai", "Kem", "Hành tây"] },
	{ name: "Ratatouille", ingredients: ["Cà tím", "Bí ngòi Hàn Quốc", "Ớt chuông", "Cà chua", "Hành tây", "Tỏi"] },
	{ name: "Bouillabaisse (Súp cá kiểu Pháp)", ingredients: ["Cá", "Vẹm", "Tôm", "Cà chua", "Tỏi", "Hành tây", "Thì là tây (Fennel)", "Nghệ tây"] },
	{ name: "Crepe", ingredients: ["Bột mì", "Trứng", "Sữa", "Bơ", "Đường", "Muối"] },
	{ name: "Trứng tráng kiểu Tây Ban Nha", ingredients: ["Trứng", "Khoai tây", "Hành tây", "Dầu ô liu", "Muối"] },
	{ name: "Gazpacho", ingredients: ["Cà chua", "Dưa chuột", "Ớt chuông", "Hành tây", "Tỏi", "Dầu ô liu", "Giấm"] },
	{ name: "Patatas Bravas", ingredients: ["Khoai tây", "Dầu ô liu", "Ớt bột (Paprika)", "Cà chua", "Sốt Aioli"] },
	{ name: "Churros", ingredients: ["Bột mì", "Trứng", "Bơ", "Đường", "Muối", "Dầu ăn", "Quế"] },
	{ name: "Salad Niçoise cá ngừ", ingredients: ["Xà lách", "Cá ngừ", "Trứng", "Khoai tây", "Đậu que", "Ô liu", "Cà chua", "Cá cơm"] },
	{ name: "Taco", ingredients: ["Tortilla", "Thịt bò", "Xà lách", "Cà chua", "Phô mai", "Hành tây", "Kem chua", "Guacamole"] },
	{ name: "Enchilada", ingredients: ["Tortilla", "Thịt gà", "Phô mai", "Hành tây", "Sốt Enchilada", "Kem chua"] },
	{ name: "Burrito", ingredients: ["Tortilla", "Cơm", "Đậu", "Thịt bò", "Xà lách", "Phô mai", "Salsa"] },
	{ name: "Ceviche", ingredients: ["Cá", "Chanh xanh", "Hành tây", "Ớt", "Ngò rí", "Cà chua"] },
	{ name: "Feijoada", ingredients: ["Đậu đen", "Thịt heo", "Thịt bò", "Xúc xích", "Cơm", "Hành tây", "Tỏi"] },
	{ name: "Empanada", ingredients: ["Bột mì", "Thịt bò", "Hành tây", "Trứng", "Ô liu", "Nho khô", "Ớt bột (Paprika)"] },
	{ name: "Moussaka", ingredients: ["Cà tím", "Khoai tây", "Thịt bò băm", "Cà chua", "Hành tây", "Sốt Béchamel"] },
	{ name: "Salad Hy Lạp", ingredients: ["Cà chua", "Dưa chuột", "Ô liu", "Phô mai Feta", "Hành tây", "Dầu ô liu"] },
	{ name: "Shakshuka", ingredients: ["Trứng", "Cà chua", "Ớt chuông", "Hành tây", "Tỏi", "Thì là Ai Cập (Cumin)", "Ớt bột (Paprika)"] },
	{ name: "Falafel", ingredients: ["Đậu gà", "Hành tây", "Tỏi", "Ngò tây (Parsley)", "Ngò rí", "Thì là Ai Cập (Cumin)", "Bột mì"] },
	{ name: "Hummus", ingredients: ["Đậu gà", "Tahini (Bơ mè)", "Tỏi", "Chanh vàng", "Dầu ô liu"] },
	{ name: "Shawarma", ingredients: ["Thịt gà", "Thịt bò", "Bánh Pita", "Xà lách", "Cà chua", "Hành tây", "Sữa chua", "Tỏi"] },
	{ name: "Couscous", ingredients: ["Couscous", "Thịt gà", "Cà rốt", "Bí ngòi Hàn Quốc", "Đậu gà", "Hành tây"] },
	{ name: "Tagine", ingredients: ["Thịt cừu", "Mơ", "Hạnh nhân", "Hành tây", "Quế", "Ngò rí", "Nghệ tây"] },
	{ name: "Gà bơ", ingredients: ["Thịt gà", "Bơ", "Kem", "Cà chua", "Hành tây", "Garam Masala (Gia vị Ấn Độ)"] },
	{ name: "Gà Tandoori", ingredients: ["Thịt gà", "Sữa chua", "Garam Masala (Gia vị Ấn Độ)", "Thì là Ai Cập (Cumin)", "Tỏi", "Gừng", "Ớt"] },
	{ name: "Palak Paneer", ingredients: ["Rau chân vịt", "Paneer (Phô mai Ấn Độ)", "Kem", "Hành tây", "Cà chua", "Tỏi", "Thì là Ai Cập (Cumin)"] },
	{ name: "Dal Tadka", ingredients: ["Đậu lăng", "Hành tây", "Cà chua", "Tỏi", "Gừng", "Thì là Ai Cập (Cumin)", "Nghệ", "Bơ Ghee"] },
	{ name: "Biryani", ingredients: ["Cơm", "Thịt gà", "Sữa chua", "Hành tây", "Garam Masala (Gia vị Ấn Độ)", "Nghệ tây"] },
	{ name: "Samosa", ingredients: ["Bột mì", "Khoai tây", "Đậu Hà Lan", "Hành tây", "Thì là Ai Cập (Cumin)", "Ngò rí"] },
	{ name: "Fettuccine Alfredo", ingredients: ["Fettuccine", "Bơ", "Kem", "Phô mai Parmesan"] },
	{ name: "Gà Parmesan", ingredients: ["Thịt gà", "Trứng", "Bột chiên xù", "Phô mai Parmesan", "Phô mai Mozzarella", "Sốt cà chua"] },
	{ name: "Bò Stroganoff", ingredients: ["Thịt bò", "Hành tây", "Nấm", "Kem chua", "Bơ", "Bột mì"] },
	{ name: "Trứng Benedict", ingredients: ["Trứng", "Bánh mì English muffin", "Thịt nguội (Ham)", "Sốt Hollandaise", "Bơ"] },
	{ name: "Súp kem tôm hùm", ingredients: ["Tôm hùm", "Kem", "Bơ", "Hành tây", "Cần tây", "Cà rốt", "Rượu Cognac"] },
	{ name: "Súp nghêu Clam Chowder", ingredients: ["Nghêu", "Khoai tây", "Hành tây", "Cần tây", "Thịt xông khói (Bacon)", "Kem", "Bơ"] },
	{ name: "Bánh gà nướng", ingredients: ["Thịt gà", "Cà rốt", "Khoai tây", "Đậu Hà Lan", "Hành tây", "Vỏ bánh pie", "Kem"] },
	{ name: "Thịt viên nướng", ingredients: ["Thịt bò", "Trứng", "Bột chiên xù", "Hành tây", "Tương cà (Ketchup)", "Mù tạt"] },
	{ name: "Bánh mì nướng kiểu Pháp", ingredients: ["Bánh mì", "Trứng", "Sữa", "Quế", "Đường", "Bơ"] },
	{ name: "Bánh kếp (Pancake)", ingredients: ["Bột mì", "Trứng", "Sữa", "Bột nở (Baking powder)", "Đường", "Bơ"] },
	{ name: "Waffle", ingredients: ["Bột mì", "Trứng", "Sữa", "Bột nở (Baking powder)", "Đường", "Bơ"] },
	{ name: "Bánh mì chuối", ingredients: ["Chuối", "Bột mì", "Trứng", "Đường", "Bơ"] },
	{ name: "Bánh táo", ingredients: ["Táo", "Bột mì", "Trứng", "Đường", "Bơ", "Quế"] },
	{ name: "Bánh tart chanh", ingredients: ["Vỏ bánh tart", "Chanh vàng", "Trứng", "Đường", "Bơ", "Bột mì"] },
	{ name: "Bánh Brownie", ingredients: ["Sô cô la", "Bột mì", "Trứng", "Đường", "Bơ"] },
	{ name: "Bánh phô mai", ingredients: ["Cream cheese", "Trứng", "Đường", "Bơ", "Bánh quy Graham"] },
	{ name: "Súp bí đỏ", ingredients: ["Bí đỏ", "Hành tây", "Tỏi", "Kem", "Bơ"] },
	{ name: "Súp Minestrone", ingredients: ["Đậu", "Cà rốt", "Cần tây", "Hành tây", "Cà chua", "Mì Ý"] },
	{ name: "Trứng ốp lết", ingredients: ["Trứng", "Sữa", "Phô mai", "Thịt nguội (Ham)", "Hành tây", "Ớt chuông"] },
	{ name: "Trứng khuấy", ingredients: ["Trứng", "Sữa", "Bơ", "Muối", "Tiêu"] },
	{ name: "Quesadilla", ingredients: ["Tortilla", "Phô mai", "Thịt gà", "Ớt chuông", "Hành tây"] },
	{ name: "Fajita", ingredients: ["Thịt bò", "Hành tây", "Ớt chuông", "Tortilla", "Kem chua"] },
	{ name: "Thịt heo xé", ingredients: ["Thịt heo", "Sốt BBQ", "Đường nâu", "Hành tây", "Bánh mì"] },
	{ name: "Cá và khoai tây chiên", ingredients: ["Cá", "Khoai tây", "Bột mì", "Trứng", "Dầu ăn"] },
	{ name: "Bánh Shepherd's Pie", ingredients: ["Thịt cừu băm", "Khoai tây", "Cà rốt", "Hành tây", "Đậu Hà Lan", "Nước sốt thịt (Gravy)"] },
	{ name: "Bít tết", ingredients: ["Thịt bò", "Muối", "Tiêu", "Bơ", "Tỏi"] },
	{ name: "Sườn cừu nướng", ingredients: ["Thịt cừu", "Muối", "Tiêu", "Tỏi", "Hương thảo"] },
	{ name: "Gà quay", ingredients: ["Thịt gà", "Muối", "Tiêu", "Tỏi", "Cỏ xạ hương", "Dầu ô liu"] },
	{ name: "Cà ri gà", ingredients: ["Thịt gà", "Hành tây", "Cà chua", "Tỏi", "Gừng", "Bột cà ri", "Nước cốt dừa"] },
	{ name: "Tôm Scampi", ingredients: ["Tôm", "Tỏi", "Bơ", "Chanh vàng", "Ngò tây (Parsley)", "Spaghetti"] },
	{ name: "Paella hải sản", ingredients: ["Cơm", "Tôm", "Vẹm", "Mực ống", "Đậu Hà Lan", "Nghệ tây"] },
	{ name: "Gà Cacciatore", ingredients: ["Thịt gà", "Cà chua", "Hành tây", "Ớt chuông", "Nấm", "Tỏi"] },
	{ name: "Thịt bò hầm rượu vang", ingredients: ["Thịt bò", "Rượu vang đỏ", "Hành tây", "Cà rốt", "Cần tây", "Tỏi", "Cỏ xạ hương"] },
	{ name: "Goulash", ingredients: ["Thịt bò", "Hành tây", "Ớt bột (Paprika)", "Cà chua", "Ớt chuông", "Tỏi"] },
	{ name: "Borsch", ingredients: ["Củ dền", "Bắp cải", "Khoai tây", "Cà rốt", "Hành tây", "Thì là"] },
	{ name: "Pierogi", ingredients: ["Bột mì", "Trứng", "Khoai tây", "Phô mai", "Hành tây", "Bơ"] },
	{ name: "Baklava", ingredients: ["Bột filo", "Óc chó", "Hạt hồ trăn", "Đường", "Bơ", "Mật ong"] },
	{ name: "Dolma", ingredients: ["Lá nho", "Cơm", "Hành tây", "Hạt thông", "Thì là"] },
	{ name: "Cải bắp cuộn", ingredients: ["Bắp cải", "Thịt bò", "Cơm", "Hành tây", "Sốt cà chua"] },
	{ name: "Hầm kiểu Ailen", ingredients: ["Thịt cừu", "Khoai tây", "Cà rốt", "Hành tây", "Cần tây"] },
	{ name: "Cassoulet", ingredients: ["Đậu trắng", "Thịt heo", "Vịt", "Xúc xích", "Hành tây", "Tỏi"] },
	{ name: "Bourekas", ingredients: ["Bột filo", "Phô mai", "Khoai tây", "Trứng", "Hạt mè (Vừng)"] },
	{ name: "Sauerbraten", ingredients: ["Thịt bò", "Hành tây", "Cà rốt", "Cần tây", "Giấm", "Gừng"] },
	{ name: "Wiener Schnitzel", ingredients: ["Thịt bê", "Trứng", "Bột mì", "Bột chiên xù", "Chanh vàng"] },
	{ name: "Zwiebelrostbraten", ingredients: ["Thịt bò", "Hành tây", "Bơ", "Bột mì", "Nước dùng bò"] },
	{ name: "Rösti", ingredients: ["Khoai tây", "Bơ", "Hành tây", "Thịt xông khói (Bacon)"] },
	{ name: "Spätzle", ingredients: ["Bột mì", "Trứng", "Sữa", "Bơ"] },
	{ name: "Súp Goulash", ingredients: ["Thịt bò", "Hành tây", "Ớt bột (Paprika)", "Khoai tây", "Cà rốt"] },
	{ name: "Gà Kiev", ingredients: ["Thịt gà", "Bơ", "Tỏi", "Ngò tây (Parsley)", "Trứng", "Bột mì", "Bột chiên xù"] },
	{ name: "Plov", ingredients: ["Cơm", "Thịt bò", "Cà rốt", "Hành tây", "Thì là Ai Cập (Cumin)"] },
	{ name: "Manti", ingredients: ["Bột mì", "Trứng", "Thịt bò", "Hành tây", "Sữa chua"] },
	{ name: "Mì kiểu Bắc Kinh", ingredients: ["Mì", "Thịt heo", "Trứng", "Hành lá", "Nước tương"] },
	{ name: "Cơm Jollof", ingredients: ["Cơm", "Cà chua", "Hành tây", "Ớt chuông", "Ớt", "Tỏi"] },
	{ name: "Bobotie", ingredients: ["Thịt bò", "Bánh mì", "Trứng", "Hành tây", "Sữa", "Bột cà ri"] },
	{ name: "Bunny Chow", ingredients: ["Bánh mì", "Thịt gà", "Hành tây", "Cà chua", "Bột cà ri"] },
	{ name: "Chakalaka", ingredients: ["Đậu", "Hành tây", "Cà chua", "Ớt", "Cà rốt", "Ớt chuông"] },
	{ name: "Pav Bhaji", ingredients: ["Bánh mì", "Khoai tây", "Đậu Hà Lan", "Cà rốt", "Hành tây", "Cà chua", "Bơ"] },
	{ name: "Vada Pav", ingredients: ["Bánh mì", "Khoai tây", "Ớt", "Ngò rí", "Tỏi", "Hạt mù tạt"] },
	{ name: "Masala Dosa", ingredients: ["Gạo", "Đậu lăng", "Khoai tây", "Hành tây", "Hạt mù tạt", "Lá cà ri"] },
	{ name: "Idli", ingredients: ["Gạo", "Đậu lăng", "Muối"] },
	{ name: "Sambar", ingredients: ["Đậu lăng", "Cà rốt", "Hành tây", "Cà chua", "Cà tím", "Đùi gà (Rau)", "Hỗn hợp gia vị"] },
	{ name: "Cà ri Katsu", ingredients: ["Cơm", "Thịt heo chiên xù (Tonkatsu)", "Sốt cà ri", "Hành tây", "Cà rốt", "Khoai tây"] },
	{ name: "Okonomiyaki (Bánh xèo Nhật)", ingredients: ["Bột mì", "Trứng", "Bắp cải", "Thịt heo", "Tôm", "Sốt mayonnaise", "Sốt Okonomiyaki"] },
	{ name: "Takoyaki", ingredients: ["Bột mì", "Trứng", "Bạch tuộc", "Hành lá", "Vụn chiên giòn (Tenkasu)", "Sốt mayonnaise", "Sốt Takoyaki"] },
	{ name: "Sukiyaki", ingredients: ["Thịt bò", "Đậu phụ", "Hành lá", "Nấm hương (Shiitake)", "Khoai konjac", "Trứng"] },
	{ name: "Nabe", ingredients: ["Bắp cải", "Đậu phụ", "Nấm hương (Shiitake)", "Cà rốt", "Thịt gà", "Udon"] },
	{ name: "Canh trứng", ingredients: ["Trứng", "Nước dùng gà", "Bột ngô", "Hành lá", "Nước tương"] },
	{ name: "Canh chua cay (Sản La Thang)", ingredients: ["Đậu phụ", "Trứng", "Nấm", "Măng tre", "Giấm", "Nước tương", "Tiêu"] },
	{ name: "Bò xào bông cải xanh", ingredients: ["Thịt bò", "Bông cải xanh", "Nước tương", "Tỏi", "Gừng", "Hành tây"] },
	{ name: "Gà sốt chanh", ingredients: ["Thịt gà", "Chanh vàng", "Trứng", "Bột mì", "Nước tương", "Đường"] },
	{ name: "Cơm chiên dứa", ingredients: ["Cơm", "Dứa", "Tôm", "Trứng", "Hạt điều", "Hành lá"] },
	{ name: "Bánh mì", ingredients: ["Bánh mì baguette", "Thịt heo", "Cà rốt", "Dưa chuột", "Ngò rí", "Sốt mayonnaise", "Pate"] },
	{ name: "Khao Soi", ingredients: ["Mì trứng", "Thịt gà", "Nước cốt dừa", "Bột cà ri", "Cải muối"] },
	{ name: "Bak Kut Teh", ingredients: ["Sườn heo", "Tỏi", "Nước tương", "Tiêu trắng", "Nấm"] },
	{ name: "Cơm gà Hải Nam", ingredients: ["Thịt gà", "Cơm", "Gừng", "Tỏi", "Dưa chuột", "Nước tương", "Sốt ớt"] },
	{ name: "Laksa Singapore", ingredients: ["Bún (Bún laksa)", "Tôm", "Nước cốt dừa", "Đậu phụ", "Giá đỗ", "Trứng", "Ớt", "Ngò rí"] },
	{ name: "Gado-Gado", ingredients: ["Rau củ", "Đậu phụ", "Trứng", "Sốt đậu phộng", "Giá đỗ"] },
	{ name: "Nasi Lemak", ingredients: ["Cơm", "Nước cốt dừa", "Trứng", "Cá cơm", "Đậu phộng", "Dưa chuột", "Sốt Sambal"] },
	{ name: "Mì Ý Pesto Rau Arugula", ingredients: ["Rau Arugula", "Mì Ý (Pasta)", "Phô mai Parmesan", "Dầu ô liu", "Hạt thông"] },
	{ name: "Shakshuka phô mai Feta", ingredients: ["Trứng", "Cà chua", "Ớt chuông", "Hành tây", "Phô mai Feta", "Ngò rí"] },
	{ name: "Bánh kếp Buttermilk", ingredients: ["Bột mì", "Trứng", "Buttermilk", "Đường", "Bột nở (Baking powder)"] },
	{ name: "Salad Quinoa", ingredients: ["Quinoa", "Dưa chuột", "Cà chua", "Phô mai Feta", "Chanh vàng", "Dầu ô liu"] },
	{ name: "Salad Caesar cải xoăn", ingredients: ["Cải xoăn", "Phô mai Parmesan", "Bánh mì nướng giòn (Crouton)", "Cá cơm", "Trứng", "Sốt Caesar"] },
	{ name: "Bát Buddha thuần chay", ingredients: ["Cơm gạo lứt", "Đậu gà", "Quả bơ", "Rau chân vịt", "Cà rốt", "Đậu phụ"] },
	{ name: "Cà tím Parmesan", ingredients: ["Cà tím", "Sốt cà chua", "Phô mai Mozzarella", "Phô mai Parmesan", "Húng quế"] },
	{ name: "Ớt chuông nhồi", ingredients: ["Ớt chuông", "Cơm", "Thịt bò băm", "Hành tây", "Cà chua", "Phô mai"] },
	{ name: "Sườn cừu nướng", ingredients: ["Thịt cừu", "Tỏi", "Hương thảo", "Dầu ô liu", "Muối", "Tiêu"] },
	{ name: "Súp đậu lăng", ingredients: ["Đậu lăng", "Cà rốt", "Cần tây", "Hành tây", "Cà chua", "Tỏi"] },
	{ name: "Cải Brussels nướng", ingredients: ["Cải Brussels", "Dầu ô liu", "Muối", "Tiêu", "Chanh vàng"] },
	{ name: "Gà sốt Pesto", ingredients: ["Thịt gà", "Sốt Pesto húng quế", "Phô mai Parmesan", "Dầu ô liu"] },
	{ name: "Salsa xoài", ingredients: ["Xoài", "Hành tây", "Chanh xanh", "Ngò rí", "Ớt"] },
	{ name: "Cá tuyết nướng", ingredients: ["Cá tuyết", "Chanh vàng", "Dầu ô liu", "Ngò tây (Parsley)", "Bột chiên xù"] },
	{ name: "Asian Slaw (Gỏi bắp cải kiểu Á)", ingredients: ["Cải thảo", "Cà rốt", "Hành lá", "Nước tương", "Giấm gạo", "Dầu mè"] },
	{ name: "Salad mì đậu phộng", ingredients: ["Mì", "Đậu phộng", "Cà rốt", "Dưa chuột", "Nước tương", "Dầu mè"] },
	{ name: "Chili thuần chay", ingredients: ["Đậu đen", "Cà chua", "Hành tây", "Bột ớt", "Ngô (Bắp)", "Ớt chuông"] },
	{ name: "Salad Gado-Gado", ingredients: ["Rau củ", "Đậu phụ", "Trứng", "Sốt đậu phộng", "Giá đỗ"] },
	{ name: "Taco mít non", ingredients: ["Mít non", "Tortilla", "Bắp cải", "Chanh xanh", "Quả bơ", "Ngò rí"] },
	{ name: "Đậu phụ xào rau củ", ingredients: ["Đậu phụ", "Bông cải xanh", "Ớt chuông", "Nước tương", "Gừng", "Tỏi"] },
	{ name: "Risotto bí đỏ", ingredients: ["Bí đỏ", "Gạo", "Phô mai Parmesan", "Hành tây", "Tỏi"] },
	{ name: "Bánh mì nướng Ratatouille", ingredients: ["Cà tím", "Bí ngòi Hàn Quốc", "Ớt chuông", "Hành tây", "Bánh mì"] },
	{ name: "Salad củ dền", ingredients: ["Củ dền", "Rau Arugula", "Óc chó", "Phô mai dê", "Sốt Balsamic"] },
	{ name: "Tagine Ma-rốc", ingredients: ["Thịt cừu", "Mơ", "Hạnh nhân", "Hành tây", "Quế", "Ngò rí", "Nghệ tây"] },
	{ name: "Bít tết Chimichurri", ingredients: ["Thịt bò", "Ngò tây (Parsley)", "Tỏi", "Dầu ô liu", "Kinh giới", "Giấm"] },
	{ name: "Bánh rán bí ngòi", ingredients: ["Bí ngòi Hàn Quốc", "Trứng", "Bột mì", "Phô mai Parmesan", "Hành lá"] },
	{ name: "Súp Miso", ingredients: ["Tương Miso", "Đậu phụ", "Rong biển (Wakame)", "Hành lá", "Nước dùng rong biển (Dashi)"] },
	{ name: "Bánh cuộn Falafel", ingredients: ["Falafel", "Bánh Pita", "Xà lách", "Cà chua", "Tahini (Bơ mè)"] },
	{ name: "Laksa tôm", ingredients: ["Tôm", "Bún (Bún laksa)", "Nước cốt dừa", "Bột laksa", "Trứng", "Giá đỗ"] },
	{ name: "Bát Couscous", ingredients: ["Couscous", "Đậu gà", "Cà rốt", "Bí ngòi Hàn Quốc", "Chanh vàng"] },
	{ name: "Dakgangjeong (Gà tẩm sốt)", ingredients: ["Thịt gà", "Tương ớt Gochujang", "Nước tương", "Đường", "Siro gạo (Mùn yul)", "Tỏi", "Gừng", "Bột chiên"] },
	{ name: "Budae Jjigae (Lẩu quân đội)", ingredients: ["Thịt nguội (Ham)", "Xúc xích", "Kimchi", "Đậu phụ", "Giá đỗ", "Mì Ramyeon ăn kèm", "Tương ớt Gochujang", "Bột ớt", "Hành lá"] },
	{ name: "Galbitang (Canh sườn bò)", ingredients: ["Sườn bò", "Củ cải trắng", "Hành lá", "Tỏi", "Gừng", "Nước tương", "Miến"] },
	{ name: "Haemul Pajeon (Bánh xèo hải sản)", ingredients: ["Mực ống", "Tôm", "Hành lá (Hành boa rô)", "Bột mì", "Trứng", "Nước", "Nước tương", "Giấm"] },
	{ name: "Yukgaejang (Canh thịt bò cay)", ingredients: ["Thịt bò", "Rau dương xỉ (Gosari)", "Giá đỗ", "Thân cây khoai môn", "Hành lá", "Bột ớt", "Nước tương", "Tỏi"] },
	{ name: "Bossam (Thịt luộc cuốn rau)", ingredients: ["Thịt heo", "Tỏi", "Gừng", "Hành lá", "Tương đậu (Doenjang)", "Mắm tép (Saeujeot)", "Kimchi củ cải", "Bắp cải"] },
	{ name: "Samgyetang (Gà tần sâm)", ingredients: ["Thịt gà", "Nhân sâm", "Táo tàu (Đại táo)", "Tỏi", "Gạo nếp", "Hành lá", "Muối"] },
	{ name: "Jjimdak (Gà hấp xì dầu)", ingredients: ["Thịt gà", "Khoai tây", "Cà rốt", "Hành tây", "Hành lá", "Miến", "Nước tương", "Đường", "Tỏi"] },
	{ name: "Bibim Guksu (Mì trộn cay)", ingredients: ["Mì", "Tương ớt Gochujang", "Giấm", "Đường", "Dưa chuột", "Xà lách", "Trứng", "Dầu mè"] },
	{ name: "Gimbap", ingredients: ["Cơm", "Rong biển", "Củ cải muối (Danmuji)", "Rau chân vịt", "Cà rốt", "Trứng", "Thịt nguội (Ham)", "Chả cá", "Dầu mè"] },
	{ name: "Jeyuk Bokkeum (Thịt heo xào cay)", ingredients: ["Thịt heo", "Tương ớt Gochujang", "Bột ớt", "Nước tương", "Đường", "Tỏi", "Hành tây", "Hành lá"] },
	{ name: "Dakbokkeumtang (Gà hầm cay)", ingredients: ["Thịt gà", "Khoai tây", "Cà rốt", "Hành tây", "Hành lá", "Tương ớt Gochujang", "Bột ớt", "Tỏi"] },
	{ name: "Doenjang Jjigae (Canh tương đậu)", ingredients: ["Tương đậu (Doenjang)", "Đậu phụ", "Bí ngòi Hàn Quốc", "Hành tây", "Hành lá", "Nấm", "Ớt", "Nước dùng cá cơm"] },
	{ name: "Agujjim (Cá đù gai hấp cay)", ingredients: ["Cá đù gai (Anglerfish)", "Giá đỗ", "Mi-deodeok (Hến biển gai)", "Rau cần nước (Minari)", "Bột ớt", "Tỏi", "Nước tương", "Tinh bột"] },
	{ name: "Gopchang Jeongol (Lẩu lòng bò)", ingredients: ["Lòng bò", "Hành lá", "Hành tây", "Lá vừng (Kkaennip)", "Nấm", "Đậu phụ", "Bột ớt", "Tỏi băm", "Nước dùng"] },
	{ name: "Gà sốt Yangnyeom", ingredients: ["Thịt gà", "Tương ớt Gochujang", "Siro gạo (Mùn yul)", "Tương cà (Ketchup)", "Tỏi", "Nước tương", "Đậu phộng", "Bột chiên"] },
	{ name: "Gukbap (Cơm canh)", ingredients: ["Cơm", "Thịt heo", "Nội tạng", "Hành lá", "Tỏi", "Bột ớt", "Sundae (Dồi lợn Hàn Quốc)"] },
	{ name: "Mì Ý Aglio e Olio", ingredients: ["Spaghetti", "Tỏi", "Dầu ô liu", "Ớt khô Peperoncino", "Ngò tây (Parsley)"] },
	{ name: "Mì Ý Vongole", ingredients: ["Spaghetti", "Nghêu", "Tỏi", "Dầu ô liu", "Rượu vang trắng", "Ngò tây (Parsley)"] },
	{ name: "Gambas al Ajillo (Tôm nướng tỏi dầu ô liu)", ingredients: ["Tôm", "Tỏi", "Dầu ô liu", "Ớt khô Peperoncino", "Bánh mì Baguette"] },
	{ name: "Bít tết thái hạt lựu (Chop Steak)", ingredients: ["Thịt bò", "Ớt chuông", "Hành tây", "Nấm", "Nước tương", "Tương cà (Ketchup)", "Đường", "Sốt bít tết"] },
	{ name: "Salad Ricotta", ingredients: ["Phô mai Ricotta", "Rau mầm non", "Sốt Balsamic", "Cà chua", "Các loại hạt"] },
	{ name: "Gamjajeon (Bánh khoai tây chiên)", ingredients: ["Khoai tây", "Hành tây", "Bột chiên (Bột bánh xèo)", "Nước", "Muối", "Dầu ăn"] },
	{ name: "Cá thu nướng", ingredients: ["Cá thu", "Muối", "Tiêu", "Chanh vàng", "Dầu ăn"] },
	{ name: "Jjukkumi Bokkeum (Bạch tuộc xào cay)", ingredients: ["Bạch tuộc con", "Hành tây", "Hành lá", "Bắp cải", "Tương ớt Gochujang", "Bột ớt", "Tỏi", "Đường"] },
	{ name: "Dakbal Bokkeum (Chân gà xào cay)", ingredients: ["Chân gà", "Tương ớt Gochujang", "Bột ớt", "Tỏi", "Hành tây", "Hành lá", "Đường", "Siro gạo (Mùn yul)"] },
	{ name: "Kem", ingredients: ["Sữa", "Đường", "Lòng đỏ trứng", "Kem tươi", "Vani"] },
	{ name: "Tiramisu", ingredients: ["Phô mai Mascarpone", "Bánh Ladyfinger", "Cà phê", "Đường", "Lòng đỏ trứng", "Bột cacao"] },
	{ name: "Macaron", ingredients: ["Bột hạnh nhân", "Đường bột", "Lòng trắng trứng", "Đường", "Phẩm màu thực phẩm"] },
	{ name: "Croffle", ingredients: ["Bột làm Croissant", "Khuôn làm Waffle", "Đường", "Bơ"] },
	{ name: "Bánh tart trứng", ingredients: ["Vỏ bánh tart", "Trứng", "Sữa", "Đường", "Kem tươi", "Chiết xuất vani"] },
	{ name: "An Butter (Bánh mì kẹp đậu đỏ và bơ)", ingredients: ["Bánh mì", "Đậu đỏ nghiền (Anko)", "Bơ"] },
	{ name: "Hotteok (Bánh pancake ngọt)", ingredients: ["Bột mì", "Đường", "Men nở", "Nước", "Hạt", "Mật ong"] },
	{ name: "Bungeoppang (Bánh cá)", ingredients: ["Bột mì", "Trứng", "Sữa", "Đường", "Nhân đậu đỏ", "Bơ"] },
	{ name: "Hot dog", ingredients: ["Xúc xích", "Bánh mì", "Tương cà (Ketchup)", "Mù tạt", "Hành tây", "Dưa chuột muối"] },
	{ name: "Súp hành tây kiểu Pháp", ingredients: ["Hành tây", "Nước dùng bò", "Bánh mì", "Phô mai", "Bơ", "Bột mì"] },
	{ name: "Spaghetti thịt viên", ingredients: ["Spaghetti", "Thịt bò băm", "Sốt cà chua", "Hành tây", "Tỏi", "Bột chiên xù", "Trứng"] },
	{ name: "Taco cá", ingredients: ["Cá", "Tortilla", "Bắp cải", "Salsa", "Chanh xanh", "Ngò rí"] },
	{ name: "Bánh scone phô mai", ingredients: ["Bột mì", "Bơ", "Sữa", "Phô mai", "Bột nở (Baking powder)"] },
	{ name: "Bánh muffin việt quất", ingredients: ["Bột mì", "Việt quất", "Đường", "Trứng", "Sữa", "Dầu ăn", "Bột nở (Baking powder)"] }
];

window.INGREDIENTS_DB = [
	"Trứng", "Thịt gà", "Thịt bò", "Thịt heo", "Hành tây", "Tỏi", "Cà rốt", "Khoai tây", "Spaghetti", "Cơm", "Cà chua", "Xà lách",
	"Đậu phụ", "Giá đỗ", "Đậu phộng", "Rượu vang đỏ", "Tương đậu (Doenjang)", "Rong biển (Kim)", "Kimchi", "Thịt xông khói (Bacon)", "Phô mai Parmesan", "Cá cơm", "Bánh mì",
	"Phô mai", "Tôm", "Sả", "Riềng", "Chanh xanh", "Ớt chuông", "Cà tím", "Bí ngòi Hàn Quốc", "Bánh mì nướng giòn (Crouton)", "Nước dùng rong biển (Dashima)",
	"Pancetta", "Tiêu", "Nấm", "Sữa chua", "Bột mì", "Đường", "Muối", "Bơ", "Sữa", "Kem", "Dưa chuột",
	"Táo", "Chuối", "Cam", "Chanh vàng", "Chanh xanh", "Bông cải xanh", "Rau chân vịt", "Bí đỏ", "Khoai lang", "Ngô (Bắp)", "Đậu Hà Lan",
	"Bắp cải", "Cần tây", "Gừng", "Nước tương", "Giấm", "Dầu ô liu", "Dầu hạt cải", "Dầu hướng dương", "Dầu mè",
	"Nước mắm", "Dầu hào", "Tương đen (Hoisin sauce)", "Tương cà (Ketchup)", "Mù tạt", "Sốt mayonnaise", "Húng quế", "Ngò rí (Rau mùi)", "Ngò tây (Parsley)",
	"Hương thảo", "Cỏ xạ hương", "Ngải đắng", "Bạc hà", "Quế", "Hạt nhục đậu khấu", "Đinh hương", "Lá nguyệt quế", "Hoa hồi", "Bạch đậu khấu",
	"Bột cà ri", "Bột ớt", "Ớt bột (Paprika)", "Nghệ", "Thì là Ai Cập (Cumin)", "Thì là", "Thì là tây (Fennel)", "Vani",
	"Sô cô la", "Bột cacao", "Mứt", "Mật ong", "Siro cây phong", "Mật rỉ đường", "Dâu tây", "Việt quất", "Mâm xôi",
	"Nam việt quất", "Mâm xôi đen", "Dứa (Thơm)", "Xoài", "Kiwi", "Nho", "Lê", "Đào", "Mơ", "Mận", "Táo tàu (Đại táo)",
	"Quả sung", "Dừa", "Óc chó", "Hạnh nhân", "Hạt phỉ", "Hạt điều", "Hạt hồ trăn", "Hạt Macadamia", "Hạt hồ đào (Pecan)", "Hạt hướng dương",
	"Hạt chia", "Hạt bí", "Hạt mè (Vừng)", "Quinoa", "Lúa mạch", "Kê", "Kiều mạch", "Yến mạch", "Bánh mì", "Mì Ý (Pasta)",
	"Mì", "Tortilla", "Bánh Naan", "Bánh Pita", "Bánh mì Sourdough", "Bánh Bagel", "Bánh Croissant", "Bánh Donut", "Đế bánh pizza", "Bánh quy mặn (Cracker)",
	"Xúc xích", "Salami", "Thịt nguội (Ham)", "Vịt", "Thịt cừu", "Gà tây", "Thỏ", "Thịt bê", "Ngỗng", "Cá cơm", "Cá mòi", "Cá ngừ",
	"Cá thu", "Cá Haddock", "Cá Pollack", "Cá trê", "Cá rô phi", "Mực ống", "Bạch tuộc", "Nghêu", "Vẹm",
	"Sò điệp", "Tôm hùm", "Cua", "Tôm càng", "Bào ngư", "Hải sâm", "Nhím biển", "Wasabi", "Cải ngựa (Horseradish)",
	"Sốt Tabasco", "Tương ớt Sriracha", "Tương ớt Gochujang", "Tương chấm Ssamjang", "Tương Miso", "Đậu đỏ", "Đậu đen", "Đậu",
	"Đậu gà", "Đậu lăng", "Đậu thận (Kidney bean)", "Đậu Navy", "Đậu que", "Đậu Hà Lan dẹt", "Đậu Hà Lan ngọt", "Đậu nành Edamame", "Phô mai Mozzarella",
	"Phô mai Cheddar", "Phô mai Gouda", "Phô mai Brie", "Phô mai Camembert", "Phô mai Feta", "Phô mai xanh", "Phô mai Thụy Sĩ", "Phô mai Provolone", "Phô mai Ricotta",
	"Phô mai Mascarpone", "Cream cheese", "Phô mai tươi (Cottage cheese)", "Kem chua", "Buttermilk", "Sữa đặc",
	"Sữa đặc có đường", "Sữa bột", "Sữa hạnh nhân", "Sữa đậu nành", "Sữa gạo", "Nước cốt dừa", "Sữa yến mạch",
	"Mắm tôm", "Mắm cá cơm", "Sốt cà chua cô đặc", "Sốt cà chua", "Sốt Pesto", "Piri-piri (Ớt)", "Harissa (Tương ớt Bắc Phi)", "Ajvar (Sốt ớt chuông)",
	"Tahini (Bơ mè)", "Hummus (Sốt đậu gà)", "Guacamole (Sốt bơ)", "Salsa", "Relish (Dưa góp)", "Tapenade (Pate ô liu)", "Nước sốt thịt (Gravy)", "Nước dùng", "Viên súp cô đặc (Bouillon)", "Nước hầm xương (Broth)", "Gelatin",
	"Thạch rau câu (Agar-agar)", "Bột ngô", "Bột khoai tây", "Bột năng (Bột sắn)", "Bột dong riềng (Arrowroot starch)", "Bột gạo", "Bột Semolina", "Bột ngô thô",
	"Polenta (Bột ngô)", "Mầm lúa mì", "Cám lúa mì", "Bánh tráng", "Vỏ chả giò (Spring roll wrapper)", "Rong biển", "Bánh gạo (Tteok)", "Udon", "Ramen",
	"Bún (Vermicelli)", "Soba", "Fettuccine", "Penne", "Macaroni", "Lasagna", "Spaghetti", "Linguine", "Angel Hair",
	"Gnocchi", "Ravioli", "Tortellini", "Bánh bao (Mantu)", "Hoành thánh (Wonton)", "Pierogi", "Empanada", "Tamale", "Hành lá (Hành boa rô)",
	"Hành tím", "Tỏi tây", "Củ cải turnip", "Củ cải đỏ", "Củ parsnip", "Củ cải Thụy Điển", "Củ dền", "Củ cải Thụy Điển", "Củ cải trắng", "Củ đậu", "Củ sen",
	"Atiso", "Măng tây", "Đậu bắp", "Măng tre", "Lòng đỏ trứng", "Lòng trắng trứng", "Trứng cút", "Trứng vịt", "Trứng ngỗng",
	"Nấm Truffle", "Nấm Morels", "Nấm Porcini", "Nấm Enoki", "Nấm hương (Shiitake)", "Nấm bào ngư", "Nấm đùi gà", "Nấm mỡ (Champignon)", "Nấm Portobello",
	"Hạt dẻ", "Củ mã thầy", "Khoai môn", "Khoai mỡ", "Khoai mì (Sắn)", "Salsify", "Atiso Jerusalem", "Củ thì là tây",
	"Rau Arugula", "Sốt Pesto húng quế", "Cải thìa", "Cải Brussels", "Nụ bạch hoa",
	"Caramel", "Hạt Caraway", "Hạt Chia", "Dầu ớt", "Hẹ", "Hạt ngò rí", "Cua", "Nam việt quất", "Cải xoong",
	"Bồ công anh", "Táo tàu (Đại táo)", "Vỏ ram (Egg roll wrapper)", "Farro (Lúa mì Farro)", "Cỏ cà ri",
	"Phô mai Feta", "Bơ Ghee", "Phô mai dê", "Đậu que", "Ổi", "Hạt phỉ", "Hạt cây gai dầu", "Hỗn hợp thảo mộc",
	"Mít (Jackfruit)", "Cải xoăn", "Nước Kimchi", "Quất (Hạnh)", "Tỏi tây", "Mì Ý (Pasta)", "Vải", "Chutney xoài",
	"Phô mai Manchego", "Thịt xông khói siro phong", "Kinh giới ngọt", "Cải Mizuna", "Quả La Hán", "Nước sốt nấm", "Lá mù tạt",
	"Cải thảo (Bok Choy)", "Nectarine", "Lá đậu bắp", "Ô liu", "Vỏ cam bào", "Đu đủ", "Chanh dây", "Mầm đậu Hà Lan",
	"Hạt hồ đào (Pecan)", "Phô mai Pepper Jack", "Quả hồng", "Hạt thông", "Kem hạt hồ trăn", "Cà chua mận", "Bỏng ngô", "Prosciutto",
	"Bánh mì Pumpernickel", "Quark (Phô mai Quark)", "Rau Radicchio", "Ras el Hanout (Gia vị hỗn hợp)", "Đậu lăng đỏ", "Ricotta Salata (Phô mai Ricotta khô)", "Rau rocket (Rau Arugula)", "Xà lách Romaine",
	"Phô mai Roquefort", "Nước hoa hồng", "Củ cải Thụy Điển", "Sago (Bột sago)", "Salsify", "Bắp cải Savoy", "Hành lá (Chives)",
	"Lá tía tô Nhật (Shiso)", "Đậu phụ non (Silken Tofu)", "Cá hồi hun khói", "Rau chua (Sorrel)", "Đạm đậu nành", "Lúa mì Spelt",
	"Mực ống (mực nang)", "Phô mai Stilton", "Nấm rơm (Straw mushroom)", "Sumac (Gia vị Sumac)", "Cà chua khô", "Ngô ngọt", "Cải cầu vồng Thụy Sĩ",
	"Me", "Tempeh", "Hạt mè rang", "Váng đậu", "Cà chua Mēxicō", "Dầu truffle", "Lá củ cải turnip",
	"Cam Valencia", "Phô mai thuần chay", "Thịt nai", "Bún (Vermicelli)", "Cơm giấm", "Cải xoong nước", "Hạt lúa mì",
	"Sô cô la trắng", "Gạo hoang dã", "Za'atar (Gia vị Trung Đông)", "Vỏ cam/chanh bào", "Hoa bí ngòi", "Đậu Azuki", "Amaranth (Hạt dền)",
	"Hồi hương", "Măng tre", "Ớt chuối", "Hạt húng quế", "Sò điệp nhỏ", "Tỏi đen", "Cam đỏ",
	"Borage (Rau borage)", "Bresaola (Thịt bò muối)", "Xương rồng", "Mực ống", "Dưa Canary", "Gừng ngâm đường", "Lá cà rốt", "Bột khoai mì (Bột sắn)",
	"Củ cần tây", "Su su", "Nấm Chestnut", "Xúc xích Chorizo", "Quả Cloudberry", "Đường dừa", "Tỏi confit",
	"Salad ngô", "Đậu Cranberry", "Nấm Cremini", "Diatom (Tảo silic)", "Edo (Tên địa danh)", "Rau dương xỉ (고사리)", "Trứng cá", "Rau Frisée", "Garam Masala (Gia vị Ấn Độ)",
	"Hẹ tỏi", "Kỷ tử", "Củ dền vàng", "Tỏi non", "Guanciale", "Xương giò heo hun khói (Ham hock)", "Rễ cải ngựa (Horseradish root)",
	"Atiso Jerusalem", "Chanh Kaffir", "Rễ cam thảo", "Rong biển Kombu", "Oải hương", "Limoncello (Rượu mùi chanh)", "Đậu đũa (Đậu que dài)",
	"Hạt sen", "Caramel Miso", "Myzithra (Phô mai Hy Lạp)", "Quả dâu tằm", "Nho Muscadine", "Cây Nasturtium", "Cây tầm ma", "Lá đậu bắp",
	"Olallieberry (Mâm xôi Olallie)", "Lá Parsnip", "Bí ngòi Pattypan", "Phô mai Pecorino", "Dưa Pepino", "Lá vừng (Kkaennip)", "Củ cải muối",
	"Đậu Pigeon", "Cây xô thơm dứa", "Hạt tiêu hồng", "Plumcot (Mận lai mơ)", "Ớt Poblano", "Rau sam", "Quả Mộc qua", "Tỏi rừng",
	"Cây đại hoàng", "Tỏi nướng", "Bông cải Romanesco", "Đậu đũa", "Lá củ cải Thụy Điển", "Trứng cá hồi", "Satsuma (Quýt Satsuma)", "Măng tây biển",
	"Thịt nguội", "Xúc xích", "Mì Ramyeon ăn kèm", "Củ cải trắng", "Hành lá", "Mực ống", "Mi-deodeok (Hến biển gai)", "Rau cần nước (Minari)",
	"Thân cây khoai môn", "Rau dương xỉ", "Mắm tép (Saeujeot)", "Nhân sâm", "Táo tàu (Đại táo)", "Gạo nếp", "Tinh bột", "Lòng bò",
	"Nước dùng", "Siro gạo (Mùn yul)", "Cá chày (Cá Angler)", "Sundae (Dồi lợn Hàn Quốc)",
	"Ớt khô Peperoncino", "Bánh mì Baguette", "Rượu vang trắng", "Sốt bít tết", "Rau mầm non", "Sốt Balsamic", "Các loại hạt",
	"Bột chiên (Bột bánh xèo)", "Cá thu", "Bạch tuộc con (Jjukkumi)", "Bắp cải", "Chân gà", "Bột hạnh nhân", "Đường bột", "Phẩm màu thực phẩm",
	"Bột làm Croissant", "Khuôn làm Waffle", "Vỏ bánh tart", "Chiết xuất vani", "Đậu đỏ nghiền (Anko)", "Men nở", "Hạt", "Mật ong", "Nhân đậu đỏ",
	"Xúc xích", "Dầu ăn", "Bột nở (Baking powder)"
];