const flags = [
    { country: "Афганистан", img: "https://flagcdn.com/af.svg" },
    { country: "Аландские острова", img: "https://flagcdn.com/ax.svg" },
    { country: "Албания", img: "https://flagcdn.com/al.svg" },
    { country: "Алжир", img: "https://flagcdn.com/dz.svg" },
    { country: "Американское Самоа", img: "https://flagcdn.com/as.svg" },
    { country: "Андорра", img: "https://flagcdn.com/ad.svg" },
    { country: "Ангола", img: "https://flagcdn.com/ao.svg" },
    { country: "Ангилья", img: "https://flagcdn.com/ai.svg" },
    { country: "Антарктида", img: "https://flagcdn.com/aq.svg" },
    { country: "Антигуа и Барбуда", img: "https://flagcdn.com/ag.svg" },
    { country: "Аргентина", img: "https://flagcdn.com/ar.svg" },
    { country: "Армения", img: "https://flagcdn.com/am.svg" },
    { country: "Аруба", img: "https://flagcdn.com/aw.svg" },
    { country: "Австралия", img: "https://flagcdn.com/au.svg" },
    { country: "Австрия", img: "https://flagcdn.com/at.svg" },
    { country: "Азербайджан", img: "https://flagcdn.com/az.svg" },
    { country: "Багамы", img: "https://flagcdn.com/bs.svg" },
    { country: "Бахрейн", img: "https://flagcdn.com/bh.svg" },
    { country: "Бангладеш", img: "https://flagcdn.com/bd.svg" },
    { country: "Барбадос", img: "https://flagcdn.com/bb.svg" },
    { country: "Беларусь", img: "https://flagcdn.com/by.svg" },
    { country: "Бельгия", img: "https://flagcdn.com/be.svg" },
    { country: "Белиз", img: "https://flagcdn.com/bz.svg" },
    { country: "Бенин", img: "https://flagcdn.com/bj.svg" },
    { country: "Бермуды", img: "https://flagcdn.com/bm.svg" },
    { country: "Бутан", img: "https://flagcdn.com/bt.svg" },
    { country: "Боливия", img: "https://flagcdn.com/bo.svg" },
    { country: "Карибские Нидерланды", img: "https://flagcdn.com/bq.svg" },
    { country: "Босния и Герцеговина", img: "https://flagcdn.com/ba.svg" },
    { country: "Ботсвана", img: "https://flagcdn.com/bw.svg" },
    { country: "Остров Буве", img: "https://flagcdn.com/bv.svg" },
    { country: "Бразилия", img: "https://flagcdn.com/br.svg" },
    { country: "Британская территория в Индийском океане", img: "https://flagcdn.com/io.svg" },
    { country: "Британские Виргинские острова", img: "https://flagcdn.com/vg.svg" },
    { country: "Бруней", img: "https://flagcdn.com/bn.svg" },
    { country: "Болгария", img: "https://flagcdn.com/bg.svg" },
    { country: "Буркина-Фасо", img: "https://flagcdn.com/bf.svg" },
    { country: "Бурунди", img: "https://flagcdn.com/bi.svg" },
    { country: "Кабо-Верде", img: "https://flagcdn.com/cv.svg" },
    { country: "Камбоджа", img: "https://flagcdn.com/kh.svg" },
    { country: "Камерун", img: "https://flagcdn.com/cm.svg" },
    { country: "Канада", img: "https://flagcdn.com/ca.svg" },
    { country: "Каймановы острова", img: "https://flagcdn.com/ky.svg" },
    { country: "Центральноафриканская Республика", img: "https://flagcdn.com/cf.svg" },
    { country: "Чад", img: "https://flagcdn.com/td.svg" },
    { country: "Чили", img: "https://flagcdn.com/cl.svg" },
    { country: "Китай", img: "https://flagcdn.com/cn.svg" },
    { country: "Остров Рождества", img: "https://flagcdn.com/cx.svg" },
    { country: "Кокосовые острова", img: "https://flagcdn.com/cc.svg" },
    { country: "Колумбия", img: "https://flagcdn.com/co.svg" },
    { country: "Коморы", img: "https://flagcdn.com/km.svg" },
    { country: "Демократическая Республика Конго", img: "https://flagcdn.com/cd.svg" },
    { country: "Республика Конго", img: "https://flagcdn.com/cg.svg" },
    { country: "Острова Кука", img: "https://flagcdn.com/ck.svg" },
    { country: "Коста-Рика", img: "https://flagcdn.com/cr.svg" },
    { country: "Кот-д'Ивуар", img: "https://flagcdn.com/ci.svg" },
    { country: "Хорватия", img: "https://flagcdn.com/hr.svg" },
    { country: "Куба", img: "https://flagcdn.com/cu.svg" },
    { country: "Кюрасао", img: "https://flagcdn.com/cw.svg" },
    { country: "Кипр", img: "https://flagcdn.com/cy.svg" },
    { country: "Чехия", img: "https://flagcdn.com/cz.svg" },
    { country: "Дания", img: "https://flagcdn.com/dk.svg" },
    { country: "Джибути", img: "https://flagcdn.com/dj.svg" },
    { country: "Доминика", img: "https://flagcdn.com/dm.svg" },
    { country: "Доминиканская Республика", img: "https://flagcdn.com/do.svg" },
    { country: "Эквадор", img: "https://flagcdn.com/ec.svg" },
    { country: "Египет", img: "https://flagcdn.com/eg.svg" },
    { country: "Сальвадор", img: "https://flagcdn.com/sv.svg" },
    { country: "Экваториальная Гвинея", img: "https://flagcdn.com/gq.svg" },
    { country: "Эритрея", img: "https://flagcdn.com/er.svg" },
    { country: "Эстония", img: "https://flagcdn.com/ee.svg" },
    { country: "Эсватини", img: "https://flagcdn.com/sz.svg" },
    { country: "Эфиопия", img: "https://flagcdn.com/et.svg" },
    { country: "Фолклендские острова", img: "https://flagcdn.com/fk.svg" },
    { country: "Фарерские острова", img: "https://flagcdn.com/fo.svg" },
    { country: "Фиджи", img: "https://flagcdn.com/fj.svg" },
    { country: "Финляндия", img: "https://flagcdn.com/fi.svg" },
    { country: "Франция", img: "https://flagcdn.com/fr.svg" },
    { country: "Французская Гвиана", img: "https://flagcdn.com/gf.svg" },
    { country: "Французская Полинезия", img: "https://flagcdn.com/pf.svg" },
    { country: "Французские Южные и Антарктические территории", img: "https://flagcdn.com/tf.svg" },
    { country: "Габон", img: "https://flagcdn.com/ga.svg" },
    { country: "Гамбия", img: "https://flagcdn.com/gm.svg" },
    { country: "Грузия", img: "https://flagcdn.com/ge.svg" },
    { country: "Германия", img: "https://flagcdn.com/de.svg" },
    { country: "Гана", img: "https://flagcdn.com/gh.svg" },
    { country: "Гибралтар", img: "https://flagcdn.com/gi.svg" },
    { country: "Греция", img: "https://flagcdn.com/gr.svg" },
    { country: "Гренландия", img: "https://flagcdn.com/gl.svg" },
    { country: "Гренада", img: "https://flagcdn.com/gd.svg" },
    { country: "Гваделупа", img: "https://flagcdn.com/gp.svg" },
    { country: "Гуам", img: "https://flagcdn.com/gu.svg" },
    { country: "Гватемала", img: "https://flagcdn.com/gt.svg" },
    { country: "Гернси", img: "https://flagcdn.com/gg.svg" },
    { country: "Гвинея", img: "https://flagcdn.com/gn.svg" },
    { country: "Гвинея-Бисау", img: "https://flagcdn.com/gw.svg" },
    { country: "Гайана", img: "https://flagcdn.com/gy.svg" },
    { country: "Гаити", img: "https://flagcdn.com/ht.svg" },
    { country: "Острова Херд и Макдональд", img: "https://flagcdn.com/hm.svg" },
    { country: "Ватикан", img: "https://flagcdn.com/va.svg" },
    { country: "Гондурас", img: "https://flagcdn.com/hn.svg" },
    { country: "Гонконг", img: "https://flagcdn.com/hk.svg" },
    { country: "Венгрия", img: "https://flagcdn.com/hu.svg" },
    { country: "Исландия", img: "https://flagcdn.com/is.svg" },
    { country: "Индия", img: "https://flagcdn.com/in.svg" },
    { country: "Индонезия", img: "https://flagcdn.com/id.svg" },
    { country: "Иран", img: "https://flagcdn.com/ir.svg" },
    { country: "Ирак", img: "https://flagcdn.com/iq.svg" },
    { country: "Ирландия", img: "https://flagcdn.com/ie.svg" },
    { country: "Остров Мэн", img: "https://flagcdn.com/im.svg" },
    { country: "Израиль", img: "https://flagcdn.com/il.svg" },
    { country: "Италия", img: "https://flagcdn.com/it.svg" },
    { country: "Ямайка", img: "https://flagcdn.com/jm.svg" },
    { country: "Япония", img: "https://flagcdn.com/jp.svg" },
    { country: "Джерси", img: "https://flagcdn.com/je.svg" },
    { country: "Иордания", img: "https://flagcdn.com/jo.svg" },
    { country: "Казахстан", img: "https://flagcdn.com/kz.svg" },
    { country: "Кения", img: "https://flagcdn.com/ke.svg" },
    { country: "Кирибати", img: "https://flagcdn.com/ki.svg" },
    { country: "Северная Корея", img: "https://flagcdn.com/kp.svg" },
    { country: "Южная Корея", img: "https://flagcdn.com/kr.svg" },
    { country: "Кувейт", img: "https://flagcdn.com/kw.svg" },
    { country: "Киргизия", img: "https://flagcdn.com/kg.svg" },
    { country: "Лаос", img: "https://flagcdn.com/la.svg" },
    { country: "Латвия", img: "https://flagcdn.com/lv.svg" },
    { country: "Ливан", img: "https://flagcdn.com/lb.svg" },
    { country: "Лесото", img: "https://flagcdn.com/ls.svg" },
    { country: "Либерия", img: "https://flagcdn.com/lr.svg" },
    { country: "Ливия", img: "https://flagcdn.com/ly.svg" },
    { country: "Лихтенштейн", img: "https://flagcdn.com/li.svg" },
    { country: "Литва", img: "https://flagcdn.com/lt.svg" },
    { country: "Люксембург", img: "https://flagcdn.com/lu.svg" },
    { country: "Макао", img: "https://flagcdn.com/mo.svg" },
    { country: "Мадагаскар", img: "https://flagcdn.com/mg.svg" },
    { country: "Малави", img: "https://flagcdn.com/mw.svg" },
    { country: "Малайзия", img: "https://flagcdn.com/my.svg" },
    { country: "Мальдивы", img: "https://flagcdn.com/mv.svg" },
    { country: "Мали", img: "https://flagcdn.com/ml.svg" },
    { country: "Мальта", img: "https://flagcdn.com/mt.svg" },
    { country: "Маршалловы Острова", img: "https://flagcdn.com/mh.svg" },
    { country: "Мартиника", img: "https://flagcdn.com/mq.svg" },
    { country: "Мавритания", img: "https://flagcdn.com/mr.svg" },
    { country: "Маврикий", img: "https://flagcdn.com/mu.svg" },
    { country: "Майотта", img: "https://flagcdn.com/yt.svg" },
    { country: "Мексика", img: "https://flagcdn.com/mx.svg" },
    { country: "Микронезия", img: "https://flagcdn.com/fm.svg" },
    { country: "Молдавия", img: "https://flagcdn.com/md.svg" },
    { country: "Монако", img: "https://flagcdn.com/mc.svg" },
    { country: "Монголия", img: "https://flagcdn.com/mn.svg" },
    { country: "Черногория", img: "https://flagcdn.com/me.svg" },
    { country: "Монтсеррат", img: "https://flagcdn.com/ms.svg" },
    { country: "Марокко", img: "https://flagcdn.com/ma.svg" },
    { country: "Мозамбик", img: "https://flagcdn.com/mz.svg" },
    { country: "Мьянма", img: "https://flagcdn.com/mm.svg" },
    { country: "Намибия", img: "https://flagcdn.com/na.svg" },
    { country: "Науру", img: "https://flagcdn.com/nr.svg" },
    { country: "Непал", img: "https://flagcdn.com/np.svg" },
    { country: "Нидерланды", img: "https://flagcdn.com/nl.svg" },
    { country: "Новая Каледония", img: "https://flagcdn.com/nc.svg" },
    { country: "Новая Зеландия", img: "https://flagcdn.com/nz.svg" },
    { country: "Никарагуа", img: "https://flagcdn.com/ni.svg" },
    { country: "Нигер", img: "https://flagcdn.com/ne.svg" },
    { country: "Нигерия", img: "https://flagcdn.com/ng.svg" },
    { country: "Ниуэ", img: "https://flagcdn.com/nu.svg" },
    { country: "Остров Норфолк", img: "https://flagcdn.com/nf.svg" },
    { country: "Северные Марианские острова", img: "https://flagcdn.com/mp.svg" },
    { country: "Норвегия", img: "https://flagcdn.com/no.svg" },
    { country: "Оман", img: "https://flagcdn.com/om.svg" },
    { country: "Пакистан", img: "https://flagcdn.com/pk.svg" },
    { country: "Палау", img: "https://flagcdn.com/pw.svg" },
    { country: "Палестина", img: "https://flagcdn.com/ps.svg" },
    { country: "Панама", img: "https://flagcdn.com/pa.svg" },
    { country: "Папуа — Новая Гвинея", img: "https://flagcdn.com/pg.svg" },
    { country: "Парагвай", img: "https://flagcdn.com/py.svg" },
    { country: "Перу", img: "https://flagcdn.com/pe.svg" },
    { country: "Филиппины", img: "https://flagcdn.com/ph.svg" },
    { country: "Питкэрн", img: "https://flagcdn.com/pn.svg" },
    { country: "Польша", img: "https://flagcdn.com/pl.svg" },
    { country: "Португалия", img: "https://flagcdn.com/pt.svg" },
    { country: "Пуэрто-Рико", img: "https://flagcdn.com/pr.svg" },
    { country: "Катар", img: "https://flagcdn.com/qa.svg" },
    { country: "Реюньон", img: "https://flagcdn.com/re.svg" },
    { country: "Румыния", img: "https://flagcdn.com/ro.svg" },
    { country: "Россия", img: "https://flagcdn.com/ru.svg" },
    { country: "Руанда", img: "https://flagcdn.com/rw.svg" },
    { country: "Сен-Бартелеми", img: "https://flagcdn.com/bl.svg" },
    { country: "Святая Елена", img: "https://flagcdn.com/sh.svg" },
    { country: "Сент-Китс и Невис", img: "https://flagcdn.com/kn.svg" },
    { country: "Сент-Люсия", img: "https://flagcdn.com/lc.svg" },
    { country: "Сен-Мартен", img: "https://flagcdn.com/mf.svg" },
    { country: "Сен-Пьер и Микелон", img: "https://flagcdn.com/pm.svg" },
    { country: "Сент-Винсент и Гренадины", img: "https://flagcdn.com/vc.svg" },
    { country: "Самоа", img: "https://flagcdn.com/ws.svg" },
    { country: "Сан-Марино", img: "https://flagcdn.com/sm.svg" },
    { country: "Сан-Томе и Принсипи", img: "https://flagcdn.com/st.svg" },
    { country: "Саудовская Аравия", img: "https://flagcdn.com/sa.svg" },
    { country: "Сенегал", img: "https://flagcdn.com/sn.svg" },
    { country: "Сербия", img: "https://flagcdn.com/rs.svg" },
    { country: "Сейшельские Острова", img: "https://flagcdn.com/sc.svg" },
    { country: "Сьерра-Леоне", img: "https://flagcdn.com/sl.svg" },
    { country: "Сингапур", img: "https://flagcdn.com/sg.svg" },
    { country: "Синт-Мартен", img: "https://flagcdn.com/sx.svg" },
    { country: "Словакия", img: "https://flagcdn.com/sk.svg" },
    { country: "Словения", img: "https://flagcdn.com/si.svg" },
    { country: "Соломоновы Острова", img: "https://flagcdn.com/sb.svg" },
    { country: "Сомали", img: "https://flagcdn.com/so.svg" },
    { country: "Южная Африка", img: "https://flagcdn.com/za.svg" },
    { country: "Южная Георгия и Южные Сандвичевы острова", img: "https://flagcdn.com/gs.svg" },
    { country: "Южный Судан", img: "https://flagcdn.com/ss.svg" },
    { country: "Испания", img: "https://flagcdn.com/es.svg" },
    { country: "Шри-Ланка", img: "https://flagcdn.com/lk.svg" },
    { country: "Судан", img: "https://flagcdn.com/sd.svg" },
    { country: "Суринам", img: "https://flagcdn.com/sr.svg" },
    { country: "Шпицберген и Ян-Майен", img: "https://flagcdn.com/sj.svg" },
    { country: "Швеция", img: "https://flagcdn.com/se.svg" },
    { country: "Швейцария", img: "https://flagcdn.com/ch.svg" },
    { country: "Сирия", img: "https://flagcdn.com/sy.svg" },
    { country: "Тайвань", img: "https://flagcdn.com/tw.svg" },
    { country: "Таджикистан", img: "https://flagcdn.com/tj.svg" },
    { country: "Танзания", img: "https://flagcdn.com/tz.svg" },
    { country: "Таиланд", img: "https://flagcdn.com/th.svg" },
    { country: "Восточный Тимор", img: "https://flagcdn.com/tl.svg" },
    { country: "Того", img: "https://flagcdn.com/tg.svg" },
    { country: "Токелау", img: "https://flagcdn.com/tk.svg" },
    { country: "Тонга", img: "https://flagcdn.com/to.svg" },
    { country: "Тринидад и Тобаго", img: "https://flagcdn.com/tt.svg" },
    { country: "Тунис", img: "https://flagcdn.com/tn.svg" },
    { country: "Турция", img: "https://flagcdn.com/tr.svg" },
    { country: "Туркменистан", img: "https://flagcdn.com/tm.svg" },
    { country: "Теркс и Кайкос", img: "https://flagcdn.com/tc.svg" },
    { country: "Тувалу", img: "https://flagcdn.com/tv.svg" },
    { country: "Уганда", img: "https://flagcdn.com/ug.svg" },
    { country: "Украина", img: "https://flagcdn.com/ua.svg" },
    { country: "ОАЭ", img: "https://flagcdn.com/ae.svg" },
    { country: "Великобритания", img: "https://flagcdn.com/gb.svg" },
    { country: "США", img: "https://flagcdn.com/us.svg" },
    { country: "Внешние малые острова США", img: "https://flagcdn.com/um.svg" },
    { country: "Уругвай", img: "https://flagcdn.com/uy.svg" },
    { country: "Узбекистан", img: "https://flagcdn.com/uz.svg" },
    { country: "Вануату", img: "https://flagcdn.com/vu.svg" },
    { country: "Венесуэла", img: "https://flagcdn.com/ve.svg" },
    { country: "Вьетнам", img: "https://flagcdn.com/vn.svg" },
    { country: "Уоллис и Футуна", img: "https://flagcdn.com/wf.svg" },
    { country: "Западная Сахара", img: "https://flagcdn.com/eh.svg" },
    { country: "Йемен", img: "https://flagcdn.com/ye.svg" },
    { country: "Замбия", img: "https://flagcdn.com/zm.svg" },
    { country: "Зимбабве", img: "https://flagcdn.com/zw.svg" },
    { country: "Косово", img: "https://flagcdn.com/xk.svg" }
];
