name: "IndexNow"

on:
  schedule: # 매일 오전 11시에 자동 실행
    - cron: "0 11 * * *"
  workflow_dispatch: # 수동 실행 가능

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://emfls.github.io/sitemap.xml"
          since: 1
          since-unit: "week"
          key: ${{ secrets.INDEXNOW_KEY }}
